/**************************************************

ERROR: CONTACT

Bob Ali

Information Systems Developer, Information Systems

SUNY College of Environmental Science and Forestry

22 Bray Hall � 1 Forestry Drive, Syracuse, NY, 13210

bali04@esf.edu  � https://www.esf.edu/computing/

***************************************************/

WITH SPAIDEN as
(
  SELECT
      SPRIDEN.SPRIDEN_PIDM,
      SPRIDEN.SPRIDEN_ID,
      SPRIDEN.SPRIDEN_LAST_NAME,
      SPRIDEN.SPRIDEN_FIRST_NAME,
      SPRIDEN.SPRIDEN_MI,
      SPRIDEN.SPRIDEN_CHANGE_IND,
      SPRIDEN.SPRIDEN_ENTITY_IND,
      SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_MI,
      SPRIDEN.SPRIDEN_SURROGATE_ID,
      SPRIDEN.SPRIDEN_VERSION,
      f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME

  FROM
      SPRIDEN SPRIDEN

  WHERE
      SPRIDEN.SPRIDEN_NTYP_CODE is NULL
      AND SPRIDEN.SPRIDEN_CHANGE_IND is NULL
  ),

SPAPERS as
(
  SELECT
      SPBPERS.SPBPERS_PIDM,
      SPBPERS.SPBPERS_SSN,
      SPBPERS.SPBPERS_BIRTH_DATE,
      SPBPERS.SPBPERS_SEX,
      SPBPERS.SPBPERS_CONFID_IND,
      SPBPERS.SPBPERS_PREF_FIRST_NAME,
      SPBPERS.SPBPERS_CITZ_CODE,
      SPBPERS.SPBPERS_ETHN_CDE,
      SPBPERS.SPBPERS_SURROGATE_ID,
      SPBPERS.SPBPERS_VERSION,
      SPBPERS.SPBPERS_GNDR_CODE,
      GOBINTL.GOBINTL_PIDM,
      GOBINTL.GOBINTL_SPOUSE_IND,
      GOBINTL.GOBINTL_SIGNATURE_IND,
      GOBINTL.GOBINTL_NATN_CODE_BIRTH,
      GOBINTL.GOBINTL_SURROGATE_ID,
      GOBINTL.GOBINTL_VERSION,
      CASE
        WHEN SPBPERS_ETHN_CDE IN (2,3,4,5,6,7,9,10) THEN 'Y'
          ELSE 'N'
            END AS SPBPERS_SICAS_HISP_ORIGIN,
      CASE
        WHEN SPBPERS.SPBPERS_CITZ_CODE = 'Y' THEN 'United States'
          ELSE (SELECT STVNATN_NATION
               FROM    STVNATN
               WHERE   STVNATN_CODE = NVL(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
                 END AS SPBPERS_CITZ_COUNTRY,
      F_GET_DESC_FNC('STVETHN', SPBPERS_ETHN_CDE, 30) as SPBPERS_ETHN_DESC,
      F_GET_DESC_FNC('STVNATN', GOBINTL_NATN_CODE_BIRTH, 30) as GOBINTL_BIRTH_NATN,
      ROUND(((SYSDATE - SPBPERS_BIRTH_DATE)/365), 0) as SPBPERS_AGE

    FROM
        SPBPERS SPBPERS
        LEFT OUTER JOIN GOBINTL GOBINTL ON GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
    ),

SOREMAL as
(
  SELECT
      GOREMAL.GOREMAL_PIDM,
      GOREMAL.GOREMAL_EMAL_CODE,
      GOREMAL.GOREMAL_EMAIL_ADDRESS,
      GOREMAL.GOREMAL_STATUS_IND,
      GOREMAL.GOREMAL_PREFERRED_IND,
      GOREMAL.GOREMAL_ACTIVITY_DATE,
      GOREMAL.GOREMAL_SURROGATE_ID,
      GOREMAL.GOREMAL_VERSION,
      GORADID.GORADID_PIDM,
      GORADID.GORADID_ADDITIONAL_ID,
      GORADID.GORADID_ADID_CODE,
      GORADID.GORADID_SURROGATE_ID,
      GORADID.GORADID_VERSION,
      GOBTPAC.GOBTPAC_PIDM,
      GOBTPAC.GOBTPAC_PIN_DISABLED_IND,
      GOBTPAC.GOBTPAC_USAGE_ACCEPT_IND,
      GOBTPAC.GOBTPAC_PIN,
      GOBTPAC.GOBTPAC_PIN_EXP_DATE,
      GOBTPAC.GOBTPAC_SURROGATE_ID,
      GOBTPAC.GOBTPAC_VERSION,
      GOBTPAC.GOBTPAC_EXTERNAL_USER --esfid

  FROM
      GOREMAL GOREMAL
      LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
           AND GORADID.GORADID_ADID_CODE = 'SUID'
      LEFT OUTER JOIN GOBUMAP GOBUMAP ON GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
      LEFT OUTER JOIN GOBTPAC GOBTPAC ON GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

  WHERE
      GOREMAL.GOREMAL_STATUS_IND = 'A'
      AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
      AND GOREMAL.GOREMAL_EMAL_CODE IN ('ESF', 'SU', 'AD', 'PERS')
  ),

SSASECT as
(
    SELECT
      SSBSECT.SSBSECT_TERM_CODE,
      SSBSECT.SSBSECT_CRN,
      SSBSECT.SSBSECT_PTRM_CODE,
      SSBSECT.SSBSECT_SUBJ_CODE,
      SSBSECT.SSBSECT_CRSE_NUMB,
      SSBSECT.SSBSECT_SEQ_NUMB,
      SSBSECT.SSBSECT_SSTS_CODE,
      SSBSECT.SSBSECT_SCHD_CODE,
      SSBSECT.SSBSECT_CAMP_CODE,
      SSBSECT.SSBSECT_CREDIT_HRS,
      SSBSECT.SSBSECT_BILL_HRS,
      SSBSECT.SSBSECT_GMOD_CODE,
      SSBSECT.SSBSECT_REG_ONEUP,
      SSBSECT.SSBSECT_PRIOR_ENRL,
      SSBSECT.SSBSECT_PROJ_ENRL,
      SSBSECT.SSBSECT_MAX_ENRL,
      SSBSECT.SSBSECT_ENRL,
      SSBSECT.SSBSECT_SEATS_AVAIL,
      SSBSECT.SSBSECT_TOT_CREDIT_HRS,
      SSBSECT.SSBSECT_CENSUS_ENRL,
      SSBSECT.SSBSECT_CENSUS_ENRL_DATE,
      SSBSECT.SSBSECT_ACTIVITY_DATE,
      SSBSECT.SSBSECT_PTRM_START_DATE,
      SSBSECT.SSBSECT_PTRM_END_DATE,
      SSBSECT.SSBSECT_PTRM_WEEKS,
      SSBSECT.SSBSECT_WAIT_CAPACITY,
      SSBSECT.SSBSECT_WAIT_COUNT,
      SSBSECT.SSBSECT_WAIT_AVAIL,
      SSBSECT.SSBSECT_INSM_CODE,
      SSBSECT.SSBSECT_SURROGATE_ID,
      SSBSECT.SSBSECT_VERSION,
      SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID,
      SCBCRSE.SCBCRSE_SUBJ_CODE,
      SCBCRSE.SCBCRSE_CRSE_NUMB,
      SCBCRSE.SCBCRSE_EFF_TERM,
      SCBCRSE.SCBCRSE_COLL_CODE,
      SCBCRSE.SCBCRSE_DIVS_CODE,
      SCBCRSE.SCBCRSE_DEPT_CODE,
      SCBCRSE.SCBCRSE_CSTA_CODE,
      SCBCRSE.SCBCRSE_TITLE,
      SCBCRSE.SCBCRSE_CIPC_CODE,
      SCBCRSE.SCBCRSE_CREDIT_HR_IND,
      SCBCRSE.SCBCRSE_CREDIT_HR_LOW,
      SCBCRSE.SCBCRSE_CREDIT_HR_HIGH,
      SCBCRSE.SCBCRSE_LEC_HR_IND,
      SCBCRSE.SCBCRSE_LEC_HR_LOW,
      SCBCRSE.SCBCRSE_LEC_HR_HIGH,
      SCBCRSE.SCBCRSE_BILL_HR_IND,
      SCBCRSE.SCBCRSE_BILL_HR_LOW,
      SCBCRSE.SCBCRSE_BILL_HR_HIGH,
      SCBCRSE.SCBCRSE_ACTIVITY_DATE,
      SCBCRSE.SCBCRSE_CONT_HR_LOW,
      SCBCRSE.SCBCRSE_CONT_HR_IND,
      SCBCRSE.SCBCRSE_CONT_HR_HIGH,
      SCBCRSE.SCBCRSE_REPS_CODE,
      SCBCRSE.SCBCRSE_MAX_RPT_UNITS,
      SCBCRSE.SCBCRSE_SURROGATE_ID,
      SCBCRSE.SCBCRSE_VERSION,
      SCBCRSE.SCBCRSE_VPDI_CODE,
      SCBCRSE.SCBCRSE_SICAS_SUNY_ID,
      SSRMEET.SSRMEET_TERM_CODE,
      SSRMEET.SSRMEET_CRN,
      SSRMEET.SSRMEET_DAYS_CODE,
      SSRMEET.SSRMEET_DAY_NUMBER,
      SSRMEET.SSRMEET_BEGIN_TIME,
      SSRMEET.SSRMEET_END_TIME,
      SSRMEET.SSRMEET_BLDG_CODE,
      SSRMEET.SSRMEET_ROOM_CODE,
      SSRMEET.SSRMEET_ACTIVITY_DATE,
      SSRMEET.SSRMEET_START_DATE,
      SSRMEET.SSRMEET_END_DATE,
      SSRMEET.SSRMEET_SUN_DAY,
      SSRMEET.SSRMEET_MON_DAY,
      SSRMEET.SSRMEET_TUE_DAY,
      SSRMEET.SSRMEET_WED_DAY,
      SSRMEET.SSRMEET_THU_DAY,
      SSRMEET.SSRMEET_FRI_DAY,
      SSRMEET.SSRMEET_SAT_DAY,
      SSRMEET.SSRMEET_SCHD_CODE,
      SSRMEET.SSRMEET_CREDIT_HR_SESS,
      SSRMEET.SSRMEET_MEET_NO,
      SSRMEET.SSRMEET_HRS_WEEK,
      SSRMEET.SSRMEET_MTYP_CODE,
      SSRMEET.SSRMEET_SURROGATE_ID,
      SSRMEET.SSRMEET_VERSION,
      F_GET_DESC_FNC('STVSSTS', SSBSECT.SSBSECT_SSTS_CODE, 30) as SSBSECT_SSTS_DESC,
      F_GET_DESC_FNC('STVSCHD', SSBSECT.SSBSECT_SCHD_CODE, 30) as SSBSECT_SCHD_DESC,
      F_GET_DESC_FNC('STVCSTA', SCBCRSE.SCBCRSE_CSTA_CODE, 30) as SCBCRSE_CSTA_DESC,
      F_GET_DESC_FNC('STVREPS', SCBCRSE.SCBCRSE_REPS_CODE, 30) as SCBCRSE_REPS_DESC

  FROM
      SSBSECT SSBSECT

      LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT.SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
           AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB

      LEFT OUTER JOIN SSRMEET SSRMEET ON SSRMEET.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
           AND SSRMEET.SSRMEET_CRN = SSBSECT.SSBSECT_CRN
           AND SSRMEET_SURROGATE_ID = (SELECT MAX(SSRMEET_SURROGATE_ID)
                                      FROM    SSRMEET MEET
                                      WHERE   MEET.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
                                      AND     MEET.SSRMEET_CRN = SSBSECT.SSBSECT_CRN)

  WHERE
      SSBSECT.SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE
      AND SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE_EFF_TERM)
                                    FROM     SCBCRSE CRSE
                                    WHERE    CRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                    AND      CRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                    AND      CRSE.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE)
  ORDER BY
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID
  ),

SIRASGQ as
(
  SELECT
      SIRASGN.SIRASGN_TERM_CODE,
      SIRASGN.SIRASGN_CRN,
      SIRASGN.SIRASGN_PIDM,
      SIRDPCL.SIRDPCL_PIDM,
      SIRDPCL.SIRDPCL_TERM_CODE_EFF,
      SIRDPCL.SIRDPCL_COLL_CODE,
      SIRDPCL.SIRDPCL_DEPT_CODE,
      SIRASGN.SIRASGN_PRIMARY_IND,
      SSBSECT_TERM_CODE,
      SSBSECT_CRN,
      SSBSECT_PTRM_CODE,
      SSBSECT_SUBJ_CODE,
      SSBSECT_CRSE_NUMB,
      SSBSECT_SEQ_NUMB,
      SSBSECT_SSTS_CODE,
      SSBSECT_SCHD_CODE,
      SSBSECT_CAMP_CODE,
      SSBSECT_CREDIT_HRS,
      SSBSECT_BILL_HRS,
      SSBSECT_GMOD_CODE,
      SSBSECT_REG_ONEUP,
      SSBSECT_PRIOR_ENRL,
      SSBSECT_PROJ_ENRL,
      SSBSECT_MAX_ENRL,
      SSBSECT_ENRL,
      SSBSECT_SEATS_AVAIL,
      SSBSECT_TOT_CREDIT_HRS,
      SSBSECT_CENSUS_ENRL,
      SSBSECT_CENSUS_ENRL_DATE,
      SSBSECT_ACTIVITY_DATE,
      SSBSECT_PTRM_START_DATE,
      SSBSECT_PTRM_END_DATE,
      SSBSECT_PTRM_WEEKS,
      SSBSECT_WAIT_CAPACITY,
      SSBSECT_WAIT_COUNT,
      SSBSECT_WAIT_AVAIL,
      SSBSECT_INSM_CODE,
      SSBSECT_SURROGATE_ID,
      SSBSECT_VERSION,
      SSBSECT_SICAS_CAMP_COURSE_ID,
      SSBSECT_SICAS_CAMP_SECTION_ID,
      SCBCRSE_SUBJ_CODE,
      SCBCRSE_CRSE_NUMB,
      SCBCRSE_EFF_TERM,
      SCBCRSE_COLL_CODE,
      SCBCRSE_DIVS_CODE,
      SCBCRSE_DEPT_CODE,
      SCBCRSE_CSTA_CODE,
      SCBCRSE_TITLE,
      SCBCRSE_CIPC_CODE,
      SCBCRSE_CREDIT_HR_IND,
      SCBCRSE_CREDIT_HR_LOW,
      SCBCRSE_CREDIT_HR_HIGH,
      SCBCRSE_LEC_HR_IND,
      SCBCRSE_LEC_HR_LOW,
      SCBCRSE_LEC_HR_HIGH,
      SCBCRSE_BILL_HR_IND,
      SCBCRSE_BILL_HR_LOW,
      SCBCRSE_BILL_HR_HIGH,
      SCBCRSE_ACTIVITY_DATE,
      SCBCRSE_CONT_HR_LOW,
      SCBCRSE_CONT_HR_IND,
      SCBCRSE_CONT_HR_HIGH,
      SCBCRSE_REPS_CODE,
      SCBCRSE_MAX_RPT_UNITS,
      SCBCRSE_SURROGATE_ID,
      SCBCRSE_VERSION,
      SCBCRSE_VPDI_CODE,
      SCBCRSE_SICAS_SUNY_ID,
      SSRMEET_TERM_CODE,
      SSRMEET_CRN,
      SSRMEET_DAYS_CODE,
      SSRMEET_DAY_NUMBER,
      SSRMEET_BEGIN_TIME,
      SSRMEET_END_TIME,
      SSRMEET_BLDG_CODE,
      SSRMEET_ROOM_CODE,
      SSRMEET_ACTIVITY_DATE,
      SSRMEET_START_DATE,
      SSRMEET_END_DATE,
      SSRMEET_SUN_DAY,
      SSRMEET_MON_DAY,
      SSRMEET_TUE_DAY,
      SSRMEET_WED_DAY,
      SSRMEET_THU_DAY,
      SSRMEET_FRI_DAY,
      SSRMEET_SAT_DAY,
      SSRMEET_SCHD_CODE,
      SSRMEET_CREDIT_HR_SESS,
      SSRMEET_MEET_NO,
      SSRMEET_HRS_WEEK,
      SSRMEET_MTYP_CODE,
      SSRMEET_SURROGATE_ID,
      SSRMEET_VERSION,
      SSBSECT_SSTS_DESC,
      SSBSECT_SCHD_DESC,
      SCBCRSE_CSTA_DESC,
      SCBCRSE_REPS_DESC,
      CASE
        WHEN SIRDPCL_DEPT_CODE IS NULL THEN F_GET_DESC_FNC('STVDEPT', SCBCRSE_DEPT_CODE, 30)
          ELSE F_GET_DESC_FNC('STVDEPT', SIRDPCL.SIRDPCL_DEPT_CODE, 30)
            END as SIRDPCL_DEPT_DESC,
      f_format_name(SIRDPCL.SIRDPCL_PIDM, 'LF30') as SIRDPCL_INSTR_NAME,
      (SELECT GOREMAL_EMAIL_ADDRESS
      FROM    GOREMAL
      WHERE   GOREMAL_PIDM = SIRDPCL.SIRDPCL_PIDM
      AND     GOREMAL_EMAL_CODE = 'ESF'
      AND     GOREMAL_STATUS_IND = 'A'
      AND     GOREMAL_PREFERRED_IND = 'Y') as SIRDPCL_INSTR_EMAIL

  FROM
      SSASECT SSBSECT

      LEFT OUTER JOIN SIRASGN SIRASGN ON SSBSECT.SSBSECT_TERM_CODE = SIRASGN.SIRASGN_TERM_CODE
           AND SSBSECT.SSBSECT_CRN = SIRASGN.SIRASGN_CRN
           AND       SIRASGN_PRIMARY_IND = 'Y'

      LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM
           AND SIRDPCL.SIRDPCL_SURROGATE_ID = (SELECT MAX(SIRDPCL_SURROGATE_ID)
                                              FROM    SIRDPCL DPCL
                                              WHERE   DPCL.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM)
  ),

SSAMEET as
(
  SELECT
      SIRASGN.SCBCRSE_TITLE,
      SIRASGN.SSBSECT_TERM_CODE,
      SIRASGN.SSBSECT_CRN,
      SIRASGN.SSBSECT_PTRM_CODE,
      SIRASGN.SSBSECT_SUBJ_CODE,
      SIRASGN.SSBSECT_CRSE_NUMB,
      SIRASGN.SSBSECT_SEQ_NUMB,
      SIRASGN.SSBSECT_SICAS_CAMP_COURSE_ID,
      SIRASGN.SSBSECT_SCHD_CODE,
      SIRASGN.SSBSECT_CAMP_CODE,
      SIRASGN.SSBSECT_CREDIT_HRS,
      SIRASGN.SSBSECT_BILL_HRS,
      SIRASGN.SSBSECT_GMOD_CODE,
      SIRASGN.SSBSECT_REG_ONEUP,
      SIRASGN.SSBSECT_PRIOR_ENRL,
      SIRASGN.SSBSECT_PROJ_ENRL,
      SIRASGN.SSBSECT_MAX_ENRL,
      SIRASGN.SSBSECT_ENRL,
      SIRASGN.SSBSECT_SEATS_AVAIL,
      SIRASGN.SSBSECT_TOT_CREDIT_HRS,
      SIRASGN.SSBSECT_CENSUS_ENRL,
      SIRASGN.SSBSECT_CENSUS_ENRL_DATE,
      SIRASGN.SSBSECT_ACTIVITY_DATE,
      SIRASGN.SSBSECT_PTRM_START_DATE,
      SIRASGN.SSBSECT_PTRM_END_DATE,
      SIRASGN.SSBSECT_PTRM_WEEKS,
      SIRASGN.SSBSECT_WAIT_CAPACITY,
      SIRASGN.SSBSECT_WAIT_COUNT,
      SIRASGN.SSBSECT_WAIT_AVAIL,
      SIRASGN.SSBSECT_SICAS_CAMP_SECTION_ID,
      SSRMEET.SSRMEET_TERM_CODE,
      SSRMEET.SSRMEET_CRN,
      SSRMEET.SSRMEET_BEGIN_TIME,
      SSRMEET.SSRMEET_END_TIME,
      SSRMEET.SSRMEET_BLDG_CODE,
      SSRMEET.SSRMEET_ROOM_CODE,
      SSRMEET.SSRMEET_START_DATE,
      SSRMEET.SSRMEET_END_DATE,
      SSRMEET.SSRMEET_MON_DAY,
      SSRMEET.SSRMEET_TUE_DAY,
      SSRMEET.SSRMEET_WED_DAY,
      SSRMEET.SSRMEET_THU_DAY,
      SSRMEET.SSRMEET_FRI_DAY,
      SSRMEET.SSRMEET_SAT_DAY,
      SSRMEET.SSRMEET_CREDIT_HR_SESS,
      SSRMEET.SSRMEET_MEET_NO,
      SSRMEET.SSRMEET_HRS_WEEK,
      SIRASGN.SIRDPCL_INSTR_NAME,
      SIRASGN.SIRDPCL_DEPT_DESC

  FROM
      SSRMEET SSRMEET

      LEFT OUTER JOIN SIRASGQ SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSRMEET.SSRMEET_TERM_CODE
           AND SIRASGN.SIRASGN_CRN = SSRMEET.SSRMEET_CRN
           AND SIRASGN.SIRASGN_PRIMARY_IND = 'Y'

  WHERE
      SSRMEET.SSRMEET_TERM_CODE = :select_term_code.STVTERM_CODE

  ORDER BY
      SSBSECT_SICAS_CAMP_SECTION_ID
  ),

COURSE_SCHEDULE as
(
  SELECT
    SSBSECT.SSBSECT_TERM_CODE,
    SSBSECT.SSBSECT_CRN,
    SSBSECT.SSBSECT_PTRM_CODE,
    SSBSECT.SSBSECT_SUBJ_CODE,
    SSBSECT.SSBSECT_CRSE_NUMB,
    SSBSECT.SSBSECT_SEQ_NUMB,
    SSBSECT.SSBSECT_SCHD_CODE,
    SSBSECT.SSBSECT_CAMP_CODE,
    SSBSECT.SSBSECT_CREDIT_HRS,
    SSBSECT.SSBSECT_BILL_HRS,
    SSBSECT.SSBSECT_GMOD_CODE,
    SSBSECT.SSBSECT_REG_ONEUP,
    SSBSECT.SSBSECT_PRIOR_ENRL,
    SSBSECT.SSBSECT_PROJ_ENRL,
    SSBSECT.SSBSECT_MAX_ENRL,
    SSBSECT.SSBSECT_ENRL,
    SSBSECT.SSBSECT_SEATS_AVAIL,
    SSBSECT.SSBSECT_TOT_CREDIT_HRS,
    SSBSECT.SSBSECT_CENSUS_ENRL,
    SSBSECT.SSBSECT_CENSUS_ENRL_DATE,
    SSBSECT.SSBSECT_ACTIVITY_DATE,
    SSBSECT.SSBSECT_PTRM_START_DATE,
    SSBSECT.SSBSECT_PTRM_END_DATE,
    SSBSECT.SSBSECT_PTRM_WEEKS,
    SSBSECT.SSBSECT_WAIT_CAPACITY,
    SSBSECT.SSBSECT_WAIT_COUNT,
    SSBSECT.SSBSECT_WAIT_AVAIL,
    SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
    SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID,
    SIRASGN.SIRASGN_TERM_CODE,
    SIRASGN.SIRASGN_CRN,
    SIRASGN.SIRASGN_PRIMARY_IND,
    SIRDPCL.SIRDPCL_TERM_CODE_EFF,
    SIRDPCL.SIRDPCL_COLL_CODE,
    SIRDPCL.SIRDPCL_DEPT_CODE,
    SCBCRSE_SUBJ_CODE,
    SCBCRSE_CRSE_NUMB,
    SCBCRSE_EFF_TERM,
    SCBCRSE_COLL_CODE,
    SCBCRSE_DIVS_CODE,
    SCBCRSE_DEPT_CODE,
    SCBCRSE_CSTA_CODE,
    SCBCRSE_TITLE,
    SCBCRSE_CIPC_CODE,
    SCBCRSE_CREDIT_HR_IND,
    SCBCRSE_CREDIT_HR_LOW,
    SCBCRSE_CREDIT_HR_HIGH,
    SCBCRSE_LEC_HR_IND,
    SCBCRSE_LEC_HR_LOW,
    SCBCRSE_LEC_HR_HIGH,
    SCBCRSE_BILL_HR_IND,
    SCBCRSE_BILL_HR_LOW,
    SCBCRSE_BILL_HR_HIGH,
    SCBCRSE_ACTIVITY_DATE,
    SCBCRSE_CONT_HR_LOW,
    SCBCRSE_CONT_HR_IND,
    SCBCRSE_CONT_HR_HIGH,
    SCBCRSE_REPS_CODE,
    SCBCRSE_MAX_RPT_UNITS,
    SCBCRSE_SURROGATE_ID,
    SCBCRSE_VERSION,
    SCBCRSE_VPDI_CODE,
    SCBCRSE_SICAS_SUNY_ID,
    SSRMEET_TERM_CODE,
    SSRMEET_CRN,
    SSRMEET_DAYS_CODE,
    SSRMEET_DAY_NUMBER,
    SSRMEET_BEGIN_TIME,
    SSRMEET_END_TIME,
    SSRMEET_BLDG_CODE,
    SSRMEET_ROOM_CODE,
    SSRMEET_ACTIVITY_DATE,
    SSRMEET_START_DATE,
    SSRMEET_END_DATE,
    SSRMEET_SUN_DAY,
    SSRMEET_MON_DAY,
    SSRMEET_TUE_DAY,
    SSRMEET_WED_DAY,
    SSRMEET_THU_DAY,
    SSRMEET_FRI_DAY,
    SSRMEET_SAT_DAY,
    SSRMEET_SCHD_CODE,
    SSRMEET_CREDIT_HR_SESS,
    SSRMEET_MEET_NO,
    SSRMEET_HRS_WEEK,
    SSRMEET_MTYP_CODE,
    SSRMEET_SURROGATE_ID,
    SSRMEET_VERSION,
    CASE
      WHEN SIRDPCL_DEPT_CODE IS NULL THEN F_GET_DESC_FNC('STVDEPT', SCBCRSE_DEPT_CODE, 30)
        ELSE F_GET_DESC_FNC('STVDEPT', SIRDPCL.SIRDPCL_DEPT_CODE, 30)
          END as SIRDPCL_DEPT_DESC,
    f_format_name(SIRDPCL.SIRDPCL_PIDM, 'LF30') as SIRDPCL_INSTR_NAME,
    (SELECT GOREMAL_EMAIL_ADDRESS
    FROM    GOREMAL
    WHERE   GOREMAL_PIDM = SIRDPCL.SIRDPCL_PIDM
    AND     GOREMAL_EMAL_CODE = 'ESF'
    AND     GOREMAL_STATUS_IND = 'A'
    AND     GOREMAL_PREFERRED_IND = 'Y') as SIRDPCL_INSTR_EMAIL

  FROM
      SSASECT SSBSECT
      LEFT OUTER JOIN SIRASGN SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
           AND SSBSECT.SSBSECT_CRN = SIRASGN.SIRASGN_CRN
           AND SIRASGN_PRIMARY_IND = 'Y'

      LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM
           AND SIRDPCL.SIRDPCL_SURROGATE_ID = (SELECT MAX(SIRDPCL_SURROGATE_ID)
                                              FROM    SIRDPCL DPCL
                                              WHERE   DPCL.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM)

  WHERE
      SSBSECT.SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE
  )

-- reporting
SELECT
    STVTERM.STVTERM_DESC as TERM_DESC,
-- Departmental Instructor Info
    SIRASGN_TERM_CODE as Instructor_Term_Code,
    SIRASGN_CRN as Instructor_CRN,
    SIRDPCL_TERM_CODE_EFF as Dept_Eff_Term,
    SIRDPCL_COLL_CODE as Dept_Coll_Code,
    SIRDPCL_DEPT_CODE as Dept_Code,
    SIRASGN_PRIMARY_IND as Dept_Prim_Ind,
    SIRDPCL_DEPT_DESC as Dept_Desc,
    SIRDPCL_INSTR_NAME as Dept_Instr_Name,
    SIRDPCL_INSTR_EMAIL as Dept_Instr_Email,

-- Course Section Info
    SSBSECT_TERM_CODE as Section_Term_Code,
    SSBSECT_CRN as Section_CRN,
    SSBSECT_PTRM_CODE as Section_PTRM,
    SSBSECT_SUBJ_CODE as Section_Subj,
    SSBSECT_CRSE_NUMB as Section_Numb,
    SSBSECT_SEQ_NUMB as Section_Seq_No,
    SSBSECT_SCHD_CODE as Section_SCHD_Code,
    SSBSECT_CAMP_CODE as Section_Camp_Code,
    SSBSECT_CREDIT_HRS as Section_Credit_Hr,
    SSBSECT_BILL_HRS as Section_Bill_Hr,
    SSBSECT_GMOD_CODE as Section_GMOD_Code,
    SSBSECT_REG_ONEUP as Section_Reg_Oneup,
    SSBSECT_PRIOR_ENRL as Section_Prior_Enrl,
    SSBSECT_PROJ_ENRL as Section_Proj_Enrl,
    SSBSECT_MAX_ENRL as Section_Max_Enrl,
    SSBSECT_ENRL as Section_Enrl,
    SSBSECT_SEATS_AVAIL as Section_Seats_Avail,
    SSBSECT_TOT_CREDIT_HRS as Section_Tot_Credit_Hr,
    SSBSECT_CENSUS_ENRL as Section_Census_Enrl,
    SSBSECT_CENSUS_ENRL_DATE as Section_Census_Enrl_Date,
    SSBSECT_ACTIVITY_DATE as Section_Activity,
    SSBSECT_PTRM_START_DATE as Section_PTRM_Start_Date,
    SSBSECT_PTRM_END_DATE as Section_PTRM_End_Date,
    SSBSECT_PTRM_WEEKS as Section_PTRM_Weeks,
    SSBSECT_WAIT_CAPACITY as Section_Wait_Capactiy,
    SSBSECT_WAIT_COUNT as Section_Wait_Count,
    SSBSECT_WAIT_AVAIL as Section_Wait_Avail,
    SSBSECT_SICAS_CAMP_COURSE_ID as SICAS_Course_ID,
    SSBSECT_SICAS_CAMP_SECTION_ID as SICAS_Section_ID,
    SCBCRSE_SUBJ_CODE as Course_Subj,
    SCBCRSE_CRSE_NUMB as Course_Numb,
    SCBCRSE_EFF_TERM as Course_Eff_Term,
    SCBCRSE_COLL_CODE as Course_Coll_Code,
    SCBCRSE_DIVS_CODE as Course_DIVS_Code,
    SCBCRSE_DEPT_CODE as Course_Dept,
    SCBCRSE_CSTA_CODE as Course_Active,
    SCBCRSE_TITLE as Course_Title,
    SCBCRSE_CIPC_CODE as Course_CIPC_Code,
    SCBCRSE_CREDIT_HR_IND as Course_Credit_Hr_Ind,
    SCBCRSE_CREDIT_HR_LOW as Course_Credit_Hr_Low,
    SCBCRSE_CREDIT_HR_HIGH as Course_Credit_Hr_Low,
    SCBCRSE_LEC_HR_IND as Course_LEC_HR_Ind,
    SCBCRSE_LEC_HR_LOW as Course_LEC_HR_Low,
    SCBCRSE_LEC_HR_HIGH as Course_LEC_HR_High,
    SCBCRSE_BILL_HR_IND as Course_BILL_HR_Ind,
    SCBCRSE_BILL_HR_LOW as Course_BILL_HR_Low,
    SCBCRSE_BILL_HR_HIGH as Course_BILL_HR_High,
    SCBCRSE_ACTIVITY_DATE as Course_Activity,
    SCBCRSE_CONT_HR_LOW as Course_Cont_HR_Low,
    SCBCRSE_CONT_HR_IND as Course_Cont_HR_Ind,
    SCBCRSE_CONT_HR_HIGH as Course_Cont_HR_High,
    SCBCRSE_REPS_CODE as Course_Reps_Code,
    SCBCRSE_MAX_RPT_UNITS as Course_Max_Repeat_Units,
    SCBCRSE_VPDI_CODE as Course_VPDI_Code,
    SSRMEET_TERM_CODE as Meeting_Term_Code,

-- Schedule of Classes
    SSRMEET_TERM_CODE as Metting_Term_Code,
    SSRMEET_CRN as Metting_CRN,
    SSRMEET_DAYS_CODE as Meeting_Days_Code,
    SSRMEET_DAY_NUMBER as Meeting_Days_No,
    SSRMEET_BEGIN_TIME as Meeting_Begin_Time,
    SSRMEET_END_TIME as Meeting_End_Time,
    SSRMEET_BLDG_CODE as Meeting_BLDG_Code,
    SSRMEET_ROOM_CODE as Meeting_Room_Code,
    SSRMEET_ACTIVITY_DATE as Meeting_Activity,
    SSRMEET_START_DATE as Meeting_Start_Date,
    SSRMEET_END_DATE as Meeting_End_Date,
    SSRMEET_SUN_DAY as Meeting_Sun,
    SSRMEET_MON_DAY as Meeting_Mon,
    SSRMEET_TUE_DAY as Meeting_Tue,
    SSRMEET_WED_DAY as Meeting_Wed,
    SSRMEET_THU_DAY as Meeting_Thu,
    SSRMEET_FRI_DAY as Meeting_Fri,
    SSRMEET_SAT_DAY as Meeting_Sat,
    SSRMEET_CREDIT_HR_SESS as Meeting_Credit_Hr_Sess,
    SSRMEET_MEET_NO as Meeting_Meet_No,
    SSRMEET_HRS_WEEK as Meeting_Hrs_Week

FROM
      COURSE_SCHEDULE B
--    DUAL
--    LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE
    LEFT OUTER JOIN STVTERM STVTERM ON STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE

WHERE
    NULL IS NULL

      -- ENROLLMENT CONDITIONS
--    AND 'Y' = F_REGISTERED_THIS_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
--    AND EXISTS (SELECT * FROM SFAREGS WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN ('RE', 'RW'))
--    AND EXISTS (SELECT * FROM SFAREGS WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN (SELECT STVRSTS_CODE FROM STVRSTS))

--$addfilter

--$beginorder

ORDER BY
    1

--$endorder
