/****************************************************
ERROR: CONTACT

Bob Ali

Information Systems Developer, Information Systems

SUNY College of Environmental Science and Forestry

22 Bray Hall � 1 Forestry Drive, Syracuse, NY, 13210

bali04@esf.edu  � https://www.esf.edu/computing/

***************************************************/

WITH SPAIDEN as
(
  SELECT
      SPRIDEN.SPRIDEN_PIDM,
      SPRIDEN.SPRIDEN_ID,
      SPRIDEN.SPRIDEN_LAST_NAME,
      SPRIDEN.SPRIDEN_FIRST_NAME,
      SPRIDEN.SPRIDEN_MI,
      SPRIDEN.SPRIDEN_CHANGE_IND,
      SPRIDEN.SPRIDEN_ENTITY_IND,
      SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_MI,
      SPRIDEN.SPRIDEN_SURROGATE_ID,
      SPRIDEN.SPRIDEN_VERSION,
      f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME

  FROM
      SPRIDEN SPRIDEN

  WHERE
      SPRIDEN.SPRIDEN_NTYP_CODE is NULL
      AND SPRIDEN.SPRIDEN_CHANGE_IND is NULL
  ),

TUIADDR as
(
  SELECT
      SPRADDR.SPRADDR_PIDM,
      SPRADDR.SPRADDR_ATYP_CODE,
      SPRADDR.SPRADDR_SEQNO,
      SPRADDR.SPRADDR_FROM_DATE,
      SPRADDR.SPRADDR_TO_DATE,
      SPRADDR.SPRADDR_STREET_LINE1,
      SPRADDR.SPRADDR_STREET_LINE2,
      SPRADDR.SPRADDR_STREET_LINE3,
      SPRADDR.SPRADDR_CITY,
      SPRADDR.SPRADDR_STAT_CODE,
      SPRADDR.SPRADDR_ZIP,
      SPRADDR.SPRADDR_CNTY_CODE,
      f_get_desc_fnc('STVATYP', SPRADDR.SPRADDR_ATYP_CODE, 30) as SPRADDR_ATYP_DESC,
      f_get_desc_fnc('STVCNTY', SPRADDR.SPRADDR_CNTY_CODE, 30) as SPRADDR_CNTY_DESC

  FROM
      SPRADDR SPRADDR

  WHERE
      SPRADDR.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
      AND SPRADDR.SPRADDR_STATUS_IND IS NULL
      AND SPRADDR.SPRADDR_VERSION = (SELECT MAX(SPRADDR_VERSION)
                                    FROM   SPRADDR ADDR
                                    WHERE  ADDR.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                    AND    ADDR.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
                                    AND    ADDR.SPRADDR_STATUS_IND IS NULL)
      AND SPRADDR.SPRADDR_SURROGATE_ID = (SELECT MAX(SPRADDR_SURROGATE_ID)
                                         FROM    SPRADDR ADDR
                                         WHERE   ADDR.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                         AND     ADDR.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
                                         AND     ADDR.SPRADDR_STATUS_IND IS NULL)
  ),

SPATELE as
(
  SELECT
      SPRTELE.SPRTELE_PIDM,
      SPRTELE.SPRTELE_TELE_CODE,
      SPRTELE.SPRTELE_PHONE_AREA,
      SPRTELE.SPRTELE_PHONE_NUMBER,
      SPRTELE.SPRTELE_SURROGATE_ID,
      SPRTELE.SPRTELE_VERSION,
      f_get_desc_fnc('STVTELE', SPRTELE.SPRTELE_TELE_CODE, 30) as SPRTELE_TELE_DESC

  FROM
      SPRTELE SPRTELE

  WHERE
      SPRTELE.SPRTELE_SURROGATE_ID = (SELECT MAX(SPRTELE_SURROGATE_ID)
                                     FROM    SPRTELE TELE
                                     WHERE   TELE.SPRTELE_PIDM = SPRTELE.SPRTELE_PIDM
                                     AND     TELE.SPRTELE_STATUS_IND IS NULL)
  ),

SPAEMRG AS
(
  SELECT
      SPREMRG.SPREMRG_PIDM,
      SPREMRG.SPREMRG_PRIORITY,
      SPREMRG.SPREMRG_LAST_NAME,
      SPREMRG.SPREMRG_FIRST_NAME,
      SPREMRG.SPREMRG_MI,
      SPREMRG.SPREMRG_STREET_LINE1,
      SPREMRG.SPREMRG_STREET_LINE2,
      SPREMRG.SPREMRG_STREET_LINE3,
      SPREMRG.SPREMRG_CITY,
      SPREMRG.SPREMRG_STAT_CODE,
      SPREMRG.SPREMRG_NATN_CODE,
      SPREMRG.SPREMRG_ZIP,
      SPREMRG.SPREMRG_PHONE_AREA,
      SPREMRG.SPREMRG_PHONE_NUMBER,
      SPREMRG.SPREMRG_PHONE_EXT,
      SPREMRG.SPREMRG_RELT_CODE,
      SPREMRG.SPREMRG_ACTIVITY_DATE,
      SPREMRG.SPREMRG_ATYP_CODE,
      SPREMRG.SPREMRG_HOUSE_NUMBER,
      SPREMRG.SPREMRG_STREET_LINE4,
      SPREMRG.SPREMRG_SURROGATE_ID,
      SPREMRG.SPREMRG_VERSION,
      f_get_desc_fnc('STVRELT', SPREMRG.SPREMRG_RELT_CODE, 30) as SPREMRG_RELT_DESC

  FROM
      SPREMRG SPREMRG
  ),

SPAPERS as
(
  SELECT
      SPBPERS.SPBPERS_PIDM,
      SPBPERS.SPBPERS_SSN,
      SPBPERS.SPBPERS_BIRTH_DATE,
      SPBPERS.SPBPERS_SEX,
      SPBPERS.SPBPERS_CONFID_IND,
      SPBPERS.SPBPERS_PREF_FIRST_NAME,
      SPBPERS.SPBPERS_CITZ_CODE,
      SPBPERS.SPBPERS_ETHN_CDE,
      SPBPERS.SPBPERS_SURROGATE_ID,
      SPBPERS.SPBPERS_VERSION,
      SPBPERS.SPBPERS_GNDR_CODE,
      GOBINTL.GOBINTL_PIDM,
      GOBINTL.GOBINTL_SPOUSE_IND,
      GOBINTL.GOBINTL_SIGNATURE_IND,
      GOBINTL.GOBINTL_NATN_CODE_BIRTH,
      GOBINTL.GOBINTL_SURROGATE_ID,
      GOBINTL.GOBINTL_VERSION,
      CASE
        WHEN SPBPERS_ETHN_CDE IN (2,3,4,5,6,7,9,10) THEN 'Y'
          ELSE 'N'
            END AS SPBPERS_SICAS_HISP_ORIGIN,
      CASE
        WHEN SPBPERS.SPBPERS_CITZ_CODE = 'Y' THEN 'United States'
          ELSE (SELECT STVNATN_NATION
               FROM    STVNATN
               WHERE   STVNATN_CODE = NVL(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
                 END AS SPBPERS_CITZ_COUNTRY,
      F_GET_DESC_FNC('STVETHN', SPBPERS_ETHN_CDE, 30) as SPBPERS_ETHN_DESC,
      F_GET_DESC_FNC('STVNATN', GOBINTL_NATN_CODE_BIRTH, 30) as GOBINTL_BIRTH_NATN,
      ROUND(((SYSDATE - SPBPERS_BIRTH_DATE)/365), 0) as SPBPERS_AGE

    FROM
        SPBPERS SPBPERS
        LEFT OUTER JOIN GOBINTL GOBINTL ON GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
    ),

GOARACE as
(
  SELECT
      GORPRAC.GORPRAC_PIDM AS GORPRAC_PIDM,
      (LISTAGG(GORPRAC.GORPRAC_RACE_CDE,', ') WITHIN GROUP (ORDER BY GORPRAC.GORPRAC_RACE_CDE)) AS GORRACE_RACE_CDE,
      (LISTAGG(GORRACE.GORRACE_DESC,', ') WITHIN GROUP (ORDER BY GORRACE.GORRACE_DESC)) AS GORRACE_DESC

  FROM
      GORPRAC GORPRAC
      LEFT OUTER JOIN GORRACE GORRACE ON GORRACE.GORRACE_RACE_CDE = GORPRAC.GORPRAC_RACE_CDE

  GROUP BY
      GORPRAC.GORPRAC_PIDM
  ),

SOREMAL as
(
  SELECT
      GOREMAL.GOREMAL_PIDM,
      GOREMAL.GOREMAL_EMAL_CODE,
      GOREMAL.GOREMAL_EMAIL_ADDRESS,
      GOREMAL.GOREMAL_STATUS_IND,
      GOREMAL.GOREMAL_PREFERRED_IND,
      GOREMAL.GOREMAL_ACTIVITY_DATE,
      GOREMAL.GOREMAL_SURROGATE_ID,
      GOREMAL.GOREMAL_VERSION,
      GORADID.GORADID_PIDM,
      GORADID.GORADID_ADDITIONAL_ID,
      GORADID.GORADID_ADID_CODE,
      GORADID.GORADID_SURROGATE_ID,
      GORADID.GORADID_VERSION,
      GOBTPAC.GOBTPAC_PIDM,
      GOBTPAC.GOBTPAC_PIN_DISABLED_IND,
      GOBTPAC.GOBTPAC_USAGE_ACCEPT_IND,
      GOBTPAC.GOBTPAC_PIN,
      GOBTPAC.GOBTPAC_PIN_EXP_DATE,
      GOBTPAC.GOBTPAC_SURROGATE_ID,
      GOBTPAC.GOBTPAC_VERSION,
      GOBTPAC.GOBTPAC_EXTERNAL_USER --esfid

  FROM
      GOREMAL GOREMAL
      LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
           AND GORADID.GORADID_ADID_CODE = 'SUID'
      LEFT OUTER JOIN GOBUMAP GOBUMAP ON GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
      LEFT OUTER JOIN GOBTPAC GOBTPAC ON GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

  WHERE
      GOREMAL.GOREMAL_STATUS_IND = 'A'
      AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
      AND GOREMAL.GOREMAL_EMAL_CODE IN ('ESF', 'SU', 'AD', 'PERS')
  ),

SGASTDN as
(
  SELECT
      SGBSTDN.SGBSTDN_PIDM,
      SGBSTDN.SGBSTDN_TERM_CODE_EFF,
      SGBSTDN.SGBSTDN_STST_CODE,
      SGBSTDN.SGBSTDN_LEVL_CODE,
      SGBSTDN.SGBSTDN_STYP_CODE,
      SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
      SGBSTDN.SGBSTDN_TERM_CODE_ADMIT,
      SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN.SGBSTDN_CAMP_CODE,
      SGBSTDN.SGBSTDN_COLL_CODE_1,
      SGBSTDN.SGBSTDN_DEGC_CODE_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN.SGBSTDN_RESD_CODE,
      SGBSTDN.SGBSTDN_ADMT_CODE,
      SGBSTDN.SGBSTDN_DEPT_CODE,
      SGBSTDN.SGBSTDN_PROGRAM_1,
      SGBSTDN.SGBSTDN_TERM_CODE_GRAD,
      SGBSTDN.SGBSTDN_ACTIVITY_DATE,
      SFRTHST.SFRTHST_PIDM,
      SFRTHST.SFRTHST_TERM_CODE,
      SFRTHST.SFRTHST_TMST_CODE,
      SFRTHST.SFRTHST_TMST_DATE,
      SFRTHST.SFRTHST_SURROGATE_ID,
      SFRTHST.SFRTHST_VERSION,
      CASE
        WHEN SFRTHST_TMST_CODE IS NULL THEN NULL
          ELSE f_Get_desc_fnc('STVTMST', SFRTHST.SFRTHST_TMST_CODE, 30)
            END as SFRTHST_TMST_DESC,
      f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM, SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF) as SGBSTDN_CLAS_CODE,
      f_get_desc_fnc('STVTERM',SGBSTDN.SGBSTDN_TERM_CODE_EFF, 30) as SGBSTDN_TERM_EFF_DESC,
      f_get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
      f_get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
      f_get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
      f_get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
      f_get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
      f_get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
      f_get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
      f_get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_MATRIC, 30) as SGBSTDN_MATRIC_TERM_DESC,
      f_get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_GRAD, 30) as SGBSTDN_GRAD_TERM_DESC,
      f_get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF), 30) as SGBSTDN_CLAS_DESC

  FROM
      SGBSTDN SGBSTDN
      LEFT OUTER JOIN SFRTHST SFRTHST ON SFRTHST.SFRTHST_PIDM = SGBSTDN.SGBSTDN_PIDM
           AND SFRTHST_SURROGATE_ID = (SELECT MAX(SFRTHST_SURROGATE_ID)
                                      FROM   SFRTHST TMST
                                      WHERE  TMST.SFRTHST_PIDM = SGBSTDN.SGBSTDN_PIDM
                                      AND    TMST.SFRTHST_TERM_CODE = SGBSTDN.SGBSTDN_TERM_CODE_EFF)
  ),

SHADEGR as
(
  SELECT
      SHRDGMR.SHRDGMR_PIDM,
      SHRDGMR.SHRDGMR_SEQ_NO,
      SHRDGMR.SHRDGMR_DEGC_CODE,
      SHRDGMR.SHRDGMR_DEGS_CODE,
      SHRDGMR.SHRDGMR_LEVL_CODE,
      SHRDGMR.SHRDGMR_COLL_CODE_1,
      SHRDGMR.SHRDGMR_MAJR_CODE_1,
      SHRDGMR.SHRDGMR_MAJR_CODE_MINR_1,
      SHRDGMR.SHRDGMR_MAJR_CODE_CONC_1,
      SHRDGMR.SHRDGMR_APPL_DATE,
      SHRDGMR.SHRDGMR_GRAD_DATE,
      SHRDGMR.SHRDGMR_ACYR_CODE_BULLETIN,
      SHRDGMR.SHRDGMR_CAMP_CODE,
      SHRDGMR.SHRDGMR_TERM_CODE_GRAD,
      SHRDGMR.SHRDGMR_ACYR_CODE,
      SHRDGMR.SHRDGMR_TERM_CODE_STUREC,
      SHRDGMR.SHRDGMR_ACTIVITY_DATE,
      SHRDGMR.SHRDGMR_GRST_CODE,
      SHRDGMR.SHRDGMR_TERM_CODE_COMPLETED,
      SHRDGMR.SHRDGMR_DEPT_CODE,
      SHRDGMR.SHRDGMR_PROGRAM,
      SHRDGMR.SHRDGMR_SURROGATE_ID,
      SHRDGMR.SHRDGMR_VERSION,
      SHRDGIH.SHRDGIH_PIDM,
      SHRDGIH.SHRDGIH_DGMR_SEQ_NO,
      SHRDGIH.SHRDGIH_HONR_CODE,
      SHRDGIH.SHRDGIH_ACTIVITY_DATE,
      SHRDGIH.SHRDGIH_TRANSC_PRT_IND,
      SHRDGIH.SHRDGIH_COMMENCE_PRT_IND,
      SHRDGIH.SHRDGIH_EDI_DEFAULT,
      SHRDGIH.SHRDGIH_SURROGATE_ID,
      SHRDGIH.SHRDGIH_VERSION,
      CASE
        WHEN SHRDGIH.SHRDGIH_HONR_CODE IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVHONR', SHRDGIH.SHRDGIH_HONR_CODE, 30)
            END as SHRDGIH_HONR_DESC,
      f_get_desc_fnc('STVDEGS', SHRDGMR.SHRDGMR_DEGS_CODE, 30) as SHRDGMR_DEGS_DESC,
      f_get_desc_fnc('STVDEGC', SHRDGMR.SHRDGMR_DEGC_CODE, 30) as SHRDGMR_DEGC_DESC,
      f_get_desc_fnc('STVLEVL', SHRDGMR.SHRDGMR_LEVL_CODE, 30) as SHRDGMR_LEVL_DESC,
      f_get_desc_fnc('STVMAJR', SHRDGMR.SHRDGMR_MAJR_CODE_1, 30) as SHRDGMR_MAJR_DESC,
      f_get_desc_fnc('STVMAJR', SHRDGMR.SHRDGMR_COLL_CODE_1, 30) as SHRDGMR_COLL_DESC,
      f_get_desc_fnc('STVGRST', SHRDGMR.SHRDGMR_GRST_CODE, 30) as SHRDGMR_GRST_DESC

  FROM
      SHRDGMR SHRDGMR
      LEFT OUTER JOIN SHRDGIH SHRDGIH ON SHRDGIH.SHRDGIH_PIDM = SHRDGMR.SHRDGMR_PIDM
           AND SHRDGIH.SHRDGIH_DGMR_SEQ_NO = SHRDGMR.SHRDGMR_SEQ_NO

  WHERE
      SHRDGMR.SHRDGMR_TERM_CODE_GRAD = (SELECT MAX(SHRDGMR_TERM_CODE_GRAD)
                                       FROM    SHRDGMR DGMR
                                       WHERE   DGMR.SHRDGMR_PIDM = SHRDGMR.SHRDGMR_PIDM
                                       AND     DGMR.SHRDGMR_TERM_CODE_GRAD <= :select_term_code.STVTERM_CODE)
  ),

SFAWDRL as
(
  SELECT
      SFRWDRL.SFRWDRL_PIDM,
      SFRWDRL.SFRWDRL_TERM_CODE,
      SFRWDRL.SFRWDRL_SEQ_NO,
      SFRWDRL.SFRWDRL_WDRL_CODE,
      SFRWDRL.SFRWDRL_EFF_WDRL_DATE,
      SFRWDRL.SFRWDRL_ESTS_CODE,
      SFRWDRL.SFRWDRL_ESTS_DATE,
      SFRWDRL.SFRWDRL_TIV_IND,
      SFRWDRL.SFRWDRL_PROCESSED_IND,
      SFRWDRL.SFRWDRL_ENRL_START_DATE,
      SFRWDRL.SFRWDRL_ENRL_END_DATE,
      SFRWDRL.SFRWDRL_ENRL_DAYS,
      SFRWDRL.SFRWDRL_ATTEND_DAYS,
      SFRWDRL.SFRWDRL_PERCENT_ATTEND,
      SFRWDRL.SFRWDRL_ORIGINAL_CHARGES,
      SFRWDRL.SFRWDRL_ACTIVITY_DATE,
      SFRWDRL.SFRWDRL_SURROGATE_ID,
      SFRWDRL.SFRWDRL_VERSION,
      f_get_desc_fnc('STVESTS', SFRWDRL.SFRWDRL_ESTS_CODE, 30) as SFRWDRL_ESTS_DESC

  FROM
      SFRWDRL SFRWDRL

  WHERE
      SFRWDRL.SFRWDRL_TERM_CODE = (SELECT MAX(SFRWDRL_TERM_CODE)
                                  FROM    SFRWDRL WDRL
                                  WHERE   WDRL.SFRWDRL_PIDM = SFRWDRL_PIDM
                                  AND     WDRL.SFRWDRL_TERM_CODE <= :select_term_code.STVTERM_CODE)
  ),

SAAADMS as
(
  SELECT
        SARADAP.SARADAP_PIDM,
        SARADAP.SARADAP_TERM_CODE_ENTRY,
        SARADAP.SARADAP_APPL_NO,
        SARADAP.SARADAP_LEVL_CODE,
        SARADAP.SARADAP_APPL_DATE,
        SARADAP.SARADAP_APST_CODE,
        SARADAP.SARADAP_APST_DATE,
        SARADAP.SARADAP_MAINT_IND,
        SARADAP.SARADAP_ADMT_CODE,
        SARADAP.SARADAP_STYP_CODE,
        SARADAP.SARADAP_CAMP_CODE,
        SARADAP.SARADAP_COLL_CODE_1,
        SARADAP.SARADAP_DEGC_CODE_1,
        SARADAP.SARADAP_MAJR_CODE_1,
        SARADAP.SARADAP_RESD_CODE,
        SARADAP.SARADAP_ACTIVITY_DATE,
        SARADAP.SARADAP_DEPT_CODE,
        SARADAP.SARADAP_PROGRAM_1,
        SARADAP.SARADAP_TERM_CODE_CTLG_1,
        SARADAP.SARADAP_WEB_TRANS_NO,
        SARADAP.SARADAP_WEB_AMOUNT,
        SARADAP.SARADAP_WEB_RECEIPT_NUMBER,
        SARADAP.SARADAP_SURROGATE_ID,
        SARADAP.SARADAP_VERSION,
        SARAPPD.SARAPPD_PIDM,
        SARAPPD.SARAPPD_TERM_CODE_ENTRY,
        SARAPPD.SARAPPD_APPL_NO,
        SARAPPD.SARAPPD_SEQ_NO,
        SARAPPD.SARAPPD_APDC_DATE,
        SARAPPD.SARAPPD_APDC_CODE,
        SARAPPD.SARAPPD_MAINT_IND,
        SARAPPD.SARAPPD_ACTIVITY_DATE,
        SARAPPD.SARAPPD_USER,
        SARAPPD.SARAPPD_DATA_ORIGIN,
        SARAPPD.SARAPPD_SURROGATE_ID,
        SARAPPD.SARAPPD_VERSION,
        SARAPPD.SARAPPD_USER_ID,
        SARAPPD.SARAPPD_VPDI_CODE,
        SARAPPD.SARAPPD_GUID,
        SARAPPD.SARAPPD_DFE_ADMN_DECN_GUID,
        f_get_desc_fnc('STVLEVL', SARADAP.SARADAP_LEVL_CODE, 30) as SARADAP_LEVL_DESC,
        f_get_desc_fnc('STVAPST', SARADAP.SARADAP_APST_CODE, 30) as SARADAP_APST_DESC,
        f_get_desc_fnc('STVADMT', SARADAP.SARADAP_ADMT_CODE, 30) as SARADAP_ADMT_DESC,
        f_get_desc_fnc('STVAPST', SARADAP.SARADAP_STYP_CODE, 30) as SARADAP_STYP_DESC,
        f_get_desc_fnc('STVCAMP', SARADAP.SARADAP_CAMP_CODE, 30) as SARADAP_CAMP_DESC,
        f_get_desc_fnc('STVAPST', SARADAP.SARADAP_COLL_CODE_1, 30) as SARADAP_COLL_DESC,
        f_get_desc_fnc('STVDEGC', SARADAP.SARADAP_DEGC_CODE_1, 30) as SARADAP_DEGC_DESC,
        f_get_desc_fnc('STVMAJR', SARADAP.SARADAP_MAJR_CODE_1, 30) as SARADAP_MAJR_DESC,
        f_get_desc_fnc('STVRESD', SARADAP.SARADAP_RESD_CODE, 30) as SARADAP_RESD_DESC,
        f_get_desc_fnc('STVDEPT', SARADAP.SARADAP_DEPT_CODE, 30) as SARADAP_DEPT_DESC,
        f_get_desc_fnc('STVAPDC', SARAPPD.SARAPPD_APDC_CODE, 30) as SARAPPD_APDC_DESC

    FROM
        SARADAP SARADAP
        LEFT OUTER JOIN SARAPPD SARAPPD ON SARAPPD.SARAPPD_PIDM = SARADAP.SARADAP_PIDM
             AND SARAPPD.SARAPPD_TERM_CODE_ENTRY = SARADAP.SARADAP_TERM_CODE_ENTRY
             AND SARAPPD.SARAPPD_APPL_NO = SARADAP.SARADAP_APPL_NO

    WHERE
        SARADAP.SARADAP_APPL_NO = (SELECT MAX(SARADAP_APPL_NO)
                                  FROM    SARADAP ADAP
                                  WHERE   ADAP.SARADAP_PIDM = SARADAP.SARADAP_PIDM)
        AND SARAPPD.SARAPPD_SEQ_NO = (SELECT MAX(SARAPPD_SEQ_NO)
                                     FROM    SARAPPD APPD
                                     WHERE   APPD.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM
                                     AND     APPD.SARAPPD_TERM_CODE_ENTRY = SARAPPD.SARAPPD_TERM_CODE_ENTRY
                                     AND     APPD.SARAPPD_APPL_NO = SARAPPD.SARAPPD_APPL_NO)
        AND SARAPPD.SARAPPD_APPL_NO = (SELECT MAX(SARAPPD_APPL_NO)
                                      FROM    SARAPPD APPD
                                      WHERE   APPD.SARAPPD_PIDM = SARAPPD.SARAPPD_PIDM
                                      AND     APPD.SARAPPD_TERM_CODE_ENTRY = SARAPPD.SARAPPD_TERM_CODE_ENTRY
                                      AND     APPD.SARAPPD_APPL_NO = SARAPPD.SARAPPD_APPL_NO)
    ),

SOAPCOL as
(
    SELECT
        SORPCOL.SORPCOL_PIDM,
        SORPCOL.SORPCOL_SBGI_CODE,
        SORPCOL.SORPCOL_TRANS_RECV_DATE,
        SORPCOL.SORPCOL_TRANS_REV_DATE,
        SORPCOL.SORPCOL_OFFICIAL_TRANS,
        SORPCOL.SORPCOL_ADMR_CODE,
        SORPCOL.SORPCOL_ACTIVITY_DATE,
        SORPCOL.SORPCOL_DATA_ORIGIN,
        SORPCOL.SORPCOL_USER_ID,
        SORPCOL.SORPCOL_SURROGATE_ID,
        SORPCOL.SORPCOL_VERSION,
        SORPCOL.SORPCOL_VPDI_CODE,
        SORPCOL.SORPCOL_GUID,
        SORPCOL.SORPCOL_GPA,
        SORPCOL.SORPCOL_TOTAL_CREDITS,
        SORDEGR.SORDEGR_PIDM,
        SORDEGR.SORDEGR_SBGI_CODE,
        SORDEGR.SORDEGR_DEGC_CODE,
        SORDEGR.SORDEGR_DEGR_SEQ_NO,
        SORDEGR.SORDEGR_ATTEND_FROM,
        SORDEGR.SORDEGR_ATTEND_TO,
        SORDEGR.SORDEGR_HOURS_TRANSFERRED,
        SORDEGR.SORDEGR_GPA_TRANSFERRED,
        SORDEGR.SORDEGR_DEGC_DATE,
        SORDEGR.SORDEGR_ACTIVITY_DATE,
        SORDEGR.SORDEGR_PRIMARY_IND,
        SORDEGR.SORDEGR_SURROGATE_ID,
        SORDEGR.SORDEGR_VERSION,
        CASE
          WHEN SORPCOL.SORPCOL_ADMR_CODE IS NULL THEN ''
            ELSE F_GET_DESC_FNC('STVADMR', SORPCOL.SORPCOL_ADMR_CODE, 30)
              END as SORPCOL_ADMR_DESC,
        f_get_desc_fnc('STVSBGI', SORPCOL.SORPCOL_SBGI_CODE, 30) as SORPCOL_SGBI_DESC,
        f_get_desc_fnc('STVSBGI', SORDEGR.SORDEGR_SBGI_CODE, 30) as SORDEGR_SGBI_DESC

    FROM
        SORPCOL SORPCOL
        LEFT OUTER JOIN SORDEGR SORDEGR ON SORDEGR.SORDEGR_PIDM = SORPCOL.SORPCOL_PIDM
             AND SORDEGR.SORDEGR_SBGI_CODE = SORPCOL.SORPCOL_SBGI_CODE

    WHERE
        SORPCOL.SORPCOL_VERSION = (SELECT MAX(SORPCOL_VERSION)
                                  FROM    SORPCOL PCOL
                                  WHERE   PCOL.SORPCOL_PIDM = SORPCOL.SORPCOL_PIDM)
    ),

SHATRNS as (
    SELECT
        SHRTRCE.SHRTRCE_PIDM,
        SHRTRCE.SHRTRCE_TRIT_SEQ_NO,
        SHRTRCE.SHRTRCE_TRAM_SEQ_NO,
        SHRTRCE.SHRTRCE_SEQ_NO,
        SHRTRCE.SHRTRCE_TRCR_SEQ_NO,
        SHRTRCE.SHRTRCE_TERM_CODE_EFF,
        SHRTRCE.SHRTRCE_LEVL_CODE,
        SHRTRCE.SHRTRCE_SUBJ_CODE,
        SHRTRCE.SHRTRCE_CRSE_NUMB,
        SHRTRCE.SHRTRCE_CRSE_TITLE,
        SHRTRCE.SHRTRCE_CREDIT_HOURS,
        (SELECT to_char(SUM(SHRTRCE_CREDIT_HOURS), '000.00')
        FROM    SHRTRCE TRCE
        WHERE   TRCE.SHRTRCE_PIDM = SHRTRCE.SHRTRCE_PIDM) as SHRTRCE_CREDIT_HR_SUM,
        SHRTRCE.SHRTRCE_GRDE_CODE,
        SHRTRCE.SHRTRCE_GMOD_CODE,
        SHRTRCE.SHRTRCE_COUNT_IN_GPA_IND,
        SHRTRCE.SHRTRCE_ACTIVITY_DATE,
        SHRTRCE.SHRTRCE_SURROGATE_ID,
        SHRTRCE.SHRTRCE_VERSION,
        SHRTRCE.SHRTRCE_USER_ID,
        SHRTRCE.SHRTRCE_DATA_ORIGIN,
        SHRTRCE.SHRTRCE_GUID,
        SHRTRIT.SHRTRIT_PIDM,
        SHRTRIT.SHRTRIT_SEQ_NO,
        SHRTRIT.SHRTRIT_SBGI_CODE,
        SHRTRIT.SHRTRIT_SBGI_DESC,
        SHRTRIT.SHRTRIT_OFFICIAL_TRANS_IND,
        SHRTRIT.SHRTRIT_TRANS_DATE_RCVD,
        SHRTRIT.SHRTRIT_ACTIVITY_DATE,
        SHRTRIT.SHRTRIT_SURROGATE_ID,
        SHRTRIT.SHRTRIT_VERSION

    FROM
        SHRTRCE SHRTRCE

        LEFT OUTER JOIN SHRTRIT SHRTRIT ON SHRTRIT.SHRTRIT_PIDM = SHRTRCE.SHRTRCE_PIDM

    WHERE
        SHRTRCE.SHRTRCE_TRIT_SEQ_NO = (SELECT MAX(SHRTRCE_TRIT_SEQ_NO)
                                      FROM    SHRTRCE TRCE
                                      WHERE   TRCE.SHRTRCE_PIDM = SHRTRCE.SHRTRCE_PIDM
                                      AND     TRCE.SHRTRCE_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
        AND SHRTRCE.SHRTRCE_TRAM_SEQ_NO = (SELECT MAX(SHRTRCE_TRAM_SEQ_NO)
                                          FROM    SHRTRCE TRCE
                                          WHERE   TRCE.SHRTRCE_PIDM = SHRTRCE.SHRTRCE_PIDM
                                          AND     TRCE.SHRTRCE_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
        AND SHRTRCE.SHRTRCE_SEQ_NO = (SELECT MAX(SHRTRCE_SEQ_NO)
                                     FROM    SHRTRCE TRCE
                                     WHERE   TRCE.SHRTRCE_PIDM = SHRTRCE.SHRTRCE_PIDM
                                     AND     TRCE.SHRTRCE_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
        AND SHRTRCE.SHRTRCE_TRCR_SEQ_NO = (SELECT MAX(SHRTRCE_TRCR_SEQ_NO)
                                          FROM    SHRTRCE TRCE
                                          WHERE   TRCE.SHRTRCE_PIDM = SHRTRCE.SHRTRCE_PIDM
                                          AND     TRCE.SHRTRCE_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
    ),

ROAHSCH as
(
    SELECT
        SORHSCH.SORHSCH_PIDM,
        SORHSCH.SORHSCH_SBGI_CODE,
        SORHSCH.SORHSCH_GRADUATION_DATE,
        SORHSCH.SORHSCH_GPA,
        SORHSCH.SORHSCH_TRANS_RECV_DATE,
        F_GET_DESC_FNC('STVSBGI', SORHSCH.SORHSCH_SBGI_CODE, 30) AS SORHSCH_SGBI_DESC,
        SORHSCH.SORHSCH_SURROGATE_ID,
        SORHSCH.SORHSCH_VERSION

    FROM
        SORHSCH SORHSCH
    ),

SGAADVR as
(
  SELECT
      SGRADVR.SGRADVR_PIDM,
      SGRADVR.SGRADVR_TERM_CODE_EFF,
      SGRADVR.SGRADVR_ADVR_PIDM,
      SGRADVR.SGRADVR_ADVR_CODE,
      SGRADVR.SGRADVR_PRIM_IND,
      SGRADVR.SGRADVR_ACTIVITY_DATE,
      SGRADVR.SGRADVR_SURROGATE_ID,
      CASE
        WHEN SGRADVR_ADVR_PIDM IS NULL THEN NULL
          ELSE f_format_name(SGRADVR.SGRADVR_ADVR_PIDM, 'LF30')
            END as SGRADVR_ADVR_NAME,
      CASE
        WHEN SGRADVR.SGRADVR_PIDM IS NULL THEN NULL
          ELSE f_format_name(SGRADVR.SGRADVR_PIDM, 'LF30')
            END as SGRADVR_NAME,
      CASE
        WHEN SGRADVR_ADVR_CODE IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVADVR', SGRADVR_ADVR_CODE, 30)
            END as SGRADVR_ADVR_DESC,
      (SELECT GOREMAL_EMAIL_ADDRESS
      FROM    GOREMAL
      WHERE   GOREMAL_PIDM = SGRADVR.SGRADVR_ADVR_PIDM
      AND     GOREMAL_EMAL_CODE = 'ESF') as SGRADVR_ADVR_EMAIL

  FROM
      SGRADVR SGRADVR

  WHERE
      SGRADVR.SGRADVR_PRIM_IND = 'Y'
      AND SGRADVR.SGRADVR_TERM_CODE_EFF = (SELECT MAX(SGRADVR_TERM_CODE_EFF)
                                          FROM    SGRADVR ADVR
                                          WHERE   ADVR.SGRADVR_PIDM = SGRADVR.SGRADVR_PIDM
                                          AND     ADVR.SGRADVR_PRIM_IND = 'Y'
                                          AND     ADVR.SGRADVR_TERM_CODE_EFF <= :select_term_code.STVTERM_CODE)
      AND SGRADVR.SGRADVR_SURROGATE_ID = (SELECT MAX(SGRADVR_SURROGATE_ID)
                                         FROM    SGRADVR ADVR
                                         WHERE   ADVR.SGRADVR_PIDM = SGRADVR.SGRADVR_PIDM
                                         AND     ADVR.SGRADVR_TERM_CODE_EFF = SGRADVR.SGRADVR_TERM_CODE_EFF
                                         AND     ADVR.SGRADVR_PRIM_IND = 'Y')
  ),

SHATERM as
(
  SELECT
      SHRTTRM.SHRTTRM_PIDM,
      SHRTTRM.SHRTTRM_TERM_CODE,
      SHRTTRM.SHRTTRM_UPDATE_SOURCE_IND,
      SHRTTRM.SHRTTRM_PRE_CATALOG_IND,
      SHRTTRM.SHRTTRM_RECORD_STATUS_IND,
      SHRTTRM.SHRTTRM_RECORD_STATUS_DATE,
      SHRTTRM.SHRTTRM_ASTD_CODE_END_OF_TERM,
      SHRTTRM.SHRTTRM_ASTD_DATE_END_OF_TERM,
      SHRTTRM.SHRTTRM_ACTIVITY_DATE,
      SHRTTRM.SHRTTRM_ASTD_CODE_DL,
      SHRTTRM.SHRTTRM_ASTD_DATE_DL,
      SHRTTRM.SHRTTRM_WRSN_CODE,
      SHRTTRM.SHRTTRM_SURROGATE_ID,
      SHRTTRM.SHRTTRM_VERSION,
      CASE
        WHEN SHRTTRM.SHRTTRM_ASTD_CODE_END_OF_TERM IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVASTD', SHRTTRM.SHRTTRM_ASTD_CODE_END_OF_TERM, 30)
            END as SHRTTRM_ASTD_DESC_END_OF_TERM,
      CASE
        WHEN SHRTTRM.SHRTTRM_ASTD_CODE_DL IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVASTD', SHRTTRM.SHRTTRM_ASTD_CODE_DL, 30)
            END as SHRTTRM_ASTD_DESC_DL,
      CASE
        WHEN SHRTTRM.SHRTTRM_WRSN_CODE IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVWRSN', SHRTTRM.SHRTTRM_WRSN_CODE, 30)
            END as SHRTTRM_WRSN_DESC

  FROM
      SHRTTRM SHRTTRM

  WHERE
      SHRTTRM.SHRTTRM_TERM_CODE = (SELECT MAX(SHRTTRM_TERM_CODE)
                                  FROM    SHRTTRM TTRM
                                  WHERE   TTRM.SHRTTRM_PIDM = SHRTTRM.SHRTTRM_PIDM
                                  AND     TTRM.SHRTTRM_TERM_CODE < :select_term_code.STVTERM_CODE)
  ),

SHAGPAR as
(
  SELECT
      SHRTGPA.SHRTGPA_PIDM,
      SHRTGPA.SHRTGPA_LEVL_CODE,
      SHRTGPA.SHRTGPA_GPA_TYPE_IND,
      SHRTGPA.SHRTGPA_TERM_CODE,
      SHRTGPA.SHRTGPA_HOURS_ATTEMPTED,
      SHRTGPA.SHRTGPA_HOURS_EARNED,
      SHRTGPA.SHRTGPA_GPA_HOURS,
      --SHRTGPA.SHRTGPA_GPA,
      SHRTGPA.SHRTGPA_QUALITY_POINTS,
      SHRTGPA.SHRTGPA_HOURS_PASSED,
      SHRTGPA.SHRTGPA_SURROGATE_ID,
      SHRLGPA.SHRLGPA_PIDM,
      SHRLGPA.SHRLGPA_LEVL_CODE,
      SHRLGPA.SHRLGPA_GPA_TYPE_IND,
      SHRLGPA.SHRLGPA_HOURS_ATTEMPTED,
      SHRLGPA.SHRLGPA_HOURS_EARNED,
      SHRLGPA.SHRLGPA_GPA_HOURS,
      --SHRLGPA.SHRLGPA_GPA,
      SHRLGPA.SHRLGPA_QUALITY_POINTS,
      SHRLGPA.SHRLGPA_SURROGATE_ID,
      trunc(SHRTGPA.SHRTGPA_GPA,3) as SHRTGPA_GPA,
      trunc(SHRLGPA.SHRLGPA_GPA,3) as SHRLGPA_GPA

  FROM
      SHRTGPA SHRTGPA

      LEFT OUTER JOIN SHRLGPA SHRLGPA ON SHRLGPA.SHRLGPA_PIDM = SHRTGPA.SHRTGPA_PIDM
           AND SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'I'
           AND SHRLGPA.SHRLGPA_LEVL_CODE = SHRTGPA.SHRTGPA_LEVL_CODE

  WHERE
      SHRTGPA.SHRTGPA_GPA_TYPE_IND = 'I'
      AND SHRTGPA.SHRTGPA_TERM_CODE = (SELECT MAX(SHRTGPA_TERM_CODE)
                                      FROM    SHRTGPA TGPA
                                      WHERE   TGPA.SHRTGPA_PIDM = SHRTGPA.SHRTGPA_PIDM
                                      AND     TGPA.SHRTGPA_GPA_TYPE_IND  = SHRTGPA.SHRTGPA_GPA_TYPE_IND
                                      AND     TGPA.SHRTGPA_LEVL_CODE = SHRTGPA.SHRTGPA_LEVL_CODE
                                      AND     TGPA.SHRTGPA_TERM_CODE <= :select_term_code.STVTERM_CODE)
  ),

SFAREGS as
(
  SELECT
      SFRSTCR.SFRSTCR_TERM_CODE,
      SFRSTCR.SFRSTCR_PIDM,
      SFRSTCR.SFRSTCR_CRN,
      SFRSTCR.SFRSTCR_CLASS_SORT_KEY,
      SFRSTCR.SFRSTCR_REG_SEQ,
      SFRSTCR.SFRSTCR_PTRM_CODE,
      SFRSTCR.SFRSTCR_RSTS_CODE,
      SFRSTCR.SFRSTCR_BILL_HR,
      SFRSTCR.SFRSTCR_WAIV_HR,
      SFRSTCR.SFRSTCR_CREDIT_HR,
      SFRSTCR.SFRSTCR_BILL_HR_HOLD,
      SFRSTCR.SFRSTCR_CREDIT_HR_HOLD,
      SFRSTCR.SFRSTCR_GMOD_CODE,
      SFRSTCR.SFRSTCR_GRDE_CODE,
      SFRSTCR.SFRSTCR_GRDE_DATE,
      SFRSTCR.SFRSTCR_ADD_DATE,
      SFRSTCR.SFRSTCR_ACTIVITY_DATE,
      SFRSTCR.SFRSTCR_LEVL_CODE,
      SFRSTCR.SFRSTCR_CAMP_CODE,
      SFRSTCA.SFRSTCA_TERM_CODE,
      SFRSTCA.SFRSTCA_PIDM,
      SFRSTCA.SFRSTCA_CRN,
      SFRSTCA.SFRSTCA_SEQ_NUMBER,
      SFRSTCA.SFRSTCA_LEVL_CODE,
      SFRSTCA.SFRSTCA_CAMP_CODE,
      SFRSTCA.SFRSTCA_ADD_DATE,
      SFRSTCA.SFRSTCA_ACTIVITY_DATE,
      SFRSTCA.SFRSTCA_RSTS_CODE,
      SFRSTCA.SFRSTCA_RSTS_DATE,
      SFRSTCA.SFRSTCA_ERROR_FLAG,
      SFRSTCA.SFRSTCA_MESSAGE,
      SFRSTCA.SFRSTCA_BILL_HR,
      SFRSTCA.SFRSTCA_CREDIT_HR,
      SFRSTCA.SFRSTCA_GMOD_CODE,
      SFRSTCA.SFRSTCA_USER,
      SFRSTCA.SFRSTCA_GCMT_CODE,
      SFRSTCA.SFRSTCA_SOURCE_CDE,
      SFRSTCA.SFRSTCA_DATA_ORIGIN,
      SFRSTCA.SFRSTCA_ATTEMPT_HR,
      SFRSTCA.SFRSTCA_RMSG_CDE,
      SFRSTCA.SFRSTCA_STSP_KEY_SEQUENCE,
      SFRSTCA.SFRSTCA_BRDH_SEQ_NUM,
      SFRSTCA.SFRSTCA_BLCK_CODE,
      SFRSTCA.SFRSTCA_STRH_SEQNO,
      SFRSTCA.SFRSTCA_STRD_SEQNO,
      SFRSTCA.SFRSTCA_SURROGATE_ID,
      SFRSTCA.SFRSTCA_VERSION,
      SFRSTCA.SFRSTCA_USER_ID,
      SFRSTCA.SFRSTCA_VPDI_CODE,
      SFRSTCA.SFRSTCA_SESSIONID,
      SFRSTCA.SFRSTCA_CURRENT_TIME,
      SFRSTCA.SFRSTCA_ENRL,
      SFRSTCA.SFRSTCA_SEATS_AVAIL

  FROM
      SFRSTCR SFRSTCR

      LEFT OUTER JOIN SFRSTCA SFRSTCA ON SFRSTCA.SFRSTCA_PIDM = SFRSTCR.SFRSTCR_PIDM
           AND SFRSTCA.SFRSTCA_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
           AND SFRSTCA.SFRSTCA_CRN = SFRSTCR.SFRSTCR_CRN
           AND SFRSTCA.SFRSTCA_SEQ_NUMBER = (SELECT MAX(SFRSTCA_SEQ_NUMBER)
                                            FROM    SFRSTCA STCA
                                            WHERE   STCA.SFRSTCA_PIDM = SFRSTCR.SFRSTCR_PIDM
                                            AND     STCA.SFRSTCA_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
                                            AND     STCA.SFRSTCA_CRN = SFRSTCR.SFRSTCR_CRN)

  WHERE
      SFRSTCR.SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
  ),

SHATCKN as
(
  SELECT
      SFRSTCR_TERM_CODE,
      SFRSTCR_PIDM,
      SFRSTCR_CRN,
      SFRSTCR_CLASS_SORT_KEY,
      SFRSTCR_REG_SEQ,
      SFRSTCR_PTRM_CODE,
      SFRSTCR_RSTS_CODE,
      SFRSTCR_BILL_HR,
      SFRSTCR_WAIV_HR,
      SFRSTCR_CREDIT_HR,
      SFRSTCR_BILL_HR_HOLD,
      SFRSTCR_CREDIT_HR_HOLD,
      SFRSTCR_GMOD_CODE,
      SFRSTCR_GRDE_CODE,
      SFRSTCR_GRDE_DATE,
      SFRSTCR_ADD_DATE,
      SFRSTCR_ACTIVITY_DATE,
      SFRSTCR_LEVL_CODE,
      SFRSTCR_CAMP_CODE,
      SFRSTCA_TERM_CODE,
      SFRSTCA_PIDM,
      SFRSTCA_CRN,
      SFRSTCA_SEQ_NUMBER,
      SFRSTCA_LEVL_CODE,
      SFRSTCA_CAMP_CODE,
      SFRSTCA_ADD_DATE,
      SFRSTCA_ACTIVITY_DATE,
      SFRSTCA_RSTS_CODE,
      SFRSTCA_RSTS_DATE,
      SFRSTCA_ERROR_FLAG,
      SFRSTCA_MESSAGE,
      SFRSTCA_BILL_HR,
      SFRSTCA_CREDIT_HR,
      SFRSTCA_GMOD_CODE,
      SFRSTCA_USER,
      SFRSTCA_GCMT_CODE,
      SFRSTCA_SOURCE_CDE,
      SFRSTCA_DATA_ORIGIN,
      SFRSTCA_ATTEMPT_HR,
      SFRSTCA_RMSG_CDE,
      SFRSTCA_STSP_KEY_SEQUENCE,
      SFRSTCA_BRDH_SEQ_NUM,
      SFRSTCA_BLCK_CODE,
      SFRSTCA_STRH_SEQNO,
      SFRSTCA_STRD_SEQNO,
      SFRSTCA_SURROGATE_ID,
      SFRSTCA_VERSION,
      SFRSTCA_USER_ID,
      SFRSTCA_VPDI_CODE,
      SFRSTCA_SESSIONID,
      SFRSTCA_CURRENT_TIME,
      SFRSTCA_ENRL,
      SFRSTCA_SEATS_AVAIL,
      SHRTCKN.SHRTCKN_PIDM,
      SHRTCKN.SHRTCKN_TERM_CODE,
      SHRTCKN.SHRTCKN_SEQ_NO,
      SHRTCKN.SHRTCKN_CRN,
      SHRTCKN.SHRTCKN_SUBJ_CODE,
      SHRTCKN.SHRTCKN_CRSE_NUMB,
      SHRTCKN.SHRTCKN_COLL_CODE,
      SHRTCKN.SHRTCKN_CAMP_CODE,
      SHRTCKN.SHRTCKN_ACTIVITY_DATE,
      SHRTCKN.SHRTCKN_SEQ_NUMB,
      SHRTCKN.SHRTCKN_SURROGATE_ID,
      SHRTCKN.SHRTCKN_VERSION,
      SHRTCKL.SHRTCKL_PIDM,
      SHRTCKL.SHRTCKL_TERM_CODE,
      SHRTCKL.SHRTCKL_TCKN_SEQ_NO,
      SHRTCKL.SHRTCKL_LEVL_CODE,
      SHRTCKL.SHRTCKL_ACTIVITY_DATE,
      SHRTCKL.SHRTCKL_PRIMARY_LEVL_IND,
      SHRTCKL.SHRTCKL_SURROGATE_ID,
      SHRTCKL.SHRTCKL_VERSION,
      SHRTCKG.SHRTCKG_PIDM,
      SHRTCKG.SHRTCKG_TERM_CODE,
      SHRTCKG.SHRTCKG_TCKN_SEQ_NO,
      SHRTCKG.SHRTCKG_SEQ_NO,
      SHRTCKG.SHRTCKG_FINAL_GRDE_SEQ_NO,
      SHRTCKG.SHRTCKG_GRDE_CODE_FINAL,
      SHRTCKG.SHRTCKG_GMOD_CODE,
      SHRTCKG.SHRTCKG_CREDIT_HOURS,
      SHRTCKG.SHRTCKG_GCHG_CODE,
      SHRTCKG.SHRTCKG_FINAL_GRDE_CHG_DATE,
      SHRTCKG.SHRTCKG_HOURS_ATTEMPTED,
      SHRTCKG.SHRTCKG_GRDE_CODE_INCMP_FINAL,
      SHRTCKG.SHRTCKG_SURROGATE_ID,
      SHRTCKG.SHRTCKG_VERSION,
      SHRGRDE.SHRGRDE_CODE,
      SHRGRDE.SHRGRDE_LEVL_CODE,
      SHRGRDE.SHRGRDE_QUALITY_POINTS,
      SHRGRDE.SHRGRDE_ATTEMPTED_IND,
      SHRGRDE.SHRGRDE_COMPLETED_IND,
      SHRGRDE.SHRGRDE_PASSED_IND,
      SHRGRDE.SHRGRDE_GPA_IND,
      SHRGRDE.SHRGRDE_SURROGATE_ID,
      SHRGRDE.SHRGRDE_VERSION,
      SHRGRDE.SHRGRDE_NUMERIC_VALUE,
      CASE
        WHEN SHRTCKG.SHRTCKG_GCHG_CODE IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVGCHG', SHRTCKG.SHRTCKG_GCHG_CODE, 30)
            END as SHRTCKG_GCHG_DESC,
      decode(SHRGRDE.SHRGRDE_COMPLETED_IND,'Y',1,0) as COURSE_COMPLETE_IND,
      decode(SHRGRDE.SHRGRDE_PASSED_IND,'Y',1,0) as COURSE_PASSED_IND,
      decode(SHRGRDE.SHRGRDE_GPA_IND,'Y',1,0) as COURSE_GPA_IND,
      f_format_name(SFRSTCR_PIDM, 'LF30') as SFRSTCR_STUDENT_NAME

  FROM
      SFAREGS SFRSTCR

      LEFT OUTER JOIN SHRTCKN SHRTCKN ON SHRTCKN.SHRTCKN_PIDM = SFRSTCR_PIDM
           AND SHRTCKN.SHRTCKN_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKN.SHRTCKN_CRN = SFRSTCR_CRN

      LEFT OUTER JOIN SHRTCKG SHRTCKG ON SHRTCKG.SHRTCKG_PIDM = SFRSTCR_PIDM
           AND SHRTCKG.SHRTCKG_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKG.SHRTCKG_TCKN_SEQ_NO = SFRSTCR_REG_SEQ
           AND SHRTCKG.SHRTCKG_SEQ_NO = (SELECT MAX(SHRTCKG_SEQ_NO)
                                        FROM    SHRTCKG TCKG
                                        WHERE   TCKG.SHRTCKG_PIDM = SHRTCKG.SHRTCKG_PIDM
                                        AND     TCKG.SHRTCKG_TERM_CODE = SHRTCKG.SHRTCKG_TERM_CODE
                                        AND     TCKG.SHRTCKG_TCKN_SEQ_NO = SHRTCKG.SHRTCKG_TCKN_SEQ_NO)

      LEFT OUTER JOIN SHRTCKL SHRTCKL ON SHRTCKL.SHRTCKL_PIDM = SFRSTCR_PIDM
           AND SHRTCKL.SHRTCKL_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKL.SHRTCKL_SURROGATE_ID = (SELECT MAX(SHRTCKL_SURROGATE_ID)
                                              FROM    SHRTCKL TCKL
                                              WHERE   TCKL.SHRTCKL_PIDM = SHRTCKL.SHRTCKL_PIDM
                                              AND     TCKL.SHRTCKL_TERM_CODE = SHRTCKL.SHRTCKL_TERM_CODE)

      LEFT OUTER JOIN SHRGRDE SHRGRDE ON SHRGRDE.SHRGRDE_CODE = SFRSTCR.SFRSTCR_GRDE_CODE
           AND SHRGRDE.SHRGRDE_LEVL_CODE = SHRTCKL.SHRTCKL_LEVL_CODE
           AND SHRGRDE.SHRGRDE_TERM_CODE_EFFECTIVE = (SELECT MAX(SHRGRDE_TERM_CODE_EFFECTIVE)
                                                     FROM    SHRGRDE GRDE
                                                     WHERE   GRDE.SHRGRDE_CODE = SHRGRDE.SHRGRDE_CODE
                                                     AND     GRDE.SHRGRDE_LEVL_CODE = SHRTCKL.SHRTCKL_LEVL_CODE
                                                     AND     GRDE.SHRGRDE_TERM_CODE_EFFECTIVE <= SFRSTCR_TERM_CODE)
  ),

SSASECT as
(
    SELECT
      SSBSECT.SSBSECT_TERM_CODE,
      SSBSECT.SSBSECT_CRN,
      SSBSECT.SSBSECT_PTRM_CODE,
      SSBSECT.SSBSECT_SUBJ_CODE,
      SSBSECT.SSBSECT_CRSE_NUMB,
      SSBSECT.SSBSECT_SEQ_NUMB,
      SSBSECT.SSBSECT_SSTS_CODE,
      SSBSECT.SSBSECT_SCHD_CODE,
      SSBSECT.SSBSECT_CAMP_CODE,
      SSBSECT.SSBSECT_CREDIT_HRS,
      SSBSECT.SSBSECT_BILL_HRS,
      SSBSECT.SSBSECT_GMOD_CODE,
      SSBSECT.SSBSECT_REG_ONEUP,
      SSBSECT.SSBSECT_PRIOR_ENRL,
      SSBSECT.SSBSECT_PROJ_ENRL,
      SSBSECT.SSBSECT_MAX_ENRL,
      SSBSECT.SSBSECT_ENRL,
      SSBSECT.SSBSECT_SEATS_AVAIL,
      SSBSECT.SSBSECT_TOT_CREDIT_HRS,
      SSBSECT.SSBSECT_CENSUS_ENRL,
      SSBSECT.SSBSECT_CENSUS_ENRL_DATE,
      SSBSECT.SSBSECT_ACTIVITY_DATE,
      SSBSECT.SSBSECT_PTRM_START_DATE,
      SSBSECT.SSBSECT_PTRM_END_DATE,
      SSBSECT.SSBSECT_PTRM_WEEKS,
      SSBSECT.SSBSECT_WAIT_CAPACITY,
      SSBSECT.SSBSECT_WAIT_COUNT,
      SSBSECT.SSBSECT_WAIT_AVAIL,
      SSBSECT.SSBSECT_INSM_CODE,
      SSBSECT.SSBSECT_SURROGATE_ID,
      SSBSECT.SSBSECT_VERSION,
      SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID,
      SCBCRSE.SCBCRSE_SUBJ_CODE,
      SCBCRSE.SCBCRSE_CRSE_NUMB,
      SCBCRSE.SCBCRSE_EFF_TERM,
      SCBCRSE.SCBCRSE_COLL_CODE,
      SCBCRSE.SCBCRSE_DIVS_CODE,
      SCBCRSE.SCBCRSE_DEPT_CODE,
      SCBCRSE.SCBCRSE_CSTA_CODE,
      SCBCRSE.SCBCRSE_TITLE,
      SCBCRSE.SCBCRSE_CIPC_CODE,
      SCBCRSE.SCBCRSE_CREDIT_HR_IND,
      SCBCRSE.SCBCRSE_CREDIT_HR_LOW,
      SCBCRSE.SCBCRSE_CREDIT_HR_HIGH,
      SCBCRSE.SCBCRSE_LEC_HR_IND,
      SCBCRSE.SCBCRSE_LEC_HR_LOW,
      SCBCRSE.SCBCRSE_LEC_HR_HIGH,
      SCBCRSE.SCBCRSE_BILL_HR_IND,
      SCBCRSE.SCBCRSE_BILL_HR_LOW,
      SCBCRSE.SCBCRSE_BILL_HR_HIGH,
      SCBCRSE.SCBCRSE_ACTIVITY_DATE,
      SCBCRSE.SCBCRSE_CONT_HR_LOW,
      SCBCRSE.SCBCRSE_CONT_HR_IND,
      SCBCRSE.SCBCRSE_CONT_HR_HIGH,
      SCBCRSE.SCBCRSE_REPS_CODE,
      SCBCRSE.SCBCRSE_MAX_RPT_UNITS,
      SCBCRSE.SCBCRSE_SURROGATE_ID,
      SCBCRSE.SCBCRSE_VERSION,
      SCBCRSE.SCBCRSE_VPDI_CODE,
      SCBCRSE.SCBCRSE_SICAS_SUNY_ID,
      SSRMEET.SSRMEET_TERM_CODE,
      SSRMEET.SSRMEET_CRN,
      SSRMEET.SSRMEET_DAYS_CODE,
      SSRMEET.SSRMEET_DAY_NUMBER,
      SSRMEET.SSRMEET_BEGIN_TIME,
      SSRMEET.SSRMEET_END_TIME,
      SSRMEET.SSRMEET_BLDG_CODE,
      SSRMEET.SSRMEET_ROOM_CODE,
      SSRMEET.SSRMEET_ACTIVITY_DATE,
      SSRMEET.SSRMEET_START_DATE,
      SSRMEET.SSRMEET_END_DATE,
      SSRMEET.SSRMEET_SUN_DAY,
      SSRMEET.SSRMEET_MON_DAY,
      SSRMEET.SSRMEET_TUE_DAY,
      SSRMEET.SSRMEET_WED_DAY,
      SSRMEET.SSRMEET_THU_DAY,
      SSRMEET.SSRMEET_FRI_DAY,
      SSRMEET.SSRMEET_SAT_DAY,
      SSRMEET.SSRMEET_SCHD_CODE,
      SSRMEET.SSRMEET_CREDIT_HR_SESS,
      SSRMEET.SSRMEET_MEET_NO,
      SSRMEET.SSRMEET_HRS_WEEK,
      SSRMEET.SSRMEET_MTYP_CODE,
      SSRMEET.SSRMEET_SURROGATE_ID,
      SSRMEET.SSRMEET_VERSION,
      F_GET_DESC_FNC('STVSSTS', SSBSECT.SSBSECT_SSTS_CODE, 30) as SSBSECT_SSTS_DESC,
      F_GET_DESC_FNC('STVSCHD', SSBSECT.SSBSECT_SCHD_CODE, 30) as SSBSECT_SCHD_DESC,
      F_GET_DESC_FNC('STVCSTA', SCBCRSE.SCBCRSE_CSTA_CODE, 30) as SCBCRSE_CSTA_DESC,
      F_GET_DESC_FNC('STVREPS', SCBCRSE.SCBCRSE_REPS_CODE, 30) as SCBCRSE_REPS_DESC

  FROM
      SSBSECT SSBSECT

      LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT.SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
           AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB

      LEFT OUTER JOIN SSRMEET SSRMEET ON SSRMEET.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
           AND SSRMEET.SSRMEET_CRN = SSBSECT.SSBSECT_CRN
           AND SSRMEET_SURROGATE_ID = (SELECT MAX(SSRMEET_SURROGATE_ID)
                                      FROM    SSRMEET MEET
                                      WHERE   MEET.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
                                      AND     MEET.SSRMEET_CRN = SSBSECT.SSBSECT_CRN)

  WHERE
      SSBSECT.SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE
      AND SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE_EFF_TERM)
                                    FROM     SCBCRSE CRSE
                                    WHERE    CRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                    AND      CRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                    AND      CRSE.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE)
  ORDER BY
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID
  ),

SIRASGQ as
(
 SELECT
      SIRASGN.SIRASGN_TERM_CODE,
      SIRASGN.SIRASGN_CRN,
      SIRASGN.SIRASGN_PIDM,
      SIRASGN.SIRASGN_CATEGORY,
      SIRASGN.SIRASGN_SURROGATE_ID,
      SIRASGN.SIRASGN_VERSION,
      SIRDPCL.SIRDPCL_PIDM,
      SIRDPCL.SIRDPCL_TERM_CODE_EFF,
      SIRDPCL.SIRDPCL_COLL_CODE,
      SIRDPCL.SIRDPCL_DEPT_CODE,
      SIRASGN.SIRASGN_PRIMARY_IND,
      f_format_name(SIRDPCL.SIRDPCL_PIDM, 'LF30') as SIRDPCL_INSTR_NAME,
      CASE
        WHEN SIRDPCL_DEPT_CODE IS NULL THEN 'DEPT UNAVAILABLE'
          ELSE F_GET_DESC_FNC('STVDEPT', SIRDPCL.SIRDPCL_DEPT_CODE, 30)
            END as SIRDPCL_DEPT_DESC,
      (SELECT GOREMAL_EMAIL_ADDRESS
      FROM    GOREMAL
      WHERE   GOREMAL_PIDM = SIRDPCL_PIDM
      AND     GOREMAL_EMAL_CODE = 'ESF'
      AND     GOREMAL_STATUS_IND = 'A'
      AND     GOREMAL_PREFERRED_IND = 'Y'
      AND     SIRASGN_PRIMARY_IND = 'Y') as SIRDPCL_INSTR_EMAIL

  FROM
      SIRASGN SIRASGN
      LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM

  WHERE
      SIRASGN_PRIMARY_IND = 'Y'
      AND SIRASGN.SIRASGN_TERM_CODE = (SELECT MAX(SIRASGN_TERM_CODE)
                                      FROM    SIRASGN ASGN
                                      WHERE   ASGN.SIRASGN_PIDM = SIRASGN.SIRASGN_PIDM
                                      AND     ASGN.SIRASGN_TERM_CODE <= :select_term_code.STVTERM_CODE)
  ),

PERSONS_LIST_DEMO as
(
  SELECT
      CASE
        WHEN SPBPERS_SEX IS NULL THEN 0
          ELSE 1
            END as SEX_Measure,
      CASE
        WHEN GORRACE_RACE_CDE IS NULL THEN 0
          ELSE 1
            END as RACE_Measure,
      CASE
        WHEN SPBPERS_ETHN_CDE IS NULL THEN 0
          ELSE 1
            END as ETHN_Measure,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE

  WHERE
      SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
  ),

PERSONS_ADRTELE as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SPRADDR_PIDM,
      SPRADDR_ATYP_CODE,
      SPRADDR_ATYP_DESC,
      SPRADDR_FROM_DATE,
      SPRADDR_TO_DATE,
      SPRADDR_STREET_LINE1,
      SPRADDR_STREET_LINE2,
      SPRADDR_STREET_LINE3,
      SPRADDR_CITY,
      SPRADDR_STAT_CODE,
      SPRADDR_ZIP,
      SPRTELE_PIDM,
      SPRTELE_TELE_CODE,
      SPRTELE_TELE_DESC,
      SPRTELE_PHONE_AREA,
      SPRTELE_PHONE_NUMBER,
      SPREMRG_PIDM,
      SPREMRG_LAST_NAME,
      SPREMRG_FIRST_NAME,
      SPREMRG_MI,
      SPREMRG_RELT_CODE,
      SPREMRG_RELT_DESC,
      SPREMRG_PRIORITY,
      SPREMRG_STREET_LINE1,
      SPREMRG_STREET_LINE2,
      SPREMRG_STREET_LINE3,
      SPREMRG_CITY,
      SPREMRG_STAT_CODE,
      SPREMRG_NATN_CODE,
      SPREMRG_ZIP,
      SPREMRG_PHONE_AREA,
      SPREMRG_PHONE_NUMBER,
      SPREMRG_PHONE_EXT,
      SPREMRG_ACTIVITY_DATE,
      SPREMRG_ATYP_CODE,
      SPREMRG_HOUSE_NUMBER

  FROM
      PERSONS_LIST_DEMO A

      LEFT OUTER JOIN TUIADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPATELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPAEMRG SPREMRG ON SPREMRG.SPREMRG_PIDM = SPRIDEN_PIDM


  WHERE
      (SPREMRG_PRIORITY <= 1 OR SPREMRG_PRIORITY IS NULL)
  ),

STUDENT_LIST_DEMO as
(
  SELECT
      CASE
        WHEN SPBPERS_SEX IS NULL THEN 0
          ELSE 1
            END as SEX_Measure,
      CASE
        WHEN GORRACE_RACE_CDE IS NULL THEN 0
          ELSE 1
            END as RACE_Measure,
      CASE
        WHEN SPBPERS_ETHN_CDE IS NULL THEN 0
          ELSE 1
            END as ETHN_Measure,
      CASE
        WHEN SGBSTDN_MAJR_CODE_1 IS NULL THEN 0
          ELSE 1
            END as POS_Measure,
      CASE
        WHEN SGBSTDN_DEGC_CODE_1 IS NULL THEN 0
          ELSE 1
            END as DEGC_Measure,
      CASE
        WHEN SGBSTDN_STYP_CODE IS NULL THEN 0
          ELSE 1
            END as STYP_Measure,
      CASE
        WHEN SGBSTDN_LEVL_CODE IS NULL THEN 0
          ELSE 1
            END as LEVL_Measure,
      CASE
        WHEN SGBSTDN_CLAS_CODE IS NULL THEN 0
          ELSE 1
            END as CLAS_Measure,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SFRTHST_TMST_CODE,
      SFRTHST_TMST_DESC,
      SGBSTDN_TERM_CODE_EFF,
      SGBSTDN_STST_CODE,
      SGBSTDN_STYP_CODE,
      SGBSTDN_LEVL_CODE,
      SGBSTDN_CLAS_CODE,
      SGBSTDN_DEPT_CODE,
      SGBSTDN_MAJR_CODE_1,
      SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN_DEGC_CODE_1,
      SGBSTDN_RESD_CODE,
      SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN_TERM_EFF_DESC,
      SGBSTDN_STYP_DESC,
      SGBSTDN_LEVL_DESC,
      SGBSTDN_CLAS_DESC,
      SGBSTDN_DEPT_DESC,
      SGBSTDN_MAJR_DESC,
      SGBSTDN_MINR_1_DESC,
      SGBSTDN_MINR_1_2_DESC,
      SGBSTDN_CONC_DESC,
      SGBSTDN_DEGC_DESC,
      SGBSTDN_RESD_DESC,
      STVCLAS_SURROGATE_ID

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE

  WHERE
      SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
  ),

STUDENT_ADRTELE as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SPRADDR_PIDM,
      SPRADDR_ATYP_CODE,
      SPRADDR_ATYP_DESC,
      SPRADDR_FROM_DATE,
      SPRADDR_TO_DATE,
      SPRADDR_STREET_LINE1,
      SPRADDR_STREET_LINE2,
      SPRADDR_STREET_LINE3,
      SPRADDR_CITY,
      SPRADDR_STAT_CODE,
      SPRADDR_ZIP,
      SPRTELE_PIDM,
      SPRTELE_TELE_CODE,
      SPRTELE_TELE_DESC,
      SPRTELE_PHONE_AREA,
      SPRTELE_PHONE_NUMBER,
      SPREMRG_PIDM,
      SPREMRG_LAST_NAME,
      SPREMRG_FIRST_NAME,
      SPREMRG_MI,
      SPREMRG_RELT_CODE,
      SPREMRG_RELT_DESC,
      SPREMRG_PRIORITY,
      SPREMRG_STREET_LINE1,
      SPREMRG_STREET_LINE2,
      SPREMRG_STREET_LINE3,
      SPREMRG_CITY,
      SPREMRG_STAT_CODE,
      SPREMRG_NATN_CODE,
      SPREMRG_ZIP,
      SPREMRG_PHONE_AREA,
      SPREMRG_PHONE_NUMBER,
      SPREMRG_PHONE_EXT,
      SPREMRG_ACTIVITY_DATE,
      SPREMRG_ATYP_CODE,
      SPREMRG_HOUSE_NUMBER

  FROM
      STUDENT_LIST_DEMO A

      LEFT OUTER JOIN TUIADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPATELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPAEMRG SPREMRG ON SPREMRG.SPREMRG_PIDM = SPRIDEN_PIDM

  WHERE
      (SPREMRG_PRIORITY <= 1 OR SPREMRG_PRIORITY IS NULL)
  ),

STUDENT_ADMIN_LIST as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPBPERS_SEX,
      GORADID_ADDITIONAL_ID,
      GORRACE_DESC,
      SPBPERS_ETHN_DESC,
      SGBSTDN_STST_CODE,
      SGBSTDN_CLAS_CODE,
      SGBSTDN_DEGC_CODE_1,
      SGBSTDN_MAJR_DESC,
      SGBSTDN_LEVL_CODE,
      SGBSTDN_STYP_CODE,
      SGBSTDN_STYP_DESC,
      SGBSTDN_DEPT_DESC,
      SGBSTDN_EXP_GRAD_DATE,
      SFRTHST_TMST_CODE,
      SFRTHST_TMST_DESC,
      SGBSTDN_TERM_CODE_EFF,
      SGBSTDN_TERM_EFF_DESC,
      SGBSTDN_RESD_CODE,
      SGBSTDN_RESD_DESC,
      SPBPERS_CITZ_COUNTRY,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      STVCLAS_SURROGATE_ID

  FROM
      STUDENT_LIST_DEMO A
  ),

STUDENT_GRADE_LIST as
(
  SELECT
      A.SPRIDEN_PIDM,
      A.SPRIDEN_ID,
      A.SPRIDEN_LAST_NAME,
      A.SPRIDEN_FIRST_NAME,
      A.SPRIDEN_MI,
      A.SPRIDEN_LEGAL_NAME,
      A.SPRIDEN_SEARCH_LAST_NAME,
      A.SPRIDEN_SEARCH_FIRST_NAME,
      A.SPRIDEN_SEARCH_MI,
      A.SPBPERS_PREF_FIRST_NAME,
      A.SPBPERS_AGE,
      A.SPBPERS_SEX,
      A.GORRACE_RACE_CDE,
      A.GORRACE_DESC,
      A.SPBPERS_ETHN_CDE,
      A.SPBPERS_ETHN_DESC,
      A.SPBPERS_SICAS_HISP_ORIGIN,
      A.SPBPERS_CITZ_CODE,
      A.SPBPERS_CITZ_COUNTRY,
      A.GOBINTL_NATN_CODE_BIRTH,
      A.GOBINTL_BIRTH_NATN,
      A.GOBTPAC_EXTERNAL_USER,
      A.GORADID_ADDITIONAL_ID,
      A.GOREMAL_EMAIL_ADDRESS,
      A.GOREMAL_EMAL_CODE,
      A.SFRTHST_TMST_CODE,
      A.SFRTHST_TMST_DESC,
      A.SGBSTDN_TERM_CODE_EFF,
      A.SGBSTDN_STST_CODE,
      A.SGBSTDN_STYP_CODE,
      A.SGBSTDN_LEVL_CODE,
      A.SGBSTDN_CLAS_CODE,
      A.SGBSTDN_DEPT_CODE,
      A.SGBSTDN_MAJR_CODE_1,
      A.SGBSTDN_MAJR_CODE_MINR_1,
      A.SGBSTDN_MAJR_CODE_MINR_1_2,
      A.SGBSTDN_MAJR_CODE_CONC_1,
      A.SGBSTDN_DEGC_CODE_1,
      A.SGBSTDN_RESD_CODE,
      A.SGBSTDN_EXP_GRAD_DATE,
      A.SGBSTDN_STYP_DESC,
      A.SGBSTDN_LEVL_DESC,
      A.SGBSTDN_CLAS_DESC,
      A.SGBSTDN_DEPT_DESC,
      A.SGBSTDN_MAJR_DESC,
      A.SGBSTDN_MINR_1_DESC,
      A.SGBSTDN_MINR_1_2_DESC,
      A.SGBSTDN_CONC_DESC,
      A.SGBSTDN_DEGC_DESC,
      A.SGBSTDN_RESD_DESC,
      A.STVCLAS_SURROGATE_ID,
      S1.SFRSTCR_TERM_CODE,
      S1.SFRSTCR_PIDM,
      S1.SFRSTCR_CRN,
      S1.SFRSTCR_CLASS_SORT_KEY,
      S1.SFRSTCR_REG_SEQ,
      S1.SFRSTCR_PTRM_CODE,
      S1.SFRSTCR_RSTS_CODE,
      S1.SFRSTCR_BILL_HR,
      S1.SFRSTCR_WAIV_HR,
      S1.SFRSTCR_CREDIT_HR,
      S1.SFRSTCR_BILL_HR_HOLD,
      S1.SFRSTCR_CREDIT_HR_HOLD,
      S1.SFRSTCR_GMOD_CODE,
      S1.SFRSTCR_GRDE_CODE,
      S1.SFRSTCR_GRDE_DATE,
      S1.SFRSTCR_ADD_DATE,
      S1.SFRSTCR_ACTIVITY_DATE,
      S1.SFRSTCR_LEVL_CODE,
      S1.SFRSTCR_CAMP_CODE,
      S1.SFRSTCA_TERM_CODE,
      S1.SFRSTCA_PIDM,
      S1.SFRSTCA_CRN,
      S1.SFRSTCA_SEQ_NUMBER,
      S1.SFRSTCA_LEVL_CODE,
      S1.SFRSTCA_CAMP_CODE,
      S1.SFRSTCA_ADD_DATE,
      S1.SFRSTCA_ACTIVITY_DATE,
      S1.SFRSTCA_RSTS_CODE,
      S1.SFRSTCA_RSTS_DATE,
      S1.SFRSTCA_ERROR_FLAG,
      S1.SFRSTCA_MESSAGE,
      S1.SFRSTCA_BILL_HR,
      S1.SFRSTCA_CREDIT_HR,
      S1.SFRSTCA_GMOD_CODE,
      S1.SFRSTCA_USER,
      S1.SFRSTCA_GCMT_CODE,
      S1.SFRSTCA_SOURCE_CDE,
      S1.SFRSTCA_DATA_ORIGIN,
      S1.SFRSTCA_ATTEMPT_HR,
      S1.SFRSTCA_RMSG_CDE,
      S1.SFRSTCA_STSP_KEY_SEQUENCE,
      S1.SFRSTCA_BRDH_SEQ_NUM,
      S1.SFRSTCA_BLCK_CODE,
      S1.SFRSTCA_STRH_SEQNO,
      S1.SFRSTCA_STRD_SEQNO,
      S1.SFRSTCA_SURROGATE_ID,
      S1.SFRSTCA_VERSION,
      S1.SFRSTCA_USER_ID,
      S1.SFRSTCA_VPDI_CODE,
      S1.SFRSTCA_SESSIONID,
      S1.SFRSTCA_CURRENT_TIME,
      S1.SFRSTCA_ENRL,
      S1.SFRSTCA_SEATS_AVAIL,
      S1.SHRTCKN_PIDM,
      S1.SHRTCKN_TERM_CODE,
      S1.SHRTCKN_SEQ_NO,
      S1.SHRTCKN_CRN,
      S1.SHRTCKN_SUBJ_CODE,
      S1.SHRTCKN_CRSE_NUMB,
      S1.SHRTCKN_COLL_CODE,
      S1.SHRTCKN_CAMP_CODE,
      S1.SHRTCKN_ACTIVITY_DATE,
      S1.SHRTCKN_SEQ_NUMB,
      S1.SHRTCKN_SURROGATE_ID,
      S1.SHRTCKG_PIDM,
      S1.SHRTCKG_TERM_CODE,
      S1.SHRTCKG_TCKN_SEQ_NO,
      S1.SHRTCKG_SEQ_NO,
      S1.SHRTCKG_FINAL_GRDE_SEQ_NO,
      S1.SHRTCKG_GRDE_CODE_FINAL,
      S1.SHRTCKG_GMOD_CODE,
      S1.SHRTCKG_CREDIT_HOURS,
      S1.SHRTCKG_GCHG_CODE,
      S1.SHRTCKG_FINAL_GRDE_CHG_DATE,
      S1.SHRTCKG_HOURS_ATTEMPTED,
      S1.SHRTCKG_GRDE_CODE_INCMP_FINAL,
      S1.SHRTCKG_SURROGATE_ID,
      S1.SHRTCKG_VERSION,
      S1.SHRTCKG_GCHG_DESC,
      S1.SHRTCKL_PRIMARY_LEVL_IND,
      S1.SHRGRDE_CODE,
      S1.SHRGRDE_LEVL_CODE,
      S1.SHRGRDE_QUALITY_POINTS,
      S1.SHRGRDE_ATTEMPTED_IND,
      S1.SHRGRDE_COMPLETED_IND,
      S1.SHRGRDE_PASSED_IND,
      S1.SHRGRDE_GPA_IND,
      S2.SSBSECT_TERM_CODE,
      S2.SSBSECT_CRN,
      S2.SSBSECT_PTRM_CODE,
      S2.SSBSECT_SUBJ_CODE,
      S2.SSBSECT_CRSE_NUMB,
      S2.SSBSECT_SEQ_NUMB,
      S2.SSBSECT_SSTS_CODE,
      S2.SSBSECT_SCHD_CODE,
      S2.SSBSECT_CAMP_CODE,
      S2.SSBSECT_CREDIT_HRS,
      S2.SSBSECT_BILL_HRS,
      S2.SSBSECT_GMOD_CODE,
      S2.SSBSECT_REG_ONEUP,
      S2.SSBSECT_PRIOR_ENRL,
      S2.SSBSECT_PROJ_ENRL,
      S2.SSBSECT_MAX_ENRL,
      S2.SSBSECT_ENRL,
      S2.SSBSECT_SEATS_AVAIL,
      S2.SSBSECT_TOT_CREDIT_HRS,
      S2.SSBSECT_CENSUS_ENRL,
      S2.SSBSECT_CENSUS_ENRL_DATE,
      S2.SSBSECT_ACTIVITY_DATE,
      S2.SSBSECT_PTRM_START_DATE,
      S2.SSBSECT_PTRM_END_DATE,
      S2.SSBSECT_PTRM_WEEKS,
      S2.SSBSECT_WAIT_CAPACITY,
      S2.SSBSECT_WAIT_COUNT,
      S2.SSBSECT_WAIT_AVAIL,
      S2.SSBSECT_INSM_CODE,
      S2.SSBSECT_SURROGATE_ID,
      S2.SSBSECT_VERSION,
      S2.SSBSECT_SICAS_CAMP_COURSE_ID,
      S2.SSBSECT_SICAS_CAMP_SECTION_ID,
      S2.SCBCRSE_SUBJ_CODE,
      S2.SCBCRSE_CRSE_NUMB,
      S2.SCBCRSE_EFF_TERM,
      S2.SCBCRSE_COLL_CODE,
      S2.SCBCRSE_DIVS_CODE,
      S2.SCBCRSE_DEPT_CODE,
      S2.SCBCRSE_CSTA_CODE,
      S2.SCBCRSE_TITLE,
      S2.SCBCRSE_CIPC_CODE,
      S2.SCBCRSE_CREDIT_HR_IND,
      S2.SCBCRSE_CREDIT_HR_LOW,
      S2.SCBCRSE_CREDIT_HR_HIGH,
      S2.SCBCRSE_LEC_HR_IND,
      S2.SCBCRSE_LEC_HR_LOW,
      S2.SCBCRSE_LEC_HR_HIGH,
      S2.SCBCRSE_BILL_HR_IND,
      S2.SCBCRSE_BILL_HR_LOW,
      S2.SCBCRSE_BILL_HR_HIGH,
      S2.SCBCRSE_ACTIVITY_DATE,
      S2.SCBCRSE_CONT_HR_LOW,
      S2.SCBCRSE_CONT_HR_IND,
      S2.SCBCRSE_CONT_HR_HIGH,
      S2.SCBCRSE_REPS_CODE,
      S2.SCBCRSE_MAX_RPT_UNITS,
      S2.SCBCRSE_SURROGATE_ID,
      S2.SCBCRSE_VERSION,
      S2.SCBCRSE_VPDI_CODE,
      S2.SCBCRSE_SICAS_SUNY_ID,
      S2.SSRMEET_TERM_CODE,
      S2.SSRMEET_CRN,
      S2.SSRMEET_DAYS_CODE,
      S2.SSRMEET_DAY_NUMBER,
      S2.SSRMEET_BEGIN_TIME,
      S2.SSRMEET_END_TIME,
      S2.SSRMEET_BLDG_CODE,
      S2.SSRMEET_ROOM_CODE,
      S2.SSRMEET_ACTIVITY_DATE,
      S2.SSRMEET_START_DATE,
      S2.SSRMEET_END_DATE,
      S2.SSRMEET_SUN_DAY,
      S2.SSRMEET_MON_DAY,
      S2.SSRMEET_TUE_DAY,
      S2.SSRMEET_WED_DAY,
      S2.SSRMEET_THU_DAY,
      S2.SSRMEET_FRI_DAY,
      S2.SSRMEET_SAT_DAY,
      S2.SSRMEET_SCHD_CODE,
      S2.SSRMEET_CREDIT_HR_SESS,
      S2.SSRMEET_MEET_NO,
      S2.SSRMEET_HRS_WEEK,
      S2.SSRMEET_MTYP_CODE,
      S2.SSRMEET_SURROGATE_ID,
      S2.SSRMEET_VERSION,
      S2.SSBSECT_SSTS_DESC,
      S2.SSBSECT_SCHD_DESC,
      S2.SCBCRSE_CSTA_DESC,
      S2.SCBCRSE_REPS_DESC,
      S3.SIRASGN_TERM_CODE,
      S3.SIRASGN_CRN,
      S3.SIRASGN_PIDM,
      S3.SIRDPCL_PIDM,
      S3.SIRDPCL_TERM_CODE_EFF,
      S3.SIRDPCL_COLL_CODE,
      S3.SIRDPCL_DEPT_CODE,
      S3.SIRASGN_PRIMARY_IND,
      S3.SIRDPCL_INSTR_EMAIL,
      S3.SIRDPCL_DEPT_DESC,
      S3.SIRDPCL_INSTR_NAME

  FROM
      STUDENT_LIST_DEMO A

      LEFT OUTER JOIN SHATCKN S1 ON SFRSTCR_PIDM = SPRIDEN_PIDM

      LEFT OUTER JOIN SSASECT S2 ON S2.SSBSECT_TERM_CODE = S1.SFRSTCR_TERM_CODE
           AND S2.SSBSECT_CRN = S1.SFRSTCR_CRN

      LEFT OUTER JOIN SIRASGQ S3 ON S3.SIRASGN_TERM_CODE = S1.SFRSTCR_TERM_CODE
           AND S3.SIRASGN_CRN = S1.SFRSTCR_CRN
  ),

ADVISING_LIST_DEMO as
(
  SELECT
      CASE
        WHEN SPBPERS_SEX IS NULL THEN 0
          ELSE 1
            END as SEX_Measure,
      CASE
        WHEN GORRACE_RACE_CDE IS NULL THEN 0
          ELSE 1
            END as RACE_Measure,
      CASE
        WHEN SPBPERS_ETHN_CDE IS NULL THEN 0
          ELSE 1
            END as ETHN_Measure,
      CASE
        WHEN SGBSTDN_DEPT_CODE IS NULL THEN 0
          ELSE 1
            END as DEPT_Measure,
      CASE
        WHEN SGBSTDN_MAJR_CODE_1 IS NULL THEN 0
          ELSE 1
            END as POS_Measure,
      CASE
        WHEN SGBSTDN_DEGC_CODE_1 IS NULL THEN 0
          ELSE 1
            END as DEGC_Measure,
      CASE
        WHEN SGBSTDN_STYP_CODE IS NULL THEN 0
          ELSE 1
            END as STYP_Measure,
      CASE
        WHEN SGBSTDN_LEVL_CODE IS NULL THEN 0
          ELSE 1
            END as LEVL_Measure,
      CASE
        WHEN SGBSTDN_CLAS_CODE IS NULL THEN 0
          ELSE 1
            END as CLAS_Measure,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SFRTHST_TMST_CODE,
      SFRTHST_TMST_DESC,
      SGBSTDN_TERM_CODE_EFF,
      SGBSTDN_STST_CODE,
      SGBSTDN_STYP_CODE,
      SGBSTDN_LEVL_CODE,
      SGBSTDN_CLAS_CODE,
      SGBSTDN_DEPT_CODE,
      SGBSTDN_MAJR_CODE_1,
      SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN_DEGC_CODE_1,
      SGBSTDN_RESD_CODE,
      SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN_STYP_DESC,
      SGBSTDN_LEVL_DESC,
      SGBSTDN_CLAS_DESC,
      SGBSTDN_DEPT_DESC,
      SGBSTDN_MAJR_DESC,
      SGBSTDN_MINR_1_DESC,
      SGBSTDN_MINR_1_2_DESC,
      SGBSTDN_CONC_DESC,
      SGBSTDN_DEGC_DESC,
      SGBSTDN_RESD_DESC,
      S1.SHRTGPA_HOURS_ATTEMPTED,
      S1.SHRTGPA_HOURS_EARNED,
      S1.SHRTGPA_GPA_HOURS,
      S1.SHRTGPA_QUALITY_POINTS,
      S1.SHRTGPA_GPA,
      S1.SHRLGPA_HOURS_ATTEMPTED,
      S1.SHRLGPA_HOURS_EARNED,
      S1.SHRLGPA_GPA_HOURS,
      S1.SHRLGPA_QUALITY_POINTS,
      S1.SHRLGPA_GPA,
      SHRTTRM_TERM_CODE,
      SHRTTRM_RECORD_STATUS_DATE,
      SHRTTRM_ASTD_CODE_END_OF_TERM,
      SHRTTRM_ASTD_DESC_END_OF_TERM,
      SHRTTRM_ASTD_DATE_END_OF_TERM,
      SHRTTRM_ACTIVITY_DATE,
      SHRTTRM_ASTD_CODE_DL,
      SHRTTRM_ASTD_DESC_DL,
      SHRTTRM_ASTD_DATE_DL,
      SHRTTRM_WRSN_CODE,
      SHRTTRM_WRSN_DESC,
      SGRADVR_PIDM,
      SGRADVR_ADVR_PIDM,
      SGRADVR_ADVR_NAME,
      SGRADVR_NAME,
      SGRADVR_ADVR_DESC,
      SGRADVR_TERM_CODE_EFF,
      SGRADVR_ADVR_EMAIL

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN_PIDM

      LEFT OUTER JOIN SHAGPAR S1 ON S1.SHRLGPA_PIDM = SPRIDEN_PIDM
           AND S1.SHRTGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE
           AND S1.SHRLGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE

      LEFT OUTER JOIN SHATERM SHRTTRM ON SHRTTRM.SHRTTRM_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SGAADVR SGRADVR ON SGRADVR.SGRADVR_PIDM = SPRIDEN_PIDM
           AND SGRADVR.SGRADVR_PRIM_IND = 'Y'

  WHERE
      SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
  ),

ADVISING_ADRTELE as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SGRADVR_PIDM,
      SGRADVR_ADVR_PIDM,
      SGRADVR_ADVR_NAME,
      SGRADVR_NAME,
      SGRADVR_ADVR_DESC,
      SGRADVR_TERM_CODE_EFF,
      SGRADVR_ADVR_EMAIL,
      SPRADDR_PIDM,
      SPRADDR_ATYP_CODE,
      SPRADDR_ATYP_DESC,
      SPRADDR_FROM_DATE,
      SPRADDR_TO_DATE,
      SPRADDR_STREET_LINE1,
      SPRADDR_STREET_LINE2,
      SPRADDR_STREET_LINE3,
      SPRADDR_CITY,
      SPRADDR_STAT_CODE,
      SPRADDR_ZIP,
      SPRTELE_PIDM,
      SPRTELE_TELE_CODE,
      SPRTELE_TELE_DESC,
      SPRTELE_PHONE_AREA,
      SPRTELE_PHONE_NUMBER,
      SPREMRG_PIDM,
      SPREMRG_LAST_NAME,
      SPREMRG_FIRST_NAME,
      SPREMRG_MI,
      SPREMRG_RELT_CODE,
      SPREMRG_RELT_DESC,
      SPREMRG_PRIORITY,
      SPREMRG_STREET_LINE1,
      SPREMRG_STREET_LINE2,
      SPREMRG_STREET_LINE3,
      SPREMRG_CITY,
      SPREMRG_STAT_CODE,
      SPREMRG_NATN_CODE,
      SPREMRG_ZIP,
      SPREMRG_PHONE_AREA,
      SPREMRG_PHONE_NUMBER,
      SPREMRG_PHONE_EXT,
      SPREMRG_ACTIVITY_DATE,
      SPREMRG_ATYP_CODE,
      SPREMRG_HOUSE_NUMBER

  FROM
      ADVISING_LIST_DEMO A

      LEFT OUTER JOIN TUIADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPATELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPAEMRG SPREMRG ON SPREMRG.SPREMRG_PIDM = SPRIDEN_PIDM

  WHERE
      (SPREMRG_PRIORITY <= 1 OR SPREMRG_PRIORITY IS NULL)
  )

SELECT
-- reporting
    SPRIDEN_PIDM as Remove_Label_From_Dashboard,
    STVTERM.STVTERM_DESC as TERM_DESC,

-- Systems Info/PII
    SPRIDEN_ID as Banner_ID,
    SPBPERS_PREF_FIRST_NAME Pref_Fname,
    SPRIDEN_LEGAL_NAME as Student_Name,
    SPRIDEN_LAST_NAME as Last_Name,
    SPRIDEN_FIRST_NAME as First_Name,
    SPRIDEN_MI as MI,
    SPBPERS_AGE as Age,
    SPBPERS_SEX as Sex,
    GORRACE_RACE_CDE as Race,
    GORRACE_DESC as Race_Decc,
    SPBPERS_ETHN_CDE as Ethnicity,
    SPBPERS_ETHN_DESC as Ethn_Desc,
    SPBPERS_SICAS_HISP_ORIGIN as Hisp_Origin,
    SPBPERS_CITZ_CODE as Citizen,
    SPBPERS_CITZ_COUNTRY as Citizenship,
    GOBINTL_NATN_CODE_BIRTH as Natn_Code,
    GOBINTL_BIRTH_NATN as Birth_Natn,

-- ID, SUID, EMail
    GORADID_ADDITIONAL_ID as SUID,
    GOBTPAC_EXTERNAL_USER as ESF_Netid,
    GOREMAL_EMAIL_ADDRESS as Email_Address,
    GOREMAL_EMAL_CODE as Email_Code,

-- Matriculation
    SFRTHST_TMST_CODE as TMST_Code,
    SFRTHST_TMST_DESC as TMST_Desc,
    SGBSTDN_TERM_CODE_EFF as Stdn_Eff_Term,
    SGBSTDN_STST_CODE as Stdn_STST,
    SGBSTDN_STYP_CODE as Stdn_STYP,
    SGBSTDN_LEVL_CODE as Stdn_Level,
    SGBSTDN_CLAS_CODE as Stdn_Class,
    SGBSTDN_DEPT_CODE as Stdn_Dept,
    SGBSTDN_MAJR_CODE_1 as Stdn_Major,
    SGBSTDN_MAJR_CODE_MINR_1 as Stdn_Minor,
    SGBSTDN_MAJR_CODE_MINR_1_2 as Stdn_Minor_2,
    SGBSTDN_MAJR_CODE_CONC_1 as Stdn_Conc,
    SGBSTDN_DEGC_CODE_1 as Stdn_Degree,
    SGBSTDN_RESD_CODE as Stdn_Residency,
    SGBSTDN_EXP_GRAD_DATE as Stdn_Exp_Grad_Date,
    SGBSTDN_STYP_DESC as Stdn_STYP_Desc,
    SGBSTDN_LEVL_DESC as Stdn_Levl_Desc,
    SGBSTDN_CLAS_DESC as Stdn_Class_Desc,
    SGBSTDN_DEPT_DESC as Stdn_Dept_Desc,
    SGBSTDN_MAJR_DESC as Stdn_Major_Desc,
    SGBSTDN_MINR_1_DESC as Stdn_Minor_Desc,
    SGBSTDN_MINR_1_2_DESC as Stdn_Minor_2_Desc,
    SGBSTDN_CONC_DESC as Stdn_Conc_Desc,
    SGBSTDN_DEGC_DESC as Stdn_Degree_Desc,
    SGBSTDN_RESD_DESC as Stdn_Resd_Desc,

-- Course Enrollment
    SFRSTCR_CRN as Reg_CRN,
    SFRSTCR_REG_SEQ as Reg_Seq_No,
    SFRSTCR_PTRM_CODE as Reg_PTRM,
    SFRSTCR_RSTS_CODE as Reg_RSTS,
    SFRSTCR_BILL_HR as Reg_Bill_Hr,
    SFRSTCR_WAIV_HR as Reg_Waiv_Hr,
    SFRSTCR_CREDIT_HR as Reg_Credit_Hr,
    SFRSTCR_BILL_HR_HOLD as Reg_Bill_Hr_Hold,
    SFRSTCR_CREDIT_HR_HOLD as Reg_Credit_Hr_Hold,
    SFRSTCR_GMOD_CODE as Reg_GMOD_Code,
    SFRSTCR_GRDE_CODE as Reg_Grade_Code,
    SFRSTCR_GRDE_DATE as Reg_Grade_Date,
    SFRSTCR_ADD_DATE as Reg_Add_Date,
    SFRSTCR_ACTIVITY_DATE as Reg_Activity,
    SFRSTCR_LEVL_CODE as Reg_Levl_Code,
    SFRSTCR_CAMP_CODE as Reg_Camp_Code,

-- Registration Audit
    SFRSTCA_TERM_CODE as Audit_Term,
    SFRSTCA_CRN as Audit_CRN,
    SFRSTCA_SEQ_NUMBER as Audit_Seq_No,
    SFRSTCA_LEVL_CODE as Audit_Levl_Code,
    SFRSTCA_CAMP_CODE as Audit_Camp_Code,
    SFRSTCA_ADD_DATE as Add_Date,
    SFRSTCA_ACTIVITY_DATE as Audit_Activity,
    SFRSTCA_RSTS_CODE as Audit_RSTS,
    SFRSTCA_RSTS_DATE as Audit_RSTS_Date,
    SFRSTCA_ERROR_FLAG as Error_Flag,
    SFRSTCA_MESSAGE as Message,
    SFRSTCA_CREDIT_HR as Audit_Credit_Hr,
    SFRSTCA_GMOD_CODE as Audit_GMOD_Code,
    SFRSTCA_ATTEMPT_HR as Audit_Attempt_Hr,
    SFRSTCA_RMSG_CDE as Audit_RMSG,
    SFRSTCA_ENRL as Audit_Enrolled,
    SFRSTCA_SEATS_AVAIL as Audit_Seat_Avail,

-- Class Details
    SHRTCKN_TERM_CODE as Class_Term_Code,
    SHRTCKN_SEQ_NO as Class_Seq_No,
    SHRTCKN_CRN as Class_CRN,
    SHRTCKN_SUBJ_CODE as Class_Subj,
    SHRTCKN_CRSE_NUMB as Class_Numb,
    SHRTCKN_COLL_CODE as Class_Coll_Code,
    SHRTCKN_CAMP_CODE as Class_Camp_Code,
    SHRTCKN_ACTIVITY_DATE as Class_Activity,
    SHRTCKN_SEQ_NUMB as Class_Seq_No,

-- Recorded Course Grades
    SHRTCKG_TERM_CODE as Grade_Term_Code,
    SHRTCKG_TCKN_SEQ_NO as Final_Grade_TCKN_Seq_No,
    SHRTCKG_SEQ_NO as Final_Grade_Seq_No,
    SHRTCKG_FINAL_GRDE_SEQ_NO as Final_Grade_Final_Grade_Seq_No,
    SHRTCKG_GRDE_CODE_FINAL as Final_Grade_Code_Final,
    SHRTCKG_GMOD_CODE as Final_Grade_GMOD_Code,
    SHRTCKG_CREDIT_HOURS as Final_Grade_Credit_Hr,
    SHRTCKG_GCHG_CODE as Final_Grade_GCHG_Code,
    SHRTCKG_FINAL_GRDE_CHG_DATE as Final_Grade_Change_Date,
    SHRTCKG_HOURS_ATTEMPTED as Final_Grade_Credit_Hr_Att,
    SHRTCKL_PRIMARY_LEVL_IND as Primary_Levl_Ind,

-- Grade Codes Valuation
    SHRGRDE_CODE as Grade_Code,
    SHRGRDE_LEVL_CODE as Grade_Levl_Code,
    SHRGRDE_QUALITY_POINTS as Grade_Quality_Points,
    SHRGRDE_ATTEMPTED_IND as Attempted_Ind,
    SHRGRDE_COMPLETED_IND as Competed_Ind,
    SHRGRDE_PASSED_IND as Passed_Ind,
    SHRGRDE_GPA_IND as GPA_Ind,

-- Departmental Instructor Info
    SIRASGN_TERM_CODE as Instructor_Term_Code,
    SIRASGN_CRN as Instructor_CRN,
    SIRDPCL_TERM_CODE_EFF as Dept_Eff_Term,
    SIRDPCL_TERM_CODE_EFF as Dept_Eff_Term,
    SIRDPCL_COLL_CODE as Dept_Coll_Code,
    SIRDPCL_DEPT_CODE as Dept_Code,
    SIRASGN_PRIMARY_IND as Dept_Prim_Ind,
    SIRDPCL_DEPT_DESC as Dept_Desc,
    SIRDPCL_INSTR_NAME as Dept_Instr_Name,
    SIRDPCL_INSTR_EMAIL as Dept_Instr_Email,

-- Course Section Info
    SSBSECT_TERM_CODE as Section_Term_Code,
    SSBSECT_CRN as Section_CRN,
    SSBSECT_PTRM_CODE as Section_PTRM,
    SSBSECT_SUBJ_CODE as Section_Subj,
    SSBSECT_CRSE_NUMB as Section_Numb,
    SSBSECT_SEQ_NUMB as Section_Seq_No,
    SSBSECT_SSTS_CODE as Section_SSTS_Code,
    SSBSECT_SCHD_CODE as Section_SCHD_Code,
    SSBSECT_CAMP_CODE as Section_Camp_Code,
    SSBSECT_CREDIT_HRS as Section_Credit_Hr,
    SSBSECT_BILL_HRS as Section_Bill_Hr,
    SSBSECT_GMOD_CODE as Section_GMOD_Code,
    SSBSECT_REG_ONEUP as Section_Reg_Oneup,
    SSBSECT_PRIOR_ENRL as Section_Prior_Enrl,
    SSBSECT_PROJ_ENRL as Section_Proj_Enrl,
    SSBSECT_MAX_ENRL as Section_Max_Enrl,
    SSBSECT_ENRL as Section_Enrl,
    SSBSECT_SEATS_AVAIL as Section_Seats_Avail,
    SSBSECT_TOT_CREDIT_HRS as Section_Tot_Credit_Hr,
    SSBSECT_CENSUS_ENRL as Section_Census_Enrl,
    SSBSECT_CENSUS_ENRL_DATE as Section_Census_Enrl_Date,
    SSBSECT_ACTIVITY_DATE as Section_Activity,
    SSBSECT_PTRM_START_DATE as Section_PTRM_Start_Date,
    SSBSECT_PTRM_END_DATE as Section_PTRM_End_Date,
    SSBSECT_PTRM_WEEKS as Section_PTRM_Weeks,
    SSBSECT_WAIT_CAPACITY as Section_Wait_Capactiy,
    SSBSECT_WAIT_COUNT as Section_Wait_Count,
    SSBSECT_WAIT_AVAIL as Section_Wait_Avail,
    SSBSECT_INSM_CODE as Section_INSM_Code,
    SSBSECT_SICAS_CAMP_COURSE_ID as SICAS_Course_ID,
    SSBSECT_SICAS_CAMP_SECTION_ID as SICAS_Section_ID,
    SCBCRSE_SUBJ_CODE as Course_Subj,
    SCBCRSE_CRSE_NUMB as Course_Numb,
    SCBCRSE_EFF_TERM as Course_Eff_Term,
    SCBCRSE_COLL_CODE as Course_Coll_Code,
    SCBCRSE_DIVS_CODE as Course_DIVS_Code,
    SCBCRSE_DEPT_CODE as Course_Dept,
    SCBCRSE_CSTA_CODE as Course_Active,
    SCBCRSE_TITLE as Course_Title,
    SCBCRSE_CIPC_CODE as Course_CIPC_Code,
    SCBCRSE_CREDIT_HR_IND as Course_Credit_Hr_Ind,
    SCBCRSE_CREDIT_HR_LOW as Course_Credit_Hr_Low,
    SCBCRSE_CREDIT_HR_HIGH as Course_Credit_Hr_Low,
    SCBCRSE_LEC_HR_IND as Course_LEC_HR_Ind,
    SCBCRSE_LEC_HR_LOW as Course_LEC_HR_Low,
    SCBCRSE_LEC_HR_HIGH as Course_LEC_HR_High,
    SCBCRSE_BILL_HR_IND as Course_BILL_HR_Ind,
    SCBCRSE_BILL_HR_LOW as Course_BILL_HR_Low,
    SCBCRSE_BILL_HR_HIGH as Course_BILL_HR_High,
    SCBCRSE_ACTIVITY_DATE as Course_Activity,
    SCBCRSE_CONT_HR_LOW as Course_Cont_HR_Low,
    SCBCRSE_CONT_HR_IND as Course_Cont_HR_Ind,
    SCBCRSE_CONT_HR_HIGH as Course_Cont_HR_High,
    SCBCRSE_REPS_CODE as Course_Reps_Code,
    SCBCRSE_MAX_RPT_UNITS as Course_Max_Repeat_Units,
    SCBCRSE_VPDI_CODE as Course_VPDI_Code,
    SCBCRSE_SICAS_SUNY_ID as Course_SICAS_SUNY_ID,
    SSRMEET_TERM_CODE as Meeting_Term_Code,

-- Schedule of Classes
    SSRMEET_CRN as Metting_CRN,
    SSRMEET_DAYS_CODE as Meeting_Days_Code,
    SSRMEET_DAY_NUMBER as Meeting_Days_No,
    SSRMEET_BEGIN_TIME as Meeting_Begin_Time,
    SSRMEET_END_TIME as Meeting_End_Time,
    SSRMEET_BLDG_CODE as Meeting_BLDG_Code,
    SSRMEET_ROOM_CODE as Meeting_Room_Code,
    SSRMEET_ACTIVITY_DATE as Meeting_Activity,
    SSRMEET_START_DATE as Meeting_Start_Date,
    SSRMEET_END_DATE as Meeting_End_Date,
    SSRMEET_SUN_DAY as Meeting_Sun,
    SSRMEET_MON_DAY as Meeting_Mon,
    SSRMEET_TUE_DAY as Meeting_Tue,
    SSRMEET_WED_DAY as Meeting_Wed,
    SSRMEET_THU_DAY as Meeting_Thu,
    SSRMEET_FRI_DAY as Meeting_Fri,
    SSRMEET_SAT_DAY as Meeting_Sat,
    SSRMEET_SCHD_CODE as Meeting_SCHD_Code,
    SSRMEET_CREDIT_HR_SESS as Meeting_Credit_Hr_Sess,
    SSRMEET_MEET_NO as Meeting_Meet_No,
    SSRMEET_HRS_WEEK as Meeting_Hrs_Week,
    SSRMEET_MTYP_CODE as Meeting_MTYP_Code,
    SSBSECT_SSTS_DESC as Section_SSTS_Desc,
    SSBSECT_SCHD_DESC as Section_SCHD_Desc,
    SCBCRSE_CSTA_DESC as Course_CSTA_Desc,
    SCBCRSE_REPS_DESC as Course_REPS_Desc,

-- Sorting
    STVCLAS_SURROGATE_ID

FROM
    STUDENT_GRADE_LIST B
--    LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE
    LEFT OUTER JOIN STVTERM STVTERM ON STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE

WHERE
    NULL IS NULL

--    AND SPRADDR.SPRADDR_ATYP_CODE = :select_atyp_code.STVATYP_CODE
--    AND SPRADDR.SPRADDR_ATYP_CODE IN (SELECT STVATYP_CODE FROM STVATYP)

      -- STUDENT CONDITIONS
--    AND SGBSTDN_STYP_CODE = :select_styp_code.STVSTYP_CODE
--    AND SGBSTDN_LEVL_CODE = :select_levl_code.STVLEVL_CODE
--    AND SGBSTDN_CLAS_CODE = :select_clas_code.STVCLAS_CODE
--    AND SGBSTDN_DEPT_CODE = :select_dept_code.STVDEPT_CODE
--    AND SGBSTDN_DEGC_CODE_1 = :select_degc_code.STVDEGC_CODE
--    AND SGBSTDN_MAJR_CODE_1 = :select_majr_code.STVMAJR_CODE
    AND SGBSTDN_STST_CODE = 'AS'
    AND SGBSTDN_STYP_CODE <> 'X'

      -- WITHDRAWN CONDITIONS
--    AND SFRWDRL_TERM_CODE = :select_term_code.STVTERM_CODE
--    AND SFRWDRL_ESTS_CODE = :select_ests_code.STVESTS_CODE
--    AND SFRWDRL_ESTS_CODE IN (SELECT STVESTS_CODE FROM STVESTS)

      -- ENROLLMENT CONDITIONS
--    AND 'Y' = F_REGISTERED_THIS_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
--    AND EXISTS (SELECT * FROM SFAREGS WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN ('RE', 'RW'))
--    AND EXISTS (SELECT * FROM SFAREGS WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE AND SFRSTCR_RSTS_CODE IN (SELECT STVRSTS_CODE FROM STVRSTS))

      -- GRADATION CONDITIONS
--    AND SHRDGMR_ACYR_cODE = STVTERM_ACYR_CODE
--    AND SHRDGMR_DEGS_CODE = :select_degs_code.STVDEGS_CODE
--    AND SHRDGMR_LEVL_CODE = :select_levl_code.STVLEVL_CODE
--    AND SHRDGMR_CLAS_CODE = :select_clas_code.STVCLAS_CODE
--    AND SHRDGMR_DEPT_CODE = :select_dept_code.STVDEPT_CODE
--    AND SHRDGMR_DEGC_CODE_1 = :select_degc_code.STVDEGC_CODE
--    AND SHRDGMR_MAJR_CODE_1 = :select_majr_code.STVMAJR_CODE

      -- APPLICATION CONDITIONS
--    AND SARADAP_TERM_CODE_ENTRY = :select_term_code.STVTERM_CODE
--    AND SARADAP_LEVL_CODE = :select_levl_code.STVLEVL_CODE
--    AND SARADAP_STYP_CODE = :select_styp_code.STVSTYP_CODE
--    AND SARADAP_DEPT_CODE = :select_dept_code.STVDEPT_CODE
--    AND SARADAP_DEGC_CODE_1 = :select_degc_code.STVDEGC_CODE
--    AND SARADAP_MAJR_CODE_1 = :select_majr_code.STVMAJR_CODE
--    AND SARAPPD_APDC_CODE = :select_apdc_code.STVAPDC_CODE

      -- HS TRANSCRIPTS
--    AND SORPCOL.SORPCOL_ADMR_CODE = :select_admr_code.STVADMR_CODE --'HST1'

--$addfilter

--$beginorder

ORDER BY
    1

--$endorder
