/**************************************************
ERROR: CONTACT

Bob Ali

Information Systems Developer, Information Systems

SUNY College of Environmental Science and Forestry

22 Bray Hall � 1 Forestry Drive, Syracuse, NY, 13210

bali04@esf.edu  � https://www.esf.edu/computing/

***************************************************/

WITH SPAIDEN as
(
  SELECT
      SPRIDEN.SPRIDEN_PIDM,
      SPRIDEN.SPRIDEN_ID,
      SPRIDEN.SPRIDEN_LAST_NAME,
      SPRIDEN.SPRIDEN_FIRST_NAME,
      SPRIDEN.SPRIDEN_MI,
      SPRIDEN.SPRIDEN_CHANGE_IND,
      SPRIDEN.SPRIDEN_ENTITY_IND,
      SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN.SPRIDEN_SEARCH_MI,
      SPRIDEN.SPRIDEN_SURROGATE_ID,
      SPRIDEN.SPRIDEN_VERSION,
      f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME

  FROM
      SPRIDEN SPRIDEN

  WHERE
      SPRIDEN.SPRIDEN_NTYP_CODE is NULL
      AND SPRIDEN.SPRIDEN_CHANGE_IND is NULL
  ),

TUIADDR as
(
  SELECT
      SPRADDR.SPRADDR_PIDM,
      SPRADDR.SPRADDR_ATYP_CODE,
      SPRADDR.SPRADDR_SEQNO,
      SPRADDR.SPRADDR_FROM_DATE,
      SPRADDR.SPRADDR_TO_DATE,
      SPRADDR.SPRADDR_STREET_LINE1,
      SPRADDR.SPRADDR_STREET_LINE2,
      SPRADDR.SPRADDR_STREET_LINE3,
      SPRADDR.SPRADDR_CITY,
      SPRADDR.SPRADDR_STAT_CODE,
      SPRADDR.SPRADDR_ZIP,
      SPRADDR.SPRADDR_CNTY_CODE,
      f_get_desc_fnc('STVATYP', SPRADDR.SPRADDR_ATYP_CODE, 30) as SPRADDR_ATYP_DESC,
      f_get_desc_fnc('STVCNTY', SPRADDR.SPRADDR_CNTY_CODE, 30) as SPRADDR_CNTY_DESC

  FROM
      SPRADDR SPRADDR

  WHERE
      SPRADDR.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
      AND SPRADDR.SPRADDR_STATUS_IND IS NULL
      AND SPRADDR.SPRADDR_VERSION = (SELECT MAX(SPRADDR_VERSION)
                                    FROM   SPRADDR SPRADDRX
                                    WHERE  SPRADDRX.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                    AND    SPRADDRX.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
                                    AND    SPRADDRX.SPRADDR_STATUS_IND IS NULL)
      AND SPRADDR.SPRADDR_SURROGATE_ID = (SELECT MAX(SPRADDR_SURROGATE_ID)
                                         FROM   SPRADDR SPRADDRX
                                         WHERE  SPRADDRX.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
                                         AND    SPRADDRX.SPRADDR_ATYP_CODE IN ('MA','PA','PR')
                                         AND    SPRADDRX.SPRADDR_STATUS_IND IS NULL)
  ),

SPATELE as
(
  SELECT
      SPRTELE.SPRTELE_PIDM,
      SPRTELE.SPRTELE_TELE_CODE,
      SPRTELE.SPRTELE_PHONE_AREA,
      SPRTELE.SPRTELE_PHONE_NUMBER,
      SPRTELE.SPRTELE_SURROGATE_ID,
      SPRTELE.SPRTELE_VERSION,
      f_get_desc_fnc('STVTELE', SPRTELE.SPRTELE_TELE_CODE, 30) as SPRTELE_TELE_DESC

  FROM
      SPRTELE SPRTELE

  WHERE
      SPRTELE.SPRTELE_SURROGATE_ID = (SELECT MAX(SPRTELE_SURROGATE_ID)
                                     FROM   SPRTELE SPRTELEX
                                     WHERE  SPRTELEX.SPRTELE_PIDM = SPRTELE.SPRTELE_PIDM
                                     AND    SPRTELEX.SPRTELE_STATUS_IND IS NULL)
  ),

SPAEMRG AS
(
  SELECT
      SPREMRG.SPREMRG_PIDM,
      SPREMRG.SPREMRG_PRIORITY,
      SPREMRG.SPREMRG_LAST_NAME,
      SPREMRG.SPREMRG_FIRST_NAME,
      SPREMRG.SPREMRG_MI,
      SPREMRG.SPREMRG_STREET_LINE1,
      SPREMRG.SPREMRG_STREET_LINE2,
      SPREMRG.SPREMRG_STREET_LINE3,
      SPREMRG.SPREMRG_CITY,
      SPREMRG.SPREMRG_STAT_CODE,
      SPREMRG.SPREMRG_NATN_CODE,
      SPREMRG.SPREMRG_ZIP,
      SPREMRG.SPREMRG_PHONE_AREA,
      SPREMRG.SPREMRG_PHONE_NUMBER,
      SPREMRG.SPREMRG_PHONE_EXT,
      SPREMRG.SPREMRG_RELT_CODE,
      SPREMRG.SPREMRG_ACTIVITY_DATE,
      SPREMRG.SPREMRG_ATYP_CODE,
      SPREMRG.SPREMRG_HOUSE_NUMBER,
      SPREMRG.SPREMRG_STREET_LINE4,
      SPREMRG.SPREMRG_SURROGATE_ID,
      SPREMRG.SPREMRG_VERSION,
      f_get_desc_fnc('STVRELT', SPREMRG.SPREMRG_RELT_CODE, 30) as SPREMRG_RELT_DESC

  FROM
      SPREMRG SPREMRG
  ),

SPAPERS as
(
  SELECT
      SPBPERS.SPBPERS_PIDM,
      SPBPERS.SPBPERS_SSN,
      SPBPERS.SPBPERS_BIRTH_DATE,
      SPBPERS.SPBPERS_SEX,
      SPBPERS.SPBPERS_CONFID_IND,
      SPBPERS.SPBPERS_PREF_FIRST_NAME,
      SPBPERS.SPBPERS_CITZ_CODE,
      SPBPERS.SPBPERS_ETHN_CDE,
      SPBPERS.SPBPERS_SURROGATE_ID,
      SPBPERS.SPBPERS_VERSION,
      SPBPERS.SPBPERS_GNDR_CODE,
      GOBINTL.GOBINTL_PIDM,
      GOBINTL.GOBINTL_SPOUSE_IND,
      GOBINTL.GOBINTL_SIGNATURE_IND,
      GOBINTL.GOBINTL_NATN_CODE_BIRTH,
      GOBINTL.GOBINTL_SURROGATE_ID,
      GOBINTL.GOBINTL_VERSION,
      CASE
        WHEN SPBPERS_ETHN_CDE IN (2,3,4,5,6,7,9,10) THEN 'Y'
          ELSE 'N'
            END AS SPBPERS_SICAS_HISP_ORIGIN,
      CASE
        WHEN SPBPERS.SPBPERS_CITZ_CODE = 'Y' THEN 'United States'
          ELSE (SELECT STVNATN_NATION
               FROM    STVNATN
               WHERE   STVNATN_CODE = NVL(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
                 END AS SPBPERS_CITZ_COUNTRY,
      F_GET_DESC_FNC('STVETHN', SPBPERS_ETHN_CDE, 30) as SPBPERS_ETHN_DESC,
      F_GET_DESC_FNC('STVNATN', GOBINTL_NATN_CODE_BIRTH, 30) as GOBINTL_BIRTH_NATN,
      ROUND(((SYSDATE - SPBPERS_BIRTH_DATE)/365), 0) as SPBPERS_AGE

    FROM
        SPBPERS SPBPERS
        LEFT OUTER JOIN GOBINTL GOBINTL ON GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
    ),

GOARACE as
(
  SELECT
      GORPRAC.GORPRAC_PIDM AS GORPRAC_PIDM,
      -- GORPRAC_RACE_CDE,
      (LISTAGG(GORPRAC.GORPRAC_RACE_CDE,', ') WITHIN GROUP (ORDER BY GORPRAC.GORPRAC_RACE_CDE)) AS GORRACE_RACE_CDE,
      (LISTAGG(GORRACE.GORRACE_DESC,', ') WITHIN GROUP (ORDER BY GORRACE.GORRACE_DESC)) AS GORRACE_DESC

  FROM
      GORPRAC GORPRAC
      LEFT OUTER JOIN GORRACE GORRACE ON GORRACE.GORRACE_RACE_CDE = GORPRAC.GORPRAC_RACE_CDE

  GROUP BY
      GORPRAC.GORPRAC_PIDM
  ),

SOREMAL as
(
  SELECT
      GOREMAL.GOREMAL_PIDM,
      GOREMAL.GOREMAL_EMAL_CODE,
      GOREMAL.GOREMAL_EMAIL_ADDRESS,
      GOREMAL.GOREMAL_STATUS_IND,
      GOREMAL.GOREMAL_PREFERRED_IND,
      GOREMAL.GOREMAL_ACTIVITY_DATE,
      GOREMAL.GOREMAL_SURROGATE_ID,
      GOREMAL.GOREMAL_VERSION,
      GORADID.GORADID_PIDM,
      GORADID.GORADID_ADDITIONAL_ID,
      GORADID.GORADID_ADID_CODE,
      GORADID.GORADID_SURROGATE_ID,
      GORADID.GORADID_VERSION,
      GOBTPAC.GOBTPAC_PIDM,
      GOBTPAC.GOBTPAC_PIN_DISABLED_IND,
      GOBTPAC.GOBTPAC_USAGE_ACCEPT_IND,
      GOBTPAC.GOBTPAC_PIN,
      GOBTPAC.GOBTPAC_PIN_EXP_DATE,
      GOBTPAC.GOBTPAC_SURROGATE_ID,
      GOBTPAC.GOBTPAC_VERSION,
      GOBTPAC.GOBTPAC_EXTERNAL_USER --esfid

  FROM
      GOREMAL GOREMAL
      LEFT OUTER JOIN GORADID GORADID ON GORADID.GORADID_PIDM = GOREMAL.GOREMAL_PIDM
           AND GORADID.GORADID_ADID_CODE = 'SUID'
      LEFT OUTER JOIN GOBUMAP GOBUMAP ON GOBUMAP.GOBUMAP_PIDM = GOREMAL.GOREMAL_PIDM
      LEFT OUTER JOIN GOBTPAC GOBTPAC ON GOBTPAC.GOBTPAC_PIDM = GOREMAL.GOREMAL_PIDM

  WHERE
      GOREMAL.GOREMAL_STATUS_IND = 'A'
      AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
      AND GOREMAL.GOREMAL_EMAL_CODE IN ('ESF', 'SU', 'AD', 'PERS')
      --AND GORADID.GORADID_ADID_CODE = 'SUID'
  ),

SGASTDN as
(
  SELECT
      SGBSTDN.SGBSTDN_PIDM,
      SGBSTDN.SGBSTDN_TERM_CODE_EFF,
      SGBSTDN.SGBSTDN_STST_CODE,
      SGBSTDN.SGBSTDN_LEVL_CODE,
      SGBSTDN.SGBSTDN_STYP_CODE,
      SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
      SGBSTDN.SGBSTDN_TERM_CODE_ADMIT,
      SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN.SGBSTDN_CAMP_CODE,
      SGBSTDN.SGBSTDN_COLL_CODE_1,
      SGBSTDN.SGBSTDN_DEGC_CODE_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN.SGBSTDN_RESD_CODE,
      SGBSTDN.SGBSTDN_ADMT_CODE,
      SGBSTDN.SGBSTDN_DEPT_CODE,
      SGBSTDN.SGBSTDN_PROGRAM_1,
      SGBSTDN.SGBSTDN_TERM_CODE_GRAD,
      SGBSTDN.SGBSTDN_ACTIVITY_DATE,
      SFRTHST.SFRTHST_PIDM,
      SFRTHST.SFRTHST_TERM_CODE,
      SFRTHST.SFRTHST_TMST_CODE,
      SFRTHST.SFRTHST_TMST_DATE,
      SFRTHST.SFRTHST_SURROGATE_ID,
      SFRTHST.SFRTHST_VERSION,
      CASE
        WHEN SFRTHST_TMST_CODE IS NULL THEN NULL
          ELSE f_Get_desc_fnc('STVTMST', SFRTHST.SFRTHST_TMST_CODE, 30)
            END as SFRTHST_TMST_DESC,
      f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM, SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF) as SGBSTDN_CLAS_CODE,
      f_get_desc_fnc('STVTERM',SGBSTDN.SGBSTDN_TERM_CODE_EFF, 30) as SGBSTDN_TERM_EFF_DESC,
      f_get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
      f_get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
      f_get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
      f_get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
      f_get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
      f_get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
      f_get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
      f_get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
      f_get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_MATRIC, 30) as SGBSTDN_MATRIC_TERM_DESC,
      f_get_desc_fnc('STVTERM', SGBSTDN.SGBSTDN_TERM_CODE_GRAD, 30) as SGBSTDN_GRAD_TERM_DESC,
      f_get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF), 30) as SGBSTDN_CLAS_DESC

  FROM
      SGBSTDN SGBSTDN
      LEFT OUTER JOIN SFRTHST SFRTHST ON SFRTHST.SFRTHST_PIDM = SGBSTDN.SGBSTDN_PIDM
           AND SFRTHST_SURROGATE_ID = (SELECT MAX(SFRTHST_SURROGATE_ID)
                                      FROM   SFRTHST SFRTHST1
                                      WHERE  SFRTHST1.SFRTHST_PIDM = SGBSTDN.SGBSTDN_PIDM
                                      AND    SFRTHST1.SFRTHST_TERM_CODE = SGBSTDN_TERM_CODE_EFF)
  ),

SHADEGR as
(
  SELECT
      SHRDGMR.SHRDGMR_PIDM,
      SHRDGMR.SHRDGMR_SEQ_NO,
      SHRDGMR.SHRDGMR_DEGC_CODE,
      SHRDGMR.SHRDGMR_DEGS_CODE,
      SHRDGMR.SHRDGMR_LEVL_CODE,
      SHRDGMR.SHRDGMR_COLL_CODE_1,
      SHRDGMR.SHRDGMR_MAJR_CODE_1,
      SHRDGMR.SHRDGMR_MAJR_CODE_MINR_1,
      SHRDGMR.SHRDGMR_MAJR_CODE_CONC_1,
      SHRDGMR.SHRDGMR_APPL_DATE,
      SHRDGMR.SHRDGMR_GRAD_DATE,
      SHRDGMR.SHRDGMR_ACYR_CODE_BULLETIN,
      SHRDGMR.SHRDGMR_CAMP_CODE,
      SHRDGMR.SHRDGMR_TERM_CODE_GRAD,
      SHRDGMR.SHRDGMR_ACYR_CODE,
      SHRDGMR.SHRDGMR_TERM_CODE_STUREC,
      SHRDGMR.SHRDGMR_ACTIVITY_DATE,
      SHRDGMR.SHRDGMR_GRST_CODE,
      SHRDGMR.SHRDGMR_TERM_CODE_COMPLETED,
      SHRDGMR.SHRDGMR_DEPT_CODE,
      SHRDGMR.SHRDGMR_PROGRAM,
      SHRDGMR.SHRDGMR_SURROGATE_ID,
      SHRDGMR.SHRDGMR_VERSION,
      SHRDGIH.SHRDGIH_PIDM,
      SHRDGIH.SHRDGIH_DGMR_SEQ_NO,
      SHRDGIH.SHRDGIH_HONR_CODE,
      SHRDGIH.SHRDGIH_ACTIVITY_DATE,
      SHRDGIH.SHRDGIH_TRANSC_PRT_IND,
      SHRDGIH.SHRDGIH_COMMENCE_PRT_IND,
      SHRDGIH.SHRDGIH_EDI_DEFAULT,
      SHRDGIH.SHRDGIH_SURROGATE_ID,
      SHRDGIH.SHRDGIH_VERSION,
      CASE
        WHEN SHRDGIH.SHRDGIH_HONR_CODE IS NULL THEN NULL
          ELSE f_get_desc_fnc('STVHONR', SHRDGIH.SHRDGIH_HONR_CODE, 30)
            END as SHRDGIH_HONR_DESC,
      f_get_desc_fnc('STVDEGS', SHRDGMR.SHRDGMR_DEGS_CODE, 30) as SHRDGMR_DEGS_DESC,
      f_get_desc_fnc('STVDEGC', SHRDGMR.SHRDGMR_DEGC_CODE, 30) as SHRDGMR_DEGC_DESC,
      f_get_desc_fnc('STVLEVL', SHRDGMR.SHRDGMR_LEVL_CODE, 30) as SHRDGMR_LEVL_DESC,
      f_get_desc_fnc('STVMAJR', SHRDGMR.SHRDGMR_MAJR_CODE_1, 30) as SHRDGMR_MAJR_DESC,
      f_get_desc_fnc('STVMAJR', SHRDGMR.SHRDGMR_COLL_CODE_1, 30) as SHRDGMR_COLL_DESC,
      f_get_desc_fnc('STVGRST', SHRDGMR.SHRDGMR_GRST_CODE, 30) as SHRDGMR_GRST_DESC

  FROM
      SHRDGMR SHRDGMR
      LEFT OUTER JOIN SHRDGIH SHRDGIH ON SHRDGIH.SHRDGIH_PIDM = SHRDGMR.SHRDGMR_PIDM
           AND SHRDGIH.SHRDGIH_DGMR_SEQ_NO = SHRDGMR.SHRDGMR_SEQ_NO

  WHERE
      SHRDGMR.SHRDGMR_TERM_CODE_GRAD = (SELECT MAX(SHRDGMR_TERM_CODE_GRAD)
                                       FROM    SHRDGMR SHRDGMRX
                                       WHERE   SHRDGMRX.SHRDGMR_PIDM = SHRDGMR.SHRDGMR_PIDM
                                       AND     SHRDGMRX.SHRDGMR_TERM_CODE_GRAD <= :select_term_code.STVTERM_CODE)
  ),

SFAWDRL as
(
  SELECT
      SFRWDRL.SFRWDRL_PIDM,
      SFRWDRL.SFRWDRL_TERM_CODE,
      SFRWDRL.SFRWDRL_SEQ_NO,
      SFRWDRL.SFRWDRL_WDRL_CODE,
      SFRWDRL.SFRWDRL_EFF_WDRL_DATE,
      SFRWDRL.SFRWDRL_ESTS_CODE,
      SFRWDRL.SFRWDRL_ESTS_DATE,
      SFRWDRL.SFRWDRL_TIV_IND,
      SFRWDRL.SFRWDRL_PROCESSED_IND,
      SFRWDRL.SFRWDRL_ENRL_START_DATE,
      SFRWDRL.SFRWDRL_ENRL_END_DATE,
      SFRWDRL.SFRWDRL_ENRL_DAYS,
      SFRWDRL.SFRWDRL_ATTEND_DAYS,
      SFRWDRL.SFRWDRL_PERCENT_ATTEND,
      SFRWDRL.SFRWDRL_ORIGINAL_CHARGES,
      SFRWDRL.SFRWDRL_ACTIVITY_DATE,
      SFRWDRL.SFRWDRL_SURROGATE_ID,
      SFRWDRL.SFRWDRL_VERSION,
      f_get_desc_fnc('STVESTS', SFRWDRL.SFRWDRL_ESTS_CODE, 30) as SFRWDRL_ESTS_DESC

  FROM
      SFRWDRL SFRWDRL

  WHERE
      SFRWDRL.SFRWDRL_TERM_CODE = (SELECT MAX(SFRWDRL_TERM_CODE)
                                  FROM    SFRWDRL SFRWDRLX
                                  WHERE   SFRWDRLX.SFRWDRL_PIDM = SFRWDRL.SFRWDRL_PIDM
                                  AND     SFRWDRLX.SFRWDRL_TERM_CODE <= :select_term_code.STVTERM_CODE)
  ),

SFAREGS as
(
  SELECT
      SFRSTCR.SFRSTCR_TERM_CODE,
      SFRSTCR.SFRSTCR_PIDM,
      SFRSTCR.SFRSTCR_CRN,
      SFRSTCR.SFRSTCR_CLASS_SORT_KEY,
      SFRSTCR.SFRSTCR_REG_SEQ,
      SFRSTCR.SFRSTCR_PTRM_CODE,
      SFRSTCR.SFRSTCR_RSTS_CODE,
      SFRSTCR.SFRSTCR_BILL_HR,
      SFRSTCR.SFRSTCR_WAIV_HR,
      SFRSTCR.SFRSTCR_CREDIT_HR,
      SFRSTCR.SFRSTCR_BILL_HR_HOLD,
      SFRSTCR.SFRSTCR_CREDIT_HR_HOLD,
      SFRSTCR.SFRSTCR_GMOD_CODE,
      SFRSTCR.SFRSTCR_GRDE_CODE,
      SFRSTCR.SFRSTCR_GRDE_DATE,
      SFRSTCR.SFRSTCR_ADD_DATE,
      SFRSTCR.SFRSTCR_LEVL_CODE,
      SFRSTCR.SFRSTCR_CAMP_CODE,
      SFRSTCA.SFRSTCA_TERM_CODE,
      SFRSTCA.SFRSTCA_PIDM,
      SFRSTCA.SFRSTCA_CRN,
      SFRSTCA.SFRSTCA_SEQ_NUMBER,
      SFRSTCA.SFRSTCA_LEVL_CODE,
      SFRSTCA.SFRSTCA_CAMP_CODE,
      SFRSTCA.SFRSTCA_ADD_DATE,
      SFRSTCA.SFRSTCA_ACTIVITY_DATE,
      SFRSTCA.SFRSTCA_RSTS_CODE,
      SFRSTCA.SFRSTCA_RSTS_DATE,
      SFRSTCA.SFRSTCA_ERROR_FLAG,
      SFRSTCA.SFRSTCA_MESSAGE,
      SFRSTCA.SFRSTCA_BILL_HR,
      SFRSTCA.SFRSTCA_CREDIT_HR,
      SFRSTCA.SFRSTCA_GMOD_CODE,
      SFRSTCA.SFRSTCA_USER,
      SFRSTCA.SFRSTCA_GCMT_CODE,
      SFRSTCA.SFRSTCA_SOURCE_CDE,
      SFRSTCA.SFRSTCA_DATA_ORIGIN,
      SFRSTCA.SFRSTCA_ATTEMPT_HR,
      SFRSTCA.SFRSTCA_RMSG_CDE,
      SFRSTCA.SFRSTCA_STSP_KEY_SEQUENCE,
      SFRSTCA.SFRSTCA_BRDH_SEQ_NUM,
      SFRSTCA.SFRSTCA_BLCK_CODE,
      SFRSTCA.SFRSTCA_STRH_SEQNO,
      SFRSTCA.SFRSTCA_STRD_SEQNO,
      SFRSTCA.SFRSTCA_SURROGATE_ID,
      SFRSTCA.SFRSTCA_VERSION,
      SFRSTCA.SFRSTCA_USER_ID,
      SFRSTCA.SFRSTCA_VPDI_CODE,
      SFRSTCA.SFRSTCA_SESSIONID,
      SFRSTCA.SFRSTCA_CURRENT_TIME,
      SFRSTCA.SFRSTCA_ENRL,
      SFRSTCA.SFRSTCA_SEATS_AVAIL

  FROM
      SFRSTCR SFRSTCR
      LEFT OUTER JOIN SFRSTCA SFRSTCA ON SFRSTCA.SFRSTCA_PIDM = SFRSTCR.SFRSTCR_PIDM
           AND SFRSTCA.SFRSTCA_TERM_CODE = SFRSTCR.SFRSTCR_TERM_CODE
           AND SFRSTCA.SFRSTCA_CRN = SFRSTCR.SFRSTCR_CRN
           AND SFRSTCA.SFRSTCA_SEQ_NUMBER = (SELECT MAX(SFRSTCA_SEQ_NUMBER)
                                            FROM    SFRSTCA SFRSTCAX
                                            WHERE   SFRSTCAX.SFRSTCA_PIDM = SFRSTCA_PIDM
                                            AND     SFRSTCAX.SFRSTCA_TERM_CODE = SFRSTCA_TERM_CODE
                                            AND     SFRSTCAX.SFRSTCA_CRN = SFRSTCA_CRN)

  WHERE
      SFRSTCR.SFRSTCR_TERM_CODE = :select_term_code.STVTERM_CODE
  ),

SHATCKN as
(
  SELECT
      SFRSTCR_TERM_CODE,
      SFRSTCR_PIDM,
      SFRSTCR_CRN,
      SFRSTCR_CLASS_SORT_KEY,
      SFRSTCR_REG_SEQ,
      SFRSTCR_PTRM_CODE,
      SFRSTCR_RSTS_CODE,
      SFRSTCR_BILL_HR,
      SFRSTCR_WAIV_HR,
      SFRSTCR_CREDIT_HR,
      SFRSTCR_BILL_HR_HOLD,
      SFRSTCR_CREDIT_HR_HOLD,
      SFRSTCR_GMOD_CODE,
      SFRSTCR_GRDE_CODE,
      SFRSTCR_GRDE_DATE,
      SFRSTCR_ADD_DATE,
      SFRSTCR_LEVL_CODE,
      SFRSTCR_CAMP_CODE,
      SFRSTCA_TERM_CODE,
      SFRSTCA_PIDM,
      SFRSTCA_CRN,
      SFRSTCA_SEQ_NUMBER,
      SFRSTCA_LEVL_CODE,
      SFRSTCA_CAMP_CODE,
      SFRSTCA_ADD_DATE,
      SFRSTCA_ACTIVITY_DATE,
      SFRSTCA_RSTS_CODE,
      SFRSTCA_RSTS_DATE,
      SFRSTCA_ERROR_FLAG,
      SFRSTCA_MESSAGE,
      SFRSTCA_BILL_HR,
      SFRSTCA_CREDIT_HR,
      SFRSTCA_GMOD_CODE,
      SFRSTCA_USER,
      SFRSTCA_GCMT_CODE,
      SFRSTCA_SOURCE_CDE,
      SFRSTCA_DATA_ORIGIN,
      SFRSTCA_ATTEMPT_HR,
      SFRSTCA_RMSG_CDE,
      SFRSTCA_STSP_KEY_SEQUENCE,
      SFRSTCA_BRDH_SEQ_NUM,
      SFRSTCA_BLCK_CODE,
      SFRSTCA_STRH_SEQNO,
      SFRSTCA_STRD_SEQNO,
      SFRSTCA_SURROGATE_ID,
      SFRSTCA_VERSION,
      SFRSTCA_USER_ID,
      SFRSTCA_VPDI_CODE,
      SFRSTCA_SESSIONID,
      SFRSTCA_CURRENT_TIME,
      SFRSTCA_ENRL,
      SFRSTCA_SEATS_AVAIL,
      SHRTCKN.SHRTCKN_PIDM,
      SHRTCKN.SHRTCKN_TERM_CODE,
      SHRTCKN.SHRTCKN_SEQ_NO,
      SHRTCKN.SHRTCKN_CRN,
      SHRTCKN.SHRTCKN_SUBJ_CODE,
      SHRTCKN.SHRTCKN_CRSE_NUMB,
      SHRTCKN.SHRTCKN_COLL_CODE,
      SHRTCKN.SHRTCKN_CAMP_CODE,
      SHRTCKN.SHRTCKN_ACTIVITY_DATE,
      SHRTCKN.SHRTCKN_SEQ_NUMB,
      SHRTCKN.SHRTCKN_SURROGATE_ID,
      SHRTCKN.SHRTCKN_VERSION,
      SHRTCKL.SHRTCKL_PIDM,
      SHRTCKL.SHRTCKL_TERM_CODE,
      SHRTCKL.SHRTCKL_TCKN_SEQ_NO,
      SHRTCKL.SHRTCKL_LEVL_CODE,
      SHRTCKL.SHRTCKL_ACTIVITY_DATE,
      SHRTCKL.SHRTCKL_PRIMARY_LEVL_IND,
      SHRTCKL.SHRTCKL_SURROGATE_ID,
      SHRTCKL.SHRTCKL_VERSION,
      SHRTCKG.SHRTCKG_PIDM,
      SHRTCKG.SHRTCKG_TERM_CODE,
      SHRTCKG.SHRTCKG_TCKN_SEQ_NO,
      SHRTCKG.SHRTCKG_SEQ_NO,
      SHRTCKG.SHRTCKG_FINAL_GRDE_SEQ_NO,
      SHRTCKG.SHRTCKG_GRDE_CODE_FINAL,
      SHRTCKG.SHRTCKG_GMOD_CODE,
      SHRTCKG.SHRTCKG_CREDIT_HOURS,
      SHRTCKG.SHRTCKG_GCHG_CODE,
      SHRTCKG.SHRTCKG_FINAL_GRDE_CHG_DATE,
      SHRTCKG.SHRTCKG_HOURS_ATTEMPTED,
      SHRTCKG.SHRTCKG_GRDE_CODE_INCMP_FINAL,
      SHRTCKG.SHRTCKG_SURROGATE_ID,
      SHRTCKG.SHRTCKG_VERSION,
      SHRGRDE.SHRGRDE_CODE,
      SHRGRDE.SHRGRDE_LEVL_CODE,
      SHRGRDE.SHRGRDE_QUALITY_POINTS,
      SHRGRDE.SHRGRDE_ATTEMPTED_IND,
      SHRGRDE.SHRGRDE_COMPLETED_IND,
      SHRGRDE.SHRGRDE_PASSED_IND,
      SHRGRDE.SHRGRDE_GPA_IND,
      SHRGRDE.SHRGRDE_SURROGATE_ID,
      SHRGRDE.SHRGRDE_VERSION,
      SHRGRDE.SHRGRDE_NUMERIC_VALUE,
      CASE
        WHEN SHRTCKG.SHRTCKG_GCHG_CODE IS NULL THEN NULL
          ELSE F_GET_DESC_FNC('STVGCHG', SHRTCKG.SHRTCKG_GCHG_CODE, 30)
            END as SHRTCKG_GCHG_DESC,
      decode(SHRGRDE.SHRGRDE_COMPLETED_IND,'Y',1,0) as COURSE_COMPLETE_IND,
      decode(SHRGRDE.SHRGRDE_PASSED_IND,'Y',1,0) as COURSE_PASSED_IND,
      decode(SHRGRDE.SHRGRDE_GPA_IND,'Y',1,0) as COURSE_GPA_IND,
      f_format_name(SFRSTCR_PIDM, 'LF30') as SFRSTCR_STUDENT_NAME

  FROM
      SFAREGS SFRSTCR

      LEFT OUTER JOIN SHRTCKN SHRTCKN ON SHRTCKN.SHRTCKN_PIDM = SFRSTCR_PIDM
           AND SHRTCKN.SHRTCKN_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKN.SHRTCKN_CRN = SFRSTCR_CRN

      LEFT OUTER JOIN SHRTCKG SHRTCKG ON SHRTCKG.SHRTCKG_PIDM = SFRSTCR_PIDM
           AND SHRTCKG.SHRTCKG_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKG.SHRTCKG_TCKN_SEQ_NO = SFRSTCR_REG_SEQ
           AND SHRTCKG.SHRTCKG_SEQ_NO = (SELECT MAX(SHRTCKG_SEQ_NO)
                                        FROM    SHRTCKG SHRTCKGX
                                        WHERE   SHRTCKGX.SHRTCKG_PIDM = SHRTCKG.SHRTCKG_PIDM
                                        AND     SHRTCKGX.SHRTCKG_TERM_CODE = SHRTCKG.SHRTCKG_TERM_CODE
                                        AND     SHRTCKGX.SHRTCKG_TCKN_SEQ_NO = SHRTCKG.SHRTCKG_TCKN_SEQ_NO)

      LEFT OUTER JOIN SHRTCKL SHRTCKL ON SHRTCKL.SHRTCKL_PIDM = SFRSTCR_PIDM
           AND SHRTCKL.SHRTCKL_TERM_CODE = SFRSTCR_TERM_CODE
           AND SHRTCKL.SHRTCKL_SURROGATE_ID = (SELECT MAX(SHRTCKL_SURROGATE_ID)
                                              FROM    SHRTCKL SHRTCKLX
                                              WHERE   SHRTCKLX.SHRTCKL_PIDM = SHRTCKL.SHRTCKL_PIDM
                                              AND     SHRTCKLX.SHRTCKL_TERM_CODE = SHRTCKL.SHRTCKL_TERM_CODE)

      LEFT OUTER JOIN SHRGRDE SHRGRDE ON SHRGRDE.SHRGRDE_CODE = SFRSTCR.SFRSTCR_GRDE_CODE
           AND SHRGRDE.SHRGRDE_LEVL_CODE = SHRTCKL.SHRTCKL_LEVL_CODE
           AND SHRGRDE.SHRGRDE_TERM_CODE_EFFECTIVE = (SELECT MAX(SHRGRDE_TERM_CODE_EFFECTIVE)
                                                     FROM    SHRGRDE SHRGRDEX
                                                     WHERE   SHRGRDEX.SHRGRDE_CODE = SHRGRDE.SHRGRDE_CODE
                                                     AND     SHRGRDEX.SHRGRDE_LEVL_CODE = SHRTCKL.SHRTCKL_LEVL_CODE
                                                     AND     SHRGRDEX.SHRGRDE_TERM_CODE_EFFECTIVE <= SFRSTCR_TERM_CODE)
  ),

SSASECT as
(
    SELECT
      SSBSECT.SSBSECT_TERM_CODE,
      SSBSECT.SSBSECT_CRN,
      SSBSECT.SSBSECT_PTRM_CODE,
      SSBSECT.SSBSECT_SUBJ_CODE,
      SSBSECT.SSBSECT_CRSE_NUMB,
      SSBSECT.SSBSECT_SEQ_NUMB,
      SSBSECT.SSBSECT_SSTS_CODE,
      SSBSECT.SSBSECT_SCHD_CODE,
      SSBSECT.SSBSECT_CAMP_CODE,
      SSBSECT.SSBSECT_CREDIT_HRS,
      SSBSECT.SSBSECT_BILL_HRS,
      SSBSECT.SSBSECT_GMOD_CODE,
      SSBSECT.SSBSECT_REG_ONEUP,
      SSBSECT.SSBSECT_PRIOR_ENRL,
      SSBSECT.SSBSECT_PROJ_ENRL,
      SSBSECT.SSBSECT_MAX_ENRL,
      SSBSECT.SSBSECT_ENRL,
      SSBSECT.SSBSECT_SEATS_AVAIL,
      SSBSECT.SSBSECT_TOT_CREDIT_HRS,
      SSBSECT.SSBSECT_CENSUS_ENRL,
      SSBSECT.SSBSECT_CENSUS_ENRL_DATE,
      SSBSECT.SSBSECT_ACTIVITY_DATE,
      SSBSECT.SSBSECT_PTRM_START_DATE,
      SSBSECT.SSBSECT_PTRM_END_DATE,
      SSBSECT.SSBSECT_PTRM_WEEKS,
      SSBSECT.SSBSECT_WAIT_CAPACITY,
      SSBSECT.SSBSECT_WAIT_COUNT,
      SSBSECT.SSBSECT_WAIT_AVAIL,
      SSBSECT.SSBSECT_INSM_CODE,
      SSBSECT.SSBSECT_SURROGATE_ID,
      SSBSECT.SSBSECT_VERSION,
      SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID,
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID,
      SCBCRSE.SCBCRSE_SUBJ_CODE,
      SCBCRSE.SCBCRSE_CRSE_NUMB,
      SCBCRSE.SCBCRSE_EFF_TERM,
      SCBCRSE.SCBCRSE_COLL_CODE,
      SCBCRSE.SCBCRSE_DIVS_CODE,
      SCBCRSE.SCBCRSE_DEPT_CODE,
      SCBCRSE.SCBCRSE_CSTA_CODE,
      SCBCRSE.SCBCRSE_TITLE,
      SCBCRSE.SCBCRSE_CIPC_CODE,
      SCBCRSE.SCBCRSE_CREDIT_HR_IND,
      SCBCRSE.SCBCRSE_CREDIT_HR_LOW,
      SCBCRSE.SCBCRSE_CREDIT_HR_HIGH,
      SCBCRSE.SCBCRSE_LEC_HR_IND,
      SCBCRSE.SCBCRSE_LEC_HR_LOW,
      SCBCRSE.SCBCRSE_LEC_HR_HIGH,
      SCBCRSE.SCBCRSE_BILL_HR_IND,
      SCBCRSE.SCBCRSE_BILL_HR_LOW,
      SCBCRSE.SCBCRSE_BILL_HR_HIGH,
      SCBCRSE.SCBCRSE_ACTIVITY_DATE,
      SCBCRSE.SCBCRSE_CONT_HR_LOW,
      SCBCRSE.SCBCRSE_CONT_HR_IND,
      SCBCRSE.SCBCRSE_CONT_HR_HIGH,
      SCBCRSE.SCBCRSE_REPS_CODE,
      SCBCRSE.SCBCRSE_MAX_RPT_UNITS,
      SCBCRSE.SCBCRSE_SURROGATE_ID,
      SCBCRSE.SCBCRSE_VERSION,
      SCBCRSE.SCBCRSE_VPDI_CODE,
      SCBCRSE.SCBCRSE_SICAS_SUNY_ID,
      SSRMEET.SSRMEET_TERM_CODE,
      SSRMEET.SSRMEET_CRN,
      SSRMEET.SSRMEET_DAYS_CODE,
      SSRMEET.SSRMEET_DAY_NUMBER,
      SSRMEET.SSRMEET_BEGIN_TIME,
      SSRMEET.SSRMEET_END_TIME,
      SSRMEET.SSRMEET_BLDG_CODE,
      SSRMEET.SSRMEET_ROOM_CODE,
      SSRMEET.SSRMEET_ACTIVITY_DATE,
      SSRMEET.SSRMEET_START_DATE,
      SSRMEET.SSRMEET_END_DATE,
      SSRMEET.SSRMEET_SUN_DAY,
      SSRMEET.SSRMEET_MON_DAY,
      SSRMEET.SSRMEET_TUE_DAY,
      SSRMEET.SSRMEET_WED_DAY,
      SSRMEET.SSRMEET_THU_DAY,
      SSRMEET.SSRMEET_FRI_DAY,
      SSRMEET.SSRMEET_SAT_DAY,
      SSRMEET.SSRMEET_SCHD_CODE,
      SSRMEET.SSRMEET_CREDIT_HR_SESS,
      SSRMEET.SSRMEET_MEET_NO,
      SSRMEET.SSRMEET_HRS_WEEK,
      SSRMEET.SSRMEET_MTYP_CODE,
      SSRMEET.SSRMEET_SURROGATE_ID,
      SSRMEET.SSRMEET_VERSION,
      F_GET_DESC_FNC('STVSSTS', SSBSECT.SSBSECT_SSTS_CODE, 30) as SSBSECT_SSTS_DESC,
      F_GET_DESC_FNC('STVCSTA', SCBCRSE.SCBCRSE_CSTA_CODE, 30) as SCBCRSE_CSTA_DESC,
      F_GET_DESC_FNC('STVREPS', SCBCRSE.SCBCRSE_REPS_CODE, 30) as SCBCRSE_REPS_DESC

  FROM
      SSBSECT SSBSECT

      LEFT OUTER JOIN SCBCRSE SCBCRSE ON SSBSECT.SSBSECT_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
           AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB

      LEFT OUTER JOIN SSRMEET SSRMEET ON SSRMEET.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
           AND SSRMEET.SSRMEET_CRN = SSBSECT.SSBSECT_CRN
           AND SSRMEET_SURROGATE_ID = (SELECT MAX(SSRMEET_SURROGATE_ID)
                                      FROM    SSRMEET SSRMEETX
                                      WHERE   SSRMEETX.SSRMEET_TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
                                      AND     SSRMEETX.SSRMEET_CRN = SSBSECT.SSBSECT_CRN)

  WHERE
      SSBSECT.SSBSECT_TERM_CODE = :select_term_code.STVTERM_CODE
      AND SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE_EFF_TERM)
                                    FROM     SCBCRSE SCBCRSEX
                                    WHERE    SCBCRSEX.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE
                                    AND      SCBCRSEX.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
                                    AND      SCBCRSEX.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE)
  ORDER BY
      SSBSECT.SSBSECT_SICAS_CAMP_SECTION_ID
  ),

SIRASGQ as
(
  SELECT
      SIRASGN.SIRASGN_TERM_CODE,
      SIRASGN.SIRASGN_CRN,
      SIRASGN.SIRASGN_PIDM,
      SIRDPCL.SIRDPCL_PIDM,
      SIRDPCL.SIRDPCL_TERM_CODE_EFF,
      SIRDPCL.SIRDPCL_COLL_CODE,
      SIRDPCL.SIRDPCL_DEPT_CODE,
      SIRASGN.SIRASGN_PRIMARY_IND,
      GOREMAL.GOREMAL_EMAIL_ADDRESS as SIRDPCL_INSTR_EMAIL,
      CASE
        WHEN SIRDPCL_DEPT_CODE IS NULL THEN F_GET_DESC_FNC('STVDEPT', SCBCRSE_DEPT_CODE, 30)
          ELSE F_GET_DESC_FNC('STVDEPT', SIRDPCL.SIRDPCL_DEPT_CODE, 30)
            END as SIRDPCL_DEPT_DESC,
      f_format_name(SIRDPCL.SIRDPCL_PIDM, 'LF30') as SIRDPCL_INSTR_NAME,
      SSBSECT_TERM_CODE,
      SSBSECT_CRN,
      SSBSECT_PTRM_CODE,
      SSBSECT_SUBJ_CODE,
      SSBSECT_CRSE_NUMB,
      SSBSECT_SEQ_NUMB,
      SSBSECT_SSTS_CODE,
      SSBSECT_SCHD_CODE,
      SSBSECT_CAMP_CODE,
      SSBSECT_CREDIT_HRS,
      SSBSECT_BILL_HRS,
      SSBSECT_GMOD_CODE,
      SSBSECT_REG_ONEUP,
      SSBSECT_PRIOR_ENRL,
      SSBSECT_PROJ_ENRL,
      SSBSECT_MAX_ENRL,
      SSBSECT_ENRL,
      SSBSECT_SEATS_AVAIL,
      SSBSECT_TOT_CREDIT_HRS,
      SSBSECT_CENSUS_ENRL,
      SSBSECT_CENSUS_ENRL_DATE,
      SSBSECT_ACTIVITY_DATE,
      SSBSECT_PTRM_START_DATE,
      SSBSECT_PTRM_END_DATE,
      SSBSECT_PTRM_WEEKS,
      SSBSECT_WAIT_CAPACITY,
      SSBSECT_WAIT_COUNT,
      SSBSECT_WAIT_AVAIL,
      SSBSECT_INSM_CODE,
      SSBSECT_SURROGATE_ID,
      SSBSECT_VERSION,
      SSBSECT_SICAS_CAMP_COURSE_ID,
      SSBSECT_SICAS_CAMP_SECTION_ID,
      SCBCRSE_SUBJ_CODE,
      SCBCRSE_CRSE_NUMB,
      SCBCRSE_EFF_TERM,
      SCBCRSE_COLL_CODE,
      SCBCRSE_DIVS_CODE,
      SCBCRSE_DEPT_CODE,
      SCBCRSE_CSTA_CODE,
      SCBCRSE_TITLE,
      SCBCRSE_CIPC_CODE,
      SCBCRSE_CREDIT_HR_IND,
      SCBCRSE_CREDIT_HR_LOW,
      SCBCRSE_CREDIT_HR_HIGH,
      SCBCRSE_LEC_HR_IND,
      SCBCRSE_LEC_HR_LOW,
      SCBCRSE_LEC_HR_HIGH,
      SCBCRSE_BILL_HR_IND,
      SCBCRSE_BILL_HR_LOW,
      SCBCRSE_BILL_HR_HIGH,
      SCBCRSE_ACTIVITY_DATE,
      SCBCRSE_CONT_HR_LOW,
      SCBCRSE_CONT_HR_IND,
      SCBCRSE_CONT_HR_HIGH,
      SCBCRSE_REPS_CODE,
      SCBCRSE_MAX_RPT_UNITS,
      SCBCRSE_SURROGATE_ID,
      SCBCRSE_VERSION,
      SCBCRSE_VPDI_CODE,
      SCBCRSE_SICAS_SUNY_ID,
      SSRMEET_TERM_CODE,
      SSRMEET_CRN,
      SSRMEET_DAYS_CODE,
      SSRMEET_DAY_NUMBER,
      SSRMEET_BEGIN_TIME,
      SSRMEET_END_TIME,
      SSRMEET_BLDG_CODE,
      SSRMEET_ROOM_CODE,
      SSRMEET_ACTIVITY_DATE,
      SSRMEET_START_DATE,
      SSRMEET_END_DATE,
      SSRMEET_SUN_DAY,
      SSRMEET_MON_DAY,
      SSRMEET_TUE_DAY,
      SSRMEET_WED_DAY,
      SSRMEET_THU_DAY,
      SSRMEET_FRI_DAY,
      SSRMEET_SAT_DAY,
      SSRMEET_SCHD_CODE,
      SSRMEET_CREDIT_HR_SESS,
      SSRMEET_MEET_NO,
      SSRMEET_HRS_WEEK,
      SSRMEET_MTYP_CODE,
      SSRMEET_SURROGATE_ID,
      SSRMEET_VERSION,
      SSBSECT_SSTS_DESC,
      SCBCRSE_CSTA_DESC,
      SCBCRSE_REPS_DESC

  FROM
      SIRASGN SIRASGN

      LEFT OUTER JOIN SSASECT SSBSECT ON SSBSECT.SSBSECT_TERM_CODE = SIRASGN.SIRASGN_TERM_CODE
           AND SSBSECT.SSBSECT_CRN = SIRASGN.SIRASGN_CRN

      LEFT OUTER JOIN SIRDPCL SIRDPCL ON SIRDPCL.SIRDPCL_PIDM = SIRASGN.SIRASGN_PIDM
           AND SIRDPCL.SIRDPCL_SURROGATE_ID = (SELECT MAX(SIRDPCL_SURROGATE_ID)
                                              FROM    SIRDPCL SIRDPCL1
                                              WHERE   SIRDPCL1.SIRDPCL_PIDM = SIRDPCL.SIRDPCL_PIDM)

      LEFT OUTER JOIN GOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SIRDPCL_PIDM
           AND GOREMAL.GOREMAL_EMAL_CODE = 'ESF'
           AND GOREMAL.GOREMAL_STATUS_IND = 'A'
           AND GOREMAL.GOREMAL_PREFERRED_IND = 'Y'

  WHERE
      SIRASGN_PRIMARY_IND = 'Y'
  ),

SSAMEET as
(
  SELECT
      SIRASGN.SCBCRSE_TITLE,
      SIRASGN.SSBSECT_TERM_CODE,
      SIRASGN.SSBSECT_CRN,
      SIRASGN.SSBSECT_PTRM_CODE,
      SIRASGN.SSBSECT_SUBJ_CODE,
      SIRASGN.SSBSECT_CRSE_NUMB,
      SIRASGN.SSBSECT_SEQ_NUMB,
      SIRASGN.SSBSECT_SICAS_CAMP_COURSE_ID,
      SIRASGN.SSBSECT_SCHD_CODE,
      SIRASGN.SSBSECT_CAMP_CODE,
      SIRASGN.SSBSECT_CREDIT_HRS,
      SIRASGN.SSBSECT_BILL_HRS,
      SIRASGN.SSBSECT_GMOD_CODE,
      SIRASGN.SSBSECT_REG_ONEUP,
      SIRASGN.SSBSECT_PRIOR_ENRL,
      SIRASGN.SSBSECT_PROJ_ENRL,
      SIRASGN.SSBSECT_MAX_ENRL,
      SIRASGN.SSBSECT_ENRL,
      SIRASGN.SSBSECT_SEATS_AVAIL,
      SIRASGN.SSBSECT_TOT_CREDIT_HRS,
      SIRASGN.SSBSECT_CENSUS_ENRL,
      SIRASGN.SSBSECT_CENSUS_ENRL_DATE,
      SIRASGN.SSBSECT_ACTIVITY_DATE,
      SIRASGN.SSBSECT_PTRM_START_DATE,
      SIRASGN.SSBSECT_PTRM_END_DATE,
      SIRASGN.SSBSECT_PTRM_WEEKS,
      SIRASGN.SSBSECT_WAIT_CAPACITY,
      SIRASGN.SSBSECT_WAIT_COUNT,
      SIRASGN.SSBSECT_WAIT_AVAIL,
      SIRASGN.SSBSECT_SICAS_CAMP_SECTION_ID,
      SSRMEET.SSRMEET_TERM_CODE,
      SSRMEET.SSRMEET_CRN,
      SSRMEET.SSRMEET_BEGIN_TIME,
      SSRMEET.SSRMEET_END_TIME,
      SSRMEET.SSRMEET_BLDG_CODE,
      SSRMEET.SSRMEET_ROOM_CODE,
      SSRMEET.SSRMEET_START_DATE,
      SSRMEET.SSRMEET_END_DATE,
      SSRMEET.SSRMEET_MON_DAY,
      SSRMEET.SSRMEET_TUE_DAY,
      SSRMEET.SSRMEET_WED_DAY,
      SSRMEET.SSRMEET_THU_DAY,
      SSRMEET.SSRMEET_FRI_DAY,
      SSRMEET.SSRMEET_SAT_DAY,
      SSRMEET.SSRMEET_CREDIT_HR_SESS,
      SSRMEET.SSRMEET_MEET_NO,
      SSRMEET.SSRMEET_HRS_WEEK,
      SIRASGN.SIRDPCL_INSTR_NAME,
      SIRASGN.SIRDPCL_DEPT_DESC

  FROM
      SSRMEET SSRMEET

      LEFT OUTER JOIN SIRASGQ SIRASGN ON SIRASGN.SIRASGN_TERM_CODE = SSRMEET.SSRMEET_TERM_CODE
           AND SIRASGN.SIRASGN_CRN = SSRMEET.SSRMEET_CRN
           AND SIRASGN.SIRASGN_PRIMARY_IND = 'Y'

  WHERE
      SSRMEET.SSRMEET_TERM_CODE = :select_term_code.STVTERM_CODE

  ORDER BY
      SSBSECT_SICAS_CAMP_SECTION_ID
  ),

-- LISTS
PERSONS_DEMO_LIST as
(
  SELECT
      CASE
        WHEN SPBPERS_SEX IS NULL THEN 0
          ELSE 1
            END as SEX_Measure,
      CASE
        WHEN GORRACE_RACE_CDE IS NULL THEN 0
          ELSE 1
            END as RACE_Measure,
      CASE
        WHEN SPBPERS_ETHN_CDE IS NULL THEN 0
          ELSE 1
            END as ETHN_Measure,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE

  WHERE
      SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
  ),

PERSONS_ADRTELE as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SPRADDR_PIDM,
      SPRADDR_ATYP_CODE,
      SPRADDR_ATYP_DESC,
      SPRADDR_FROM_DATE,
      SPRADDR_TO_DATE,
      SPRADDR_STREET_LINE1,
      SPRADDR_STREET_LINE2,
      SPRADDR_STREET_LINE3,
      SPRADDR_CITY,
      SPRADDR_STAT_CODE,
      SPRADDR_ZIP,
      SPRTELE_PIDM,
      SPRTELE_TELE_CODE,
      SPRTELE_TELE_DESC,
      SPRTELE_PHONE_AREA,
      SPRTELE_PHONE_NUMBER,
      SPREMRG_PIDM,
      SPREMRG_LAST_NAME,
      SPREMRG_FIRST_NAME,
      SPREMRG_MI,
      SPREMRG_RELT_CODE,
      SPREMRG_RELT_DESC,
      SPREMRG_PRIORITY,
      SPREMRG_STREET_LINE1,
      SPREMRG_STREET_LINE2,
      SPREMRG_STREET_LINE3,
      SPREMRG_CITY,
      SPREMRG_STAT_CODE,
      SPREMRG_NATN_CODE,
      SPREMRG_ZIP,
      SPREMRG_PHONE_AREA,
      SPREMRG_PHONE_NUMBER,
      SPREMRG_PHONE_EXT,
      SPREMRG_ACTIVITY_DATE,
      SPREMRG_ATYP_CODE,
      SPREMRG_HOUSE_NUMBER

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN TUIADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN_PIDM
            -- AND SPRADDR.SPRADDR_ATYP_CODE = '&ATYP'
      LEFT OUTER JOIN SPATELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPAEMRG SPREMRG ON SPREMRG.SPREMRG_PIDM = SPRIDEN_PIDM

  WHERE
      (SPREMRG_PRIORITY <= 1 OR SPREMRG_PRIORITY IS NULL)
  ),

STUDENT_DEMO_LIST as
(
  SELECT
      CASE
        WHEN SPBPERS_SEX IS NULL THEN 0
          ELSE 1
            END as SEX_Measure,
      CASE
        WHEN GORRACE_RACE_CDE IS NULL THEN 0
          ELSE 1
            END as RACE_Measure,
      CASE
        WHEN SPBPERS_ETHN_CDE IS NULL THEN 0
          ELSE 1
            END as ETHN_Measure,
      CASE
        WHEN SGBSTDN_MAJR_CODE_1 IS NULL THEN 0
          ELSE 1
            END as POS_Measure,
      CASE
        WHEN SGBSTDN_DEGC_CODE_1 IS NULL THEN 0
          ELSE 1
            END as DEGC_Measure,
      CASE
        WHEN SGBSTDN_STYP_CODE IS NULL THEN 0
          ELSE 1
            END as STYP_Measure,
      CASE
        WHEN SGBSTDN_LEVL_CODE IS NULL THEN 0
          ELSE 1
            END as LEVL_Measure,
      CASE
        WHEN SGBSTDN_CLAS_CODE IS NULL THEN 0
          ELSE 1
            END as CLAS_Measure,
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SFRTHST_TMST_CODE,
      SFRTHST_TMST_DESC,
      SGBSTDN_TERM_CODE_EFF,
      SGBSTDN_STST_CODE,
      SGBSTDN_STYP_CODE,
      SGBSTDN_LEVL_CODE,
      SGBSTDN_CLAS_CODE,
      SGBSTDN_DEPT_CODE,
      SGBSTDN_MAJR_CODE_1,
      SGBSTDN_MAJR_CODE_MINR_1,
      SGBSTDN_MAJR_CODE_MINR_1_2,
      SGBSTDN_MAJR_CODE_CONC_1,
      SGBSTDN_DEGC_CODE_1,
      SGBSTDN_RESD_CODE,
      SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN_TERM_EFF_DESC,
      SGBSTDN_STYP_DESC,
      SGBSTDN_LEVL_DESC,
      SGBSTDN_CLAS_DESC,
      SGBSTDN_DEPT_DESC,
      SGBSTDN_MAJR_DESC,
      SGBSTDN_MINR_1_DESC,
      SGBSTDN_MINR_1_2_DESC,
      SGBSTDN_CONC_DESC,
      SGBSTDN_DEGC_DESC,
      SGBSTDN_RESD_DESC,
      STVCLAS_SURROGATE_ID

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SGASTDN SGBSTDN ON SGBSTDN.SGBSTDN_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE

  WHERE
      SGBSTDN_TERM_CODE_EFF = FY_SGBSTDN_EFF_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
  ),

STUDENT_ADRTELE as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPRIDEN_LEGAL_NAME,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      SPBPERS_PREF_FIRST_NAME,
      SPBPERS_AGE,
      SPBPERS_SEX,
      GORRACE_RACE_CDE,
      GORRACE_DESC,
      SPBPERS_ETHN_CDE,
      SPBPERS_ETHN_DESC,
      SPBPERS_SICAS_HISP_ORIGIN,
      SPBPERS_CITZ_CODE,
      SPBPERS_CITZ_COUNTRY,
      GOBINTL_NATN_CODE_BIRTH,
      GOBINTL_BIRTH_NATN,
      GOBTPAC_EXTERNAL_USER,
      GORADID_ADDITIONAL_ID,
      GOREMAL_EMAIL_ADDRESS,
      GOREMAL_EMAL_CODE,
      SPRADDR_PIDM,
      SPRADDR_ATYP_CODE,
      SPRADDR_ATYP_DESC,
      SPRADDR_FROM_DATE,
      SPRADDR_TO_DATE,
      SPRADDR_STREET_LINE1,
      SPRADDR_STREET_LINE2,
      SPRADDR_STREET_LINE3,
      SPRADDR_CITY,
      SPRADDR_STAT_CODE,
      SPRADDR_ZIP,
      SPRTELE_PIDM,
      SPRTELE_TELE_CODE,
      SPRTELE_TELE_DESC,
      SPRTELE_PHONE_AREA,
      SPRTELE_PHONE_NUMBER,
      SPREMRG_PIDM,
      SPREMRG_LAST_NAME,
      SPREMRG_FIRST_NAME,
      SPREMRG_MI,
      SPREMRG_RELT_CODE,
      SPREMRG_RELT_DESC,
      SPREMRG_PRIORITY,
      SPREMRG_STREET_LINE1,
      SPREMRG_STREET_LINE2,
      SPREMRG_STREET_LINE3,
      SPREMRG_CITY,
      SPREMRG_STAT_CODE,
      SPREMRG_NATN_CODE,
      SPREMRG_ZIP,
      SPREMRG_PHONE_AREA,
      SPREMRG_PHONE_NUMBER,
      SPREMRG_PHONE_EXT,
      SPREMRG_ACTIVITY_DATE,
      SPREMRG_ATYP_CODE,
      SPREMRG_HOUSE_NUMBER

  FROM
      SPAIDEN SPRIDEN

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN GOARACE GORPRAC ON GORPRAC.GORPRAC_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SOREMAL GOREMAL ON GOREMAL.GOREMAL_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN TUIADDR SPRADDR ON SPRADDR.SPRADDR_PIDM = SPRIDEN_PIDM
            -- AND SPRADDR.SPRADDR_ATYP_CODE = '&ATYP'
      LEFT OUTER JOIN SPATELE SPRTELE ON SPRTELE.SPRTELE_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SPAEMRG SPREMRG ON SPREMRG.SPREMRG_PIDM = SPRIDEN_PIDM

  WHERE
      (SPREMRG_PRIORITY <= 1 OR SPREMRG_PRIORITY IS NULL)
  ),

STUDENT_ADMIN_LIST as
(
  SELECT
      SPRIDEN_PIDM,
      SPRIDEN_ID,
      SPRIDEN_LAST_NAME,
      SPRIDEN_FIRST_NAME,
      SPRIDEN_MI,
      SPBPERS_SEX,
      GORADID_ADDITIONAL_ID,
      GORRACE_DESC,
      SPBPERS_ETHN_DESC,
      SGBSTDN_STST_CODE,
      SGBSTDN_CLAS_CODE,
      SGBSTDN_DEGC_CODE_1,
      SGBSTDN_MAJR_DESC,
      SGBSTDN_LEVL_CODE,
      SGBSTDN_STYP_CODE,
      SGBSTDN_STYP_DESC,
      SGBSTDN_DEPT_DESC,
      SGBSTDN_EXP_GRAD_DATE,
      SFRTHST_TMST_CODE,
      SFRTHST_TMST_DESC,
      SGBSTDN_TERM_CODE_EFF,
      SGBSTDN_TERM_EFF_DESC,
      SGBSTDN_RESD_CODE,
      SGBSTDN_RESD_DESC,
      SPBPERS_CITZ_COUNTRY,
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME,
      SPRIDEN_SEARCH_MI,
      STVCLAS_SURROGATE_ID

  FROM
      STUDENT_DEMO_LIST A1
  ),

STUDENT_CLASS_LIST as
(
  SELECT
      A2.SPRIDEN_PIDM,
      A2.SPRIDEN_ID,
      A2.SPRIDEN_LAST_NAME,
      A2.SPRIDEN_FIRST_NAME,
      A2.SPRIDEN_MI,
      A2.SPRIDEN_LEGAL_NAME,
      A2.SPRIDEN_SEARCH_LAST_NAME,
      A2.SPRIDEN_SEARCH_FIRST_NAME,
      A2.SPRIDEN_SEARCH_MI,
      A2.SPBPERS_PREF_FIRST_NAME,
      A2.SPBPERS_AGE,
      A2.SPBPERS_SEX,
      A2.GORRACE_RACE_CDE,
      A2.GORRACE_DESC,
      A2.SPBPERS_ETHN_CDE,
      A2.SPBPERS_ETHN_DESC,
      A2.SPBPERS_SICAS_HISP_ORIGIN,
      A2.SPBPERS_CITZ_CODE,
      A2.SPBPERS_CITZ_COUNTRY,
      A2.GOBINTL_NATN_CODE_BIRTH,
      A2.GOBINTL_BIRTH_NATN,
      A2.GOBTPAC_EXTERNAL_USER,
      A2.GORADID_ADDITIONAL_ID,
      A2.GOREMAL_EMAIL_ADDRESS,
      A2.GOREMAL_EMAL_CODE,
      A2.SFRTHST_TMST_CODE,
      A2.SFRTHST_TMST_DESC,
      A2.SGBSTDN_TERM_CODE_EFF,
      A2.SGBSTDN_STST_CODE,
      A2.SGBSTDN_STYP_CODE,
      A2.SGBSTDN_LEVL_CODE,
      A2.SGBSTDN_CLAS_CODE,
      A2.SGBSTDN_DEPT_CODE,
      A2.SGBSTDN_MAJR_CODE_1,
      A2.SGBSTDN_MAJR_CODE_MINR_1,
      A2.SGBSTDN_MAJR_CODE_MINR_1_2,
      A2.SGBSTDN_MAJR_CODE_CONC_1,
      A2.SGBSTDN_DEGC_CODE_1,
      A2.SGBSTDN_RESD_CODE,
      A2.SGBSTDN_EXP_GRAD_DATE,
      A2.SGBSTDN_STYP_DESC,
      A2.SGBSTDN_LEVL_DESC,
      A2.SGBSTDN_CLAS_DESC,
      A2.SGBSTDN_DEPT_DESC,
      A2.SGBSTDN_MAJR_DESC,
      A2.SGBSTDN_MINR_1_DESC,
      A2.SGBSTDN_MINR_1_2_DESC,
      A2.SGBSTDN_CONC_DESC,
      A2.SGBSTDN_DEGC_DESC,
      A2.SGBSTDN_RESD_DESC,
      A2.STVCLAS_SURROGATE_ID,
      S1.SFRSTCR_TERM_CODE,
      S1.SFRSTCR_PIDM,
      S1.SFRSTCR_CRN,
      S1.SFRSTCR_CLASS_SORT_KEY,
      S1.SFRSTCR_REG_SEQ,
      S1.SFRSTCR_PTRM_CODE,
      S1.SFRSTCR_RSTS_CODE,
      S1.SFRSTCR_BILL_HR,
      S1.SFRSTCR_WAIV_HR,
      S1.SFRSTCR_CREDIT_HR,
      S1.SFRSTCR_BILL_HR_HOLD,
      S1.SFRSTCR_CREDIT_HR_HOLD,
      S1.SFRSTCR_GMOD_CODE,
      S1.SFRSTCR_GRDE_CODE,
      S1.SFRSTCR_GRDE_DATE,
      S1.SFRSTCR_ADD_DATE,
      S1.SFRSTCR_LEVL_CODE,
      S1.SFRSTCR_CAMP_CODE,
      S1.SFRSTCA_TERM_CODE,
      S1.SFRSTCA_PIDM,
      S1.SFRSTCA_CRN,
      S1.SFRSTCA_SEQ_NUMBER,
      S1.SFRSTCA_LEVL_CODE,
      S1.SFRSTCA_CAMP_CODE,
      S1.SFRSTCA_ADD_DATE,
      S1.SFRSTCA_ACTIVITY_DATE,
      S1.SFRSTCA_RSTS_CODE,
      S1.SFRSTCA_RSTS_DATE,
      S1.SFRSTCA_ERROR_FLAG,
      S1.SFRSTCA_MESSAGE,
      S1.SFRSTCA_BILL_HR,
      S1.SFRSTCA_CREDIT_HR,
      S1.SFRSTCA_GMOD_CODE,
      S1.SFRSTCA_USER,
      S1.SFRSTCA_GCMT_CODE,
      S1.SFRSTCA_SOURCE_CDE,
      S1.SFRSTCA_DATA_ORIGIN,
      S1.SFRSTCA_ATTEMPT_HR,
      S1.SFRSTCA_RMSG_CDE,
      S1.SFRSTCA_STSP_KEY_SEQUENCE,
      S1.SFRSTCA_BRDH_SEQ_NUM,
      S1.SFRSTCA_BLCK_CODE,
      S1.SFRSTCA_STRH_SEQNO,
      S1.SFRSTCA_STRD_SEQNO,
      S1.SFRSTCA_SURROGATE_ID,
      S1.SFRSTCA_VERSION,
      S1.SFRSTCA_USER_ID,
      S1.SFRSTCA_VPDI_CODE,
      S1.SFRSTCA_SESSIONID,
      S1.SFRSTCA_CURRENT_TIME,
      S1.SFRSTCA_ENRL,
      S1.SFRSTCA_SEATS_AVAIL,
      S1.SHRTCKN_PIDM,
      S1.SHRTCKN_TERM_CODE,
      S1.SHRTCKN_SEQ_NO,
      S1.SHRTCKN_CRN,
      S1.SHRTCKN_SUBJ_CODE,
      S1.SHRTCKN_CRSE_NUMB,
      S1.SHRTCKN_COLL_CODE,
      S1.SHRTCKN_CAMP_CODE,
      S1.SHRTCKN_ACTIVITY_DATE,
      S1.SHRTCKN_SEQ_NUMB,
      S1.SHRTCKN_SURROGATE_ID,
      S1.SHRTCKG_PIDM,
      S1.SHRTCKG_TERM_CODE,
      S1.SHRTCKG_TCKN_SEQ_NO,
      S1.SHRTCKG_SEQ_NO,
      S1.SHRTCKG_FINAL_GRDE_SEQ_NO,
      S1.SHRTCKG_GRDE_CODE_FINAL,
      S1.SHRTCKG_GMOD_CODE,
      S1.SHRTCKG_CREDIT_HOURS,
      S1.SHRTCKG_GCHG_CODE,
      S1.SHRTCKG_FINAL_GRDE_CHG_DATE,
      S1.SHRTCKG_HOURS_ATTEMPTED,
      S1.SHRTCKG_GRDE_CODE_INCMP_FINAL,
      S1.SHRTCKG_SURROGATE_ID,
      S1.SHRTCKG_VERSION,
      S1.SHRTCKL_PRIMARY_LEVL_IND,
      S1.SHRGRDE_CODE,
      S1.SHRGRDE_LEVL_CODE,
      S1.SHRGRDE_QUALITY_POINTS,
      S1.SHRGRDE_ATTEMPTED_IND,
      S1.SHRGRDE_COMPLETED_IND,
      S1.SHRGRDE_PASSED_IND,
      S1.SHRGRDE_GPA_IND,
      S1.SHRGRDE_SURROGATE_ID,
      S1.SHRGRDE_VERSION,
      S1.SHRGRDE_NUMERIC_VALUE,
      S1.SHRTCKG_GCHG_DESC,
      S1.COURSE_COMPLETE_IND,
      S1.COURSE_PASSED_IND,
      S1.COURSE_GPA_IND,
      S1.SFRSTCR_STUDENT_NAME,
      S2.SIRASGN_TERM_CODE,
      S2.SIRASGN_CRN,
      S2.SIRASGN_PIDM,
      S2.SIRDPCL_PIDM,
      S2.SIRDPCL_TERM_CODE_EFF,
      S2.SIRDPCL_COLL_CODE,
      S2.SIRDPCL_DEPT_CODE,
      S2.SIRASGN_PRIMARY_IND,
      S2.SIRDPCL_INSTR_EMAIL,
      S2.SIRDPCL_DEPT_DESC,
      S2.SIRDPCL_INSTR_NAME,
      S2.SSBSECT_TERM_CODE,
      S2.SSBSECT_CRN,
      S2.SSBSECT_PTRM_CODE,
      S2.SSBSECT_SUBJ_CODE,
      S2.SSBSECT_CRSE_NUMB,
      S2.SSBSECT_SEQ_NUMB,
      S2.SSBSECT_SSTS_CODE,
      S2.SSBSECT_SCHD_CODE,
      S2.SSBSECT_CAMP_CODE,
      S2.SSBSECT_CREDIT_HRS,
      S2.SSBSECT_BILL_HRS,
      S2.SSBSECT_GMOD_CODE,
      S2.SSBSECT_REG_ONEUP,
      S2.SSBSECT_PRIOR_ENRL,
      S2.SSBSECT_PROJ_ENRL,
      S2.SSBSECT_MAX_ENRL,
      S2.SSBSECT_ENRL,
      S2.SSBSECT_SEATS_AVAIL,
      S2.SSBSECT_TOT_CREDIT_HRS,
      S2.SSBSECT_CENSUS_ENRL,
      S2.SSBSECT_CENSUS_ENRL_DATE,
      S2.SSBSECT_ACTIVITY_DATE,
      S2.SSBSECT_PTRM_START_DATE,
      S2.SSBSECT_PTRM_END_DATE,
      S2.SSBSECT_PTRM_WEEKS,
      S2.SSBSECT_WAIT_CAPACITY,
      S2.SSBSECT_WAIT_COUNT,
      S2.SSBSECT_WAIT_AVAIL,
      S2.SSBSECT_INSM_CODE,
      S2.SSBSECT_SURROGATE_ID,
      S2.SSBSECT_VERSION,
      S2.SSBSECT_SICAS_CAMP_COURSE_ID,
      S2.SSBSECT_SICAS_CAMP_SECTION_ID,
      S2.SCBCRSE_SUBJ_CODE,
      S2.SCBCRSE_CRSE_NUMB,
      S2.SCBCRSE_EFF_TERM,
      S2.SCBCRSE_COLL_CODE,
      S2.SCBCRSE_DIVS_CODE,
      S2.SCBCRSE_DEPT_CODE,
      S2.SCBCRSE_CSTA_CODE,
      S2.SCBCRSE_TITLE,
      S2.SCBCRSE_CIPC_CODE,
      S2.SCBCRSE_CREDIT_HR_IND,
      S2.SCBCRSE_CREDIT_HR_LOW,
      S2.SCBCRSE_CREDIT_HR_HIGH,
      S2.SCBCRSE_LEC_HR_IND,
      S2.SCBCRSE_LEC_HR_LOW,
      S2.SCBCRSE_LEC_HR_HIGH,
      S2.SCBCRSE_BILL_HR_IND,
      S2.SCBCRSE_BILL_HR_LOW,
      S2.SCBCRSE_BILL_HR_HIGH,
      S2.SCBCRSE_ACTIVITY_DATE,
      S2.SCBCRSE_CONT_HR_LOW,
      S2.SCBCRSE_CONT_HR_IND,
      S2.SCBCRSE_CONT_HR_HIGH,
      S2.SCBCRSE_REPS_CODE,
      S2.SCBCRSE_MAX_RPT_UNITS,
      S2.SCBCRSE_SURROGATE_ID,
      S2.SCBCRSE_VERSION,
      S2.SCBCRSE_VPDI_CODE,
      S2.SCBCRSE_SICAS_SUNY_ID,
      S2.SSRMEET_TERM_CODE,
      S2.SSRMEET_CRN,
      S2.SSRMEET_DAYS_CODE,
      S2.SSRMEET_DAY_NUMBER,
      S2.SSRMEET_BEGIN_TIME,
      S2.SSRMEET_END_TIME,
      S2.SSRMEET_BLDG_CODE,
      S2.SSRMEET_ROOM_CODE,
      S2.SSRMEET_ACTIVITY_DATE,
      S2.SSRMEET_START_DATE,
      S2.SSRMEET_END_DATE,
      S2.SSRMEET_SUN_DAY,
      S2.SSRMEET_MON_DAY,
      S2.SSRMEET_TUE_DAY,
      S2.SSRMEET_WED_DAY,
      S2.SSRMEET_THU_DAY,
      S2.SSRMEET_FRI_DAY,
      S2.SSRMEET_SAT_DAY,
      S2.SSRMEET_SCHD_CODE,
      S2.SSRMEET_CREDIT_HR_SESS,
      S2.SSRMEET_MEET_NO,
      S2.SSRMEET_HRS_WEEK,
      S2.SSRMEET_MTYP_CODE,
      S2.SSRMEET_SURROGATE_ID,
      S2.SSRMEET_VERSION,
      S2.SSBSECT_SSTS_DESC,
      S2.SCBCRSE_CSTA_DESC,
      S2.SCBCRSE_REPS_DESC

  FROM
      STUDENT_DEMO_LIST A2

      LEFT OUTER JOIN SHATCKN S1 ON SFRSTCR_PIDM = SPRIDEN_PIDM

      LEFT OUTER JOIN SIRASGQ S2 ON SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE
           AND SSBSECT_CRN = SFRSTCR_CRN
  ),

STUDENT_GRADE_LIST as
(
  SELECT
      A2.SPRIDEN_PIDM,
      A2.SPRIDEN_ID,
      A2.SPRIDEN_LAST_NAME,
      A2.SPRIDEN_FIRST_NAME,
      A2.SPRIDEN_MI,
      A2.SPRIDEN_LEGAL_NAME,
      A2.SPRIDEN_SEARCH_LAST_NAME,
      A2.SPRIDEN_SEARCH_FIRST_NAME,
      A2.SPRIDEN_SEARCH_MI,
      A2.SPBPERS_PREF_FIRST_NAME,
      A2.SPBPERS_AGE,
      A2.SPBPERS_SEX,
      A2.GORRACE_RACE_CDE,
      A2.GORRACE_DESC,
      A2.SPBPERS_ETHN_CDE,
      A2.SPBPERS_ETHN_DESC,
      A2.SPBPERS_SICAS_HISP_ORIGIN,
      A2.SPBPERS_CITZ_CODE,
      A2.SPBPERS_CITZ_COUNTRY,
      A2.GOBINTL_NATN_CODE_BIRTH,
      A2.GOBINTL_BIRTH_NATN,
      A2.GOBTPAC_EXTERNAL_USER,
      A2.GORADID_ADDITIONAL_ID,
      A2.GOREMAL_EMAIL_ADDRESS,
      A2.GOREMAL_EMAL_CODE,
      A2.SFRTHST_TMST_CODE,
      A2.SFRTHST_TMST_DESC,
      A2.SGBSTDN_TERM_CODE_EFF,
      A2.SGBSTDN_STST_CODE,
      A2.SGBSTDN_STYP_CODE,
      A2.SGBSTDN_LEVL_CODE,
      A2.SGBSTDN_CLAS_CODE,
      A2.SGBSTDN_DEPT_CODE,
      A2.SGBSTDN_MAJR_CODE_1,
      A2.SGBSTDN_MAJR_CODE_MINR_1,
      A2.SGBSTDN_MAJR_CODE_MINR_1_2,
      A2.SGBSTDN_MAJR_CODE_CONC_1,
      A2.SGBSTDN_DEGC_CODE_1,
      A2.SGBSTDN_RESD_CODE,
      A2.SGBSTDN_EXP_GRAD_DATE,
      A2.SGBSTDN_STYP_DESC,
      A2.SGBSTDN_LEVL_DESC,
      A2.SGBSTDN_CLAS_DESC,
      A2.SGBSTDN_DEPT_DESC,
      A2.SGBSTDN_MAJR_DESC,
      A2.SGBSTDN_MINR_1_DESC,
      A2.SGBSTDN_MINR_1_2_DESC,
      A2.SGBSTDN_CONC_DESC,
      A2.SGBSTDN_DEGC_DESC,
      A2.SGBSTDN_RESD_DESC,
      A2.STVCLAS_SURROGATE_ID,
      S1.SFRSTCR_TERM_CODE,
      S1.SFRSTCR_PIDM,
      S1.SFRSTCR_CRN,
      S1.SFRSTCR_CLASS_SORT_KEY,
      S1.SFRSTCR_REG_SEQ,
      S1.SFRSTCR_PTRM_CODE,
      S1.SFRSTCR_RSTS_CODE,
      S1.SFRSTCR_BILL_HR,
      S1.SFRSTCR_WAIV_HR,
      S1.SFRSTCR_CREDIT_HR,
      S1.SFRSTCR_BILL_HR_HOLD,
      S1.SFRSTCR_CREDIT_HR_HOLD,
      S1.SFRSTCR_GMOD_CODE,
      S1.SFRSTCR_GRDE_CODE,
      S1.SFRSTCR_GRDE_DATE,
      S1.SFRSTCR_ADD_DATE,
      S1.SFRSTCR_LEVL_CODE,
      S1.SFRSTCR_CAMP_CODE,
      S1.SFRSTCA_TERM_CODE,
      S1.SFRSTCA_PIDM,
      S1.SFRSTCA_CRN,
      S1.SFRSTCA_SEQ_NUMBER,
      S1.SFRSTCA_LEVL_CODE,
      S1.SFRSTCA_CAMP_CODE,
      S1.SFRSTCA_ADD_DATE,
      S1.SFRSTCA_ACTIVITY_DATE,
      S1.SFRSTCA_RSTS_CODE,
      S1.SFRSTCA_RSTS_DATE,
      S1.SFRSTCA_ERROR_FLAG,
      S1.SFRSTCA_MESSAGE,
      S1.SFRSTCA_BILL_HR,
      S1.SFRSTCA_CREDIT_HR,
      S1.SFRSTCA_GMOD_CODE,
      S1.SFRSTCA_USER,
      S1.SFRSTCA_GCMT_CODE,
      S1.SFRSTCA_SOURCE_CDE,
      S1.SFRSTCA_DATA_ORIGIN,
      S1.SFRSTCA_ATTEMPT_HR,
      S1.SFRSTCA_RMSG_CDE,
      S1.SFRSTCA_STSP_KEY_SEQUENCE,
      S1.SFRSTCA_BRDH_SEQ_NUM,
      S1.SFRSTCA_BLCK_CODE,
      S1.SFRSTCA_STRH_SEQNO,
      S1.SFRSTCA_STRD_SEQNO,
      S1.SFRSTCA_SURROGATE_ID,
      S1.SFRSTCA_VERSION,
      S1.SFRSTCA_USER_ID,
      S1.SFRSTCA_VPDI_CODE,
      S1.SFRSTCA_SESSIONID,
      S1.SFRSTCA_CURRENT_TIME,
      S1.SFRSTCA_ENRL,
      S1.SFRSTCA_SEATS_AVAIL,
      S1.SHRTCKN_PIDM,
      S1.SHRTCKN_TERM_CODE,
      S1.SHRTCKN_SEQ_NO,
      S1.SHRTCKN_CRN,
      S1.SHRTCKN_SUBJ_CODE,
      S1.SHRTCKN_CRSE_NUMB,
      S1.SHRTCKN_COLL_CODE,
      S1.SHRTCKN_CAMP_CODE,
      S1.SHRTCKN_ACTIVITY_DATE,
      S1.SHRTCKN_SEQ_NUMB,
      S1.SHRTCKN_SURROGATE_ID,
      S1.SHRTCKG_PIDM,
      S1.SHRTCKG_TERM_CODE,
      S1.SHRTCKG_TCKN_SEQ_NO,
      S1.SHRTCKG_SEQ_NO,
      S1.SHRTCKG_FINAL_GRDE_SEQ_NO,
      S1.SHRTCKG_GRDE_CODE_FINAL,
      S1.SHRTCKG_GMOD_CODE,
      S1.SHRTCKG_CREDIT_HOURS,
      S1.SHRTCKG_GCHG_CODE,
      S1.SHRTCKG_FINAL_GRDE_CHG_DATE,
      S1.SHRTCKG_HOURS_ATTEMPTED,
      S1.SHRTCKG_GRDE_CODE_INCMP_FINAL,
      S1.SHRTCKG_SURROGATE_ID,
      S1.SHRTCKG_VERSION,
      S1.SHRTCKL_PRIMARY_LEVL_IND,
      S1.SHRGRDE_CODE,
      S1.SHRGRDE_LEVL_CODE,
      S1.SHRGRDE_QUALITY_POINTS,
      S1.SHRGRDE_ATTEMPTED_IND,
      S1.SHRGRDE_COMPLETED_IND,
      S1.SHRGRDE_PASSED_IND,
      S1.SHRGRDE_GPA_IND,
      S2.SIRASGN_TERM_CODE,
      S2.SIRASGN_CRN,
      S2.SIRASGN_PIDM,
      S2.SIRDPCL_PIDM,
      S2.SIRDPCL_TERM_CODE_EFF,
      S2.SIRDPCL_COLL_CODE,
      S2.SIRDPCL_DEPT_CODE,
      S2.SIRASGN_PRIMARY_IND,
      S2.SIRDPCL_INSTR_EMAIL,
      S2.SIRDPCL_DEPT_DESC,
      S2.SIRDPCL_INSTR_NAME,
      S2.SSBSECT_TERM_CODE,
      S2.SSBSECT_CRN,
      S2.SSBSECT_PTRM_CODE,
      S2.SSBSECT_SUBJ_CODE,
      S2.SSBSECT_CRSE_NUMB,
      S2.SSBSECT_SEQ_NUMB,
      S2.SSBSECT_SSTS_CODE,
      S2.SSBSECT_SCHD_CODE,
      S2.SSBSECT_CAMP_CODE,
      S2.SSBSECT_CREDIT_HRS,
      S2.SSBSECT_BILL_HRS,
      S2.SSBSECT_GMOD_CODE,
      S2.SSBSECT_REG_ONEUP,
      S2.SSBSECT_PRIOR_ENRL,
      S2.SSBSECT_PROJ_ENRL,
      S2.SSBSECT_MAX_ENRL,
      S2.SSBSECT_ENRL,
      S2.SSBSECT_SEATS_AVAIL,
      S2.SSBSECT_TOT_CREDIT_HRS,
      S2.SSBSECT_CENSUS_ENRL,
      S2.SSBSECT_CENSUS_ENRL_DATE,
      S2.SSBSECT_ACTIVITY_DATE,
      S2.SSBSECT_PTRM_START_DATE,
      S2.SSBSECT_PTRM_END_DATE,
      S2.SSBSECT_PTRM_WEEKS,
      S2.SSBSECT_WAIT_CAPACITY,
      S2.SSBSECT_WAIT_COUNT,
      S2.SSBSECT_WAIT_AVAIL,
      S2.SSBSECT_INSM_CODE,
      S2.SSBSECT_SURROGATE_ID,
      S2.SSBSECT_VERSION,
      S2.SSBSECT_SICAS_CAMP_COURSE_ID,
      S2.SSBSECT_SICAS_CAMP_SECTION_ID,
      S2.SCBCRSE_SUBJ_CODE,
      S2.SCBCRSE_CRSE_NUMB,
      S2.SCBCRSE_EFF_TERM,
      S2.SCBCRSE_COLL_CODE,
      S2.SCBCRSE_DIVS_CODE,
      S2.SCBCRSE_DEPT_CODE,
      S2.SCBCRSE_CSTA_CODE,
      S2.SCBCRSE_TITLE,
      S2.SCBCRSE_CIPC_CODE,
      S2.SCBCRSE_CREDIT_HR_IND,
      S2.SCBCRSE_CREDIT_HR_LOW,
      S2.SCBCRSE_CREDIT_HR_HIGH,
      S2.SCBCRSE_LEC_HR_IND,
      S2.SCBCRSE_LEC_HR_LOW,
      S2.SCBCRSE_LEC_HR_HIGH,
      S2.SCBCRSE_BILL_HR_IND,
      S2.SCBCRSE_BILL_HR_LOW,
      S2.SCBCRSE_BILL_HR_HIGH,
      S2.SCBCRSE_ACTIVITY_DATE,
      S2.SCBCRSE_CONT_HR_LOW,
      S2.SCBCRSE_CONT_HR_IND,
      S2.SCBCRSE_CONT_HR_HIGH,
      S2.SCBCRSE_REPS_CODE,
      S2.SCBCRSE_MAX_RPT_UNITS,
      S2.SCBCRSE_SURROGATE_ID,
      S2.SCBCRSE_VERSION,
      S2.SCBCRSE_VPDI_CODE,
      S2.SCBCRSE_SICAS_SUNY_ID,
      S2.SSRMEET_TERM_CODE,
      S2.SSRMEET_CRN,
      S2.SSRMEET_DAYS_CODE,
      S2.SSRMEET_DAY_NUMBER,
      S2.SSRMEET_BEGIN_TIME,
      S2.SSRMEET_END_TIME,
      S2.SSRMEET_BLDG_CODE,
      S2.SSRMEET_ROOM_CODE,
      S2.SSRMEET_ACTIVITY_DATE,
      S2.SSRMEET_START_DATE,
      S2.SSRMEET_END_DATE,
      S2.SSRMEET_SUN_DAY,
      S2.SSRMEET_MON_DAY,
      S2.SSRMEET_TUE_DAY,
      S2.SSRMEET_WED_DAY,
      S2.SSRMEET_THU_DAY,
      S2.SSRMEET_FRI_DAY,
      S2.SSRMEET_SAT_DAY,
      S2.SSRMEET_SCHD_CODE,
      S2.SSRMEET_CREDIT_HR_SESS,
      S2.SSRMEET_MEET_NO,
      S2.SSRMEET_HRS_WEEK,
      S2.SSRMEET_MTYP_CODE,
      S2.SSRMEET_SURROGATE_ID,
      S2.SSRMEET_VERSION,
      S2.SSBSECT_SSTS_DESC,
      S2.SCBCRSE_CSTA_DESC,
      S2.SCBCRSE_REPS_DESC

  FROM
      STUDENT_DEMO_LIST A2

      LEFT OUTER JOIN SPAPERS SPBPERS ON SPBPERS.SPBPERS_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SHATCKN S1 ON SFRSTCR_PIDM = SPRIDEN_PIDM
      LEFT OUTER JOIN SIRASGQ S2 ON SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE
           AND SSBSECT_CRN = SFRSTCR_CRN
  )

SELECT --*
    STVTERM_DESC as Term,
    SSBSECT_SICAS_CAMP_COURSE_ID as  Course_Key,
    SSBSECT_SEQ_NUMB as Seq_No,
    SSBSECT_CRN as Ref_No,
    SSBSECT_CAMP_CODE as Campus,
    SCBCRSE_TITLE as Course_Title,
    SFRSTCR_CREDIT_HR as Credit_Hours,
    SGBSTDN_DEPT_CODE as Dept_Code,
    SPRIDEN_ID as BANNER_ID,
    SPRIDEN_LEGAL_NAME as Student_Name,
    GORADID_ADDITIONAL_ID as SUID,
    SGBSTDN_CLAS_CODE as Student_Class,
    SGBSTDN_MAJR_DESC as Program_of_Study,
    SGBSTDN_MAJR_CODE_MINR_1 as Major_Conc,
    SGBSTDN_MINR_1_DESC as Major_Conc_Desc,
    SHRTCKG_GRDE_CODE_FINAL as Final_Grade,
    SHRTCKN_ACTIVITY_DATE as Activity_Date,
    B.*

FROM
    STUDENT_CLASS_LIST B
    LEFT OUTER JOIN STVCLAS STVCLAS ON STVCLAS.STVCLAS_CODE = SGBSTDN_CLAS_CODE
    LEFT OUTER JOIN STVTERM STVTERM ON STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE

WHERE
    NULL IS NULL
    AND 'Y' = F_REGISTERED_THIS_TERM(SPRIDEN_PIDM, :select_term_code.STVTERM_CODE)
    AND SFRSTCR_RSTS_CODE IN ( 'RE', 'RW')
    --AND SSBSECT_GMOD_CODE = 'Y'
    -- AND SSBSECT_TOT_CREDIT_HRS > 0
    --$addfilter

ORDER BY
    --$begngorder
    SGBSTDN_DEPT_CODE,
    SGBSTDN_MAJR_CODE_1,
    SSBSECT_SICAS_CAMP_COURSE_ID,
    STVCLAS_CODE,
    SPRIDEN_SEARCH_LAST_NAME,
    SPRIDEN_SEARCH_FIRST_NAME
    --$endorder
