with SPAIDEN as (

    select
        SPRIDEN.SPRIDEN_ID,
        SPRIDEN.SPRIDEN_PIDM,
        SPRIDEN.SPRIDEN_LAST_NAME,
        SPRIDEN.SPRIDEN_FIRST_NAME,
        SPRIDEN.SPRIDEN_MI,
        SPRIDEN.SPRIDEN_NTYP_CODE,
        SPRIDEN.SPRIDEN_CHANGE_IND,
        SPRIDEN.SPRIDEN_SEARCH_LAST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_FIRST_NAME,
        SPRIDEN.SPRIDEN_SEARCH_MI,
        GORADID.GORADID_PIDM,
        GORADID.GORADID_ADDITIONAL_ID,
        GORADID.GORADID_ADID_CODE,
        f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') as SPRIDEN_LEGAL_NAME

    from
        SPRIDEN SPRIDEN

        left outer join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
            and GORADID.GORADID_ADID_CODE = 'SUID'

    where
        SPRIDEN.SPRIDEN_NTYP_CODE is null
        and SPRIDEN.SPRIDEN_CHANGE_IND is null
   ),

SOREMAL as (

    select
        GOREMAL.GOREMAL_PIDM as GOREMAL_PIDM,
        GOREMAL.GOREMAL_EMAL_CODE as GOREMAL_EMAL_CODE,
        GOREMAL.GOREMAL_EMAIL_ADDRESS as GOREMAL_EMAIL_ADDRESS,
        GOREMAL.GOREMAL_STATUS_IND as GOREMAL_STATUS_IND,
        GOREMAL.GOREMAL_PREFERRED_IND as GOREMAL_PREFFERED_IND,
        GOREMAL1.GOREMAL_EMAL_CODE as GOREMAL1_EMAL_CODE,
        GOREMAL1.GOREMAL_EMAIL_ADDRESS as GOREMAL_PERS_EMAIL_ADDRESS,
        GOREMAL1.GOREMAL_STATUS_IND as GOREMAL_PERS_STATUS_IND,
        GOREMAL1.GOREMAL_PREFERRED_IND as GOREMAL_PERS_PREFFERED_IND

    from
        GOREMAL GOREMAL

        left outer join GOREMAL GOREMAL1 on GOREMAL1.GOREMAL_PIDM = GOREMAL.GOREMAL_PIDM
             and GOREMAL1.GOREMAL_EMAL_CODE = 'PERS'
             and GOREMAL1.GOREMAL_STATUS_IND = 'A'
             and GOREMAL1.GOREMAL_SURROGATE_ID = (select max(GOREMAL_SURROGATE_ID)
                                            from GOREMAL GOREMALX
                                            where GOREMALX.GOREMAL_PIDM = GOREMAL1.GOREMAL_PIDM)

    where
        GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        and GOREMAL.GOREMAL_STATUS_IND = 'A'),

SPAPERS as (

    select
        SPBPERS.SPBPERS_PIDM as SPBPERS_PIDM,
        SPBPERS.SPBPERS_SSN as SPBPERS_SSN,
        SPBPERS.SPBPERS_BIRTH_DATE as SBPERS_BIRTH_DATE,
        SPBPERS.SPBPERS_SEX as SPBPERS_SEX,
        SPBPERS.SPBPERS_PREF_FIRST_NAME as SPBPERS_PREF_FIRST_NAME,
        SPBPERS.SPBPERS_CITZ_CODE as SPBPERS_CITZ_CODE,
        SPBPERS.SPBPERS_GNDR_CODE as SPBPERS_GNDR_CODE,
        GOBINTL.GOBINTL_PIDM as GOBINTL_PIDM,
        GORPRAC.GORPRAC_PIDM as GORPRAC_PIDM,
        GORRACE.GORRACE_RACE_CDE as GORRACE_RACE_CDE,
        GORRACE.GORRACE_DESC as GORRACE_DESC,
        case
            when SPBPERS.SPBPERS_CITZ_CODE = 'Y' then 'United States'
            else (select STVNATN_NATION
                 from STVNATN
                 where STVNATN_CODE = nvl(GOBINTL.GOBINTL_NATN_CODE_LEGAL, GOBINTL.GOBINTL_NATN_CODE_BIRTH))
            end as SPBPERS_CITZ_COUNTRY

   from
        SPBPERS SPBPERS

        left outer join GOBINTL GOBINTL on GOBINTL.GOBINTL_PIDM = SPBPERS.SPBPERS_PIDM
        left outer join GORPRAC GORPRAC on GORPRAC.GORPRAC_PIDM = SPBPERS.SPBPERS_PIDM
        left outer join GORRACE GORRACE on GORRACE.GORRACE_RACE_CDE = GORPRAC.GORPRAC_RACE_CDE
             ),
-- TUIADDR()
-- SPATELE()
-- SOREMAL()
SPAPERS as (

    select
        SPBPERS.SPBPERS_PIDM as SPBPERS_PIDM,
        SPBPERS.SPBPERS_SSN as SPBPERS_SSN,
        SPBPERS.SPBPERS_BIRTH_DATE as SBPERS_BIRTH_DATE,
        SPBPERS.SPBPERS_SEX as SPBPERS_SEX,
        SPBPERS.SPBPERS_PREF_FIRST_NAME as SPBPERS_PREF_FIRST_NAME,
        SPBPERS.SPBPERS_CITZ_CODE as SPBPERS_CITZ_CODE,
        SPBPERS.SPBPERS_GNDR_CODE as SPBPERS_GNDR_CODE

   from
        SPBPERS SPBPERS

             ),

SGASTDN as (

    select
        SGBSTDN.SGBSTDN_PIDM,
        SGBSTDN.SGBSTDN_TERM_CODE_EFF,
        SGBSTDN.SGBSTDN_STST_CODE,
        SGBSTDN.SGBSTDN_LEVL_CODE,
        SGBSTDN.SGBSTDN_STYP_CODE,
        SGBSTDN.SGBSTDN_TERM_CODE_MATRIC,
        SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
        SGBSTDN.SGBSTDN_DEGC_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1 as SGBSTDN_MINR_CODE_1,
        SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2 as SGBSTDN_MINR_CODE_2,
        SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1 as SGBSTDN_CONC_CODE_1,
        SGBSTDN.SGBSTDN_RESD_CODE,
        SGBSTDN.SGBSTDN_ADMT_CODE,
        SGBSTDN.SGBSTDN_DEPT_CODE,
        SGBSTDN.SGBSTDN_PROGRAM_1,
        f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF) as SGBSTDN_CLASS_CODE,
        f_Get_desc_fnc('STVSTST',SGBSTDN.SGBSTDN_STST_CODE, 30) as SGBSTDN_STST_DESC,
        f_Get_desc_fnc('STVLEVL', SGBSTDN.SGBSTDN_LEVL_CODE, 30) as SGBSTDN_LEVL_DESC,
        f_Get_desc_fnc('STVSTYP', SGBSTDN.SGBSTDN_STYP_CODE, 30) as SGBSTDN_STYP_DESC,
        f_Get_desc_fnc('STVDEGC', SGBSTDN.SGBSTDN_DEGC_CODE_1, 30) as SGBSTDN_DEGC_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_1, 30) as SGBSTDN_MAJR_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1, 30) as SGBSTDN_MINR_1_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1_2, 30) as SGBSTDN_MINR_1_2_DESC,
        f_Get_desc_fnc('STVMAJR', SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1, 30) as SGBSTDN_CONC_DESC,
        f_Get_desc_fnc('STVRESD', SGBSTDN.SGBSTDN_RESD_CODE, 30) as SGBSTDN_RESD_DESC,
        f_Get_desc_fnc('STVADMT', SGBSTDN.SGBSTDN_ADMT_CODE, 30) as SGBSTDN_ADMT_DESC,
        f_Get_desc_fnc('STVDEPT', SGBSTDN.SGBSTDN_DEPT_CODE, 30) as SGBSTDN_DEPT_DESC,
        f_Get_desc_fnc('STVCLAS', f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF), 30) as SGBSTDN_CLASS_DESC

   from
        SGBSTDN SGBSTDN
   ),
        -- Degree Completion Records
SHADEGR as (

    select
        SHRDGMR.SHRDGMR_PIDM as SHRDGMR_PIDM,
        SHRDGMR.SHRDGMR_SEQ_NO as SHRDGMR_SEQ_NO,
        SHRDGMR.SHRDGMR_DEGC_CODE as SHRDGMR_DEGC_CODE,
        SHRDGMR.SHRDGMR_DEGS_CODE as SHRDGMR_DEGS_CODE,
        SHRDGMR.SHRDGMR_LEVL_CODE as SHRDGMR_LEVL_CODE,
        SHRDGMR.SHRDGMR_COLL_CODE_1 as SHRDGMR_COLL_CODE_1,
        SHRDGMR.SHRDGMR_MAJR_CODE_1 as SHRDGMR_MAJR_CODE_1,
        SHRDGMR.SHRDGMR_MAJR_CODE_MINR_1 as SHRDGMR_MAJR_CODE_MINR_1,
        SHRDGMR.SHRDGMR_MAJR_CODE_CONC_1 as SHRDGMR_MAJR_CODE_CONC_1,
        SHRDGMR.SHRDGMR_APPL_DATE as SHRDGMR_APPL_DATE,
        SHRDGMR.SHRDGMR_GRAD_DATE as SHRDGMR_GRAD_DATE,
        SHRDGMR.SHRDGMR_ACYR_CODE_BULLETIN as SHRDGMR_ACYR_CODE_BULLETIN,
        SHRDGMR.SHRDGMR_MAJR_CODE_MINR_1_2 as SHRDGMR_MAJR_CODE_MINR_1_2,
        SHRDGMR.SHRDGMR_TERM_CODE_STUREC as SHRDGMR_TERM_CODE_STUREC,
        SHRDGMR.SHRDGMR_TERM_CODE_GRAD as SHRDGMR_TERM_CODE_GRAD,
        SHRDGMR.SHRDGMR_ACYR_CODE as SHRDGMR_ACYR_CODE,
        SHRDGMR.SHRDGMR_GRST_CODE as SHRDGMR_GRST_CODE,
        SHRDGMR.SHRDGMR_TERM_CODE_COMPLETED as SHRDGMR_TERM_CODE_COMPLETED,
        SHRDGMR.SHRDGMR_DEPT_CODE as SHRDGMR_DEPT_CODE,
        SHRDGMR.SHRDGMR_PROGRAM as SHRDGMR_PROGRAM,
        SHRDGMR.SHRDGMR_TERM_CODE_CTLG_1 as SHRDGMR_TERM_CODE_CTLG_1,
        SHRDGIH.SHRDGIH_PIDM as SHRDGIH_PIDM,
        SHRDGIH.SHRDGIH_DGMR_SEQ_NO as SHRDGIH_DGMR_SEQ_NO,
        SHRDGIH.SHRDGIH_HONR_CODE as SHRDGIH_HONR_CODE,
        SHRDGIH.SHRDGIH_TRANSC_PRT_IND as SHRDGIH_TRANSC_PRT_IND

   from
        SHRDGMR SHRDGMR

        left outer join SHRDGIH SHRDGIH on SHRDGIH.SHRDGIH_PIDM = SHRDGMR.SHRDGMR_PIDM
             and SHRDGIH.SHRDGIH_DGMR_SEQ_NO = SHRDGMR.SHRDGMR_SEQ_NO

   where
        SHRDGMR_SEQ_NO = (select max(SHRDGMR_SEQ_NO)
                         from SHRDGMR SHRDGMRX
                         where SHRDGMRX.SHRDGMR_PIDM = SHRDGMR.SHRDGMR_PIDM)
    ),

        -- Student Withdrawl Details
SFAWDRL as (

    select
        SFRWDRL.SFRWDRL_PIDM as SFRWDRL_PIDM,
        SFRWDRL.SFRWDRL_TERM_CODE as SFRWDRL_TERM_CODE,
        SFRWDRL.SFRWDRL_SEQ_NO as SFRWDRL_SEQ_NO,
        SFRWDRL.SFRWDRL_WDRL_CODE as SFRWDRL_WDRL_CODE,
        SFRWDRL.SFRWDRL_EFF_WDRL_DATE as SFRWDRL_EFF_WDRL_DATE,
        SFRWDRL.SFRWDRL_ESTS_CODE as SFRWDRL_ESTS_CODE,
        SFRWDRL.SFRWDRL_ESTS_DATE as SFRWDRL_ESTS_DATE,
        SFRWDRL.SFRWDRL_TIV_IND as SFRWDRL_TIV_IND,
        SFRWDRL.SFRWDRL_PROCESSED_IND as SFRWDRL_PROCESSED_IND,
        SFRWDRL.SFRWDRL_ENRL_START_DATE as SFRWDRL_ENRL_START_DATE,
        SFRWDRL.SFRWDRL_ENRL_END_DATE as SFRWDRL_ENRL_END_DATE,
        SFRWDRL.SFRWDRL_SURROGATE_ID as SFRWDRL_SURROGATE_ID

   from
        SFRWDRL SFRWDRL
    )

select

        STVTERM.STVTERM_DESC as TERM_DESC,
        SPRIDEN_ID as Banner_ID,
        SPRIDEN.SPRIDEN_LEGAL_NAME as Student_Name,
        SPBPERS.SPBPERS_PREF_FIRST_NAME Pref_Fname,
        SGBSTDN.SGBSTDN_CLASS_CODE as Class,
        SPRIDEN.GORADID_ADDITIONAL_ID as SUID,
        GOREMAL.GOREMAL_PERS_EMAIL_ADDRESS as PERS_EMAIL,
        SGBSTDN.SGBSTDN_MAJR_DESC as Program_Of_Study,
        SGBSTDN.SGBSTDN_LEVL_DESC as Class_Levl,

        case
          when f_registered_this_term(SPRIDEN.SPRIDEN_PIDM, STVTERM_CODE) = 'Y'
            then 'Y'
              else 'N'
                end as Matriculated,
        case
          when exists (select *
                   from SFRSTCR SFRSTCR
                   where SFRSTCR.SFRSTCR_PIDM = SPRIDEN_PIDM
                   and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM_CODE
                   and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE')
                   then 'Y'
                     else 'N'
                       end as Enrolled,
        case
          when exists(select * from SHRDGMR SHRDGMR where SHRDGMR.SHRDGMR_PIDM = SPRIDEN.SPRIDEN_PIDM
                             and SHRDGMR_TERM_CODE_GRAD >= STVTERM.STVTERM_CODE)
              then 'Y'
                else 'N'
                  end as DEGR_COMPLETE,
        case
          when exists(select * from SHRDGMR SHRDGMR where SHRDGMR.SHRDGMR_PIDM = SPRIDEN.SPRIDEN_PIDM
                             and SHRDGMR_TERM_CODE_GRAD >= STVTERM.STVTERM_CODE)
              then SHRDGMR_DEGC_CODE
                else ''
                  end as PROGRAM_DESC,

        (select sum(SFRSTCR_BILL_HR) from SFRSTCR SFRSTCR
        --left outer join STVTERM STVTERMX on STVTERMX.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE
        where SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
        and SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE') as Ann_Cred_Sum_0,

        (select sum(SFRSTCR_BILL_HR) from SFRSTCR SFRSTCR
        left outer join STVTERM STVTERMX on STVTERMX.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE + 1
        where SFRSTCR.SFRSTCR_TERM_CODE = STVTERMX.STVTERM_CODE
        and SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE') as Ann_Cred_Sum_1,

        (select sum(SFRSTCR_BILL_HR) from SFRSTCR SFRSTCR
        left outer join STVTERM STVTERMX on STVTERMX.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE + 2
        where SFRSTCR.SFRSTCR_TERM_CODE = STVTERMX.STVTERM_CODE
        and SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE') as Ann_Cred_Sum_2,

        (select sum(SFRSTCR_BILL_HR) from SFRSTCR SFRSTCR
        left outer join STVTERM STVTERMX on STVTERMX.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE + 3
        where SFRSTCR.SFRSTCR_TERM_CODE = STVTERMX.STVTERM_CODE
        and SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE') as Ann_Cred_Sum_3,

        (select sum(SFRSTCR_BILL_HR) from SFRSTCR SFRSTCR
        left outer join STVTERM STVTERMX on STVTERMX.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE + 4
        where SFRSTCR.SFRSTCR_TERM_CODE = STVTERMX.STVTERM_CODE
        and SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE') as Ann_Cred_Sum_4,

        (select sum(SFRSTCR_BILL_HR) from SFRSTCR SFRSTCR
        left outer join STVTERM STVTERMX on STVTERMX.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE + 5
        where SFRSTCR_TERM_CODE = STVTERMX.STVTERM_CODE
        and SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE') as Ann_Cred_Sum_5,

        (select sum(SFRSTCR_BILL_HR) from SFRSTCR SFRSTCR
        left outer join STVTERM STVTERMX on STVTERMX.STVTERM_ACYR_CODE = STVTERM.STVTERM_ACYR_CODE + 6

        where SFRSTCR.SFRSTCR_TERM_CODE = STVTERMX.STVTERM_CODE
        and SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM and SFRSTCR.SFRSTCR_RSTS_CODE = 'RE') as Ann_Cred_Sum_6,

        SPRIDEN.*,
        SGBSTDN.*,
        SPBPERS.*

from
        STVTERM STVTERM

        join SPAIDEN SPRIDEN on SPRIDEN.SPRIDEN_PIDM is not null--f_registered_this_term(SPRIDEN.SPRIDEN_PIDM, STVTERM.STVTERM_CODE) = 'Y'
        left outer join SOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        left outer join SPAPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM
        left outer join SGASTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM

        -- admission request 4 : OVERALL RETENTION
        left outer join SFAWDRL SFAWDRL on SFAWDRL.SFRWDRL_PIDM = SPRIDEN.SPRIDEN_PIDM
        left outer join SHADEGR SHADEGR on SHADEGR.SHRDGMR_PIDM = SPRIDEN.SPRIDEN_PIDM

where
      STVTERM.STVTERM_CODE = :select_term_code.STVTERM_CODE
      and SGBSTDN_STYP_CODE = :select_styp_code.STVSTYP_CODE
      and SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
      and f_registered_this_term(SPRIDEN.SPRIDEN_PIDM, STVTERM.STVTERM_CODE) = 'Y'
      and GORADID_ADID_CODE = 'SUID'
      and SGBSTDN_LEVL_CODE = 'UG'
      and SGBSTDN_STST_CODE = 'AS'

--$addfilter

--$beginorder

order by
      SPRIDEN_SEARCH_LAST_NAME,
      SPRIDEN_SEARCH_FIRST_NAME

--$endorder
